---
Title: 7.3.0
weight: 50
---

:experimental:

_Released Aug 14, 2015_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

[discrete]
===== Additional Features
* Inline Editing
	- Edit fields directly on the List and Detail View by double clicking the field.
	- To turn inline editing off for a particular field view the field in studio and uncheck "Inline Editing"

* Desktop Notifications
	- Get Meeting/Calls Notifications direct to your desktop (enable per compatible browser in user preferences)
	- View missed Notifications in the top bar

[discrete]
===== Enhancements
* Improved Mobile Navigation
	- New improved mobile menu layout, designed to give you full control, using less screen space.
* Update cases from detail view.
* Numerous workflow enhancements e.g is null, contains etc.
* Numerous reports enhancements e.g date periods, dashlet improvements.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.3[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.