---
Title: 7.3.2
weight: 50
---

:experimental:

_Released Oct 22, 2015_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.3.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3.2.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

[discrete]
===== Bug Fixes
* Fixed  #416 Studio: New Drop Down List Issue
* Fixed Email user issue in workflow
* Fixed report join issues
* Fixed #430 Create Calendar entry on mobile view
* Fixed issue #455
* Prep module builder for php7 compatibility
* Fixed issue #560
* Fixed partners link in About screen. Fixes #547
* Fixed issue #437
* Fixed issue #360
* Fixed #512 - Issue with all/more menu not being scrollable on resolutions that have a height smaller than 700px.
* Remove duplicate hidden input causing issues
* Fixed issue #506
* Fixed issue #363
* Update generatePdf.php to avoid blank pages
* Reduced padding on Layout Editor. Previously caused all fields to move to the left side of editor on some resolutions, due to lack of space.
* Removed gap between Quick-Create Plus on top-right and its Dropdown. Fixes #433
* Removed Redundant Code that caused some pages to not load on some Mobile Devices.
* Fixing multiple issues with Calendar and sidebar conflicts, sidebar white space appearing and small CSS fixes.
* Fixed issue #380
* Fixed issue #383
* Escaping the ID in the query as it comes from the $_REQUEST object.
* Adding additional checks on data.
* Adding additional checks on data.
* Fixed all major vunerabilities
* Fixed issue #381
* Fixed issue #353 This fix should be combined with Jims proposal to remove references
* Fixed issue #305
* Fixed issue #51
* Fixed injection vunerability in the delete function.
* XSS Vunerability echoing out request data.
* XSS Vunerability
* Adding the City field to the Lead Convert form in the Contact section
* Scrolling in Edit of Layout in Studio/ModuleBuilder not possible
* Update TemplateHandler.php
* Fixed issue 446
* Allow demodata in silent install
* Fixed when login session expires. Alerts now looks for the login form then stops updating the alert manager.
* Fixed #410 php didnt know to reference the button colour or the actual save button
* Add id_name to the query in create_new_list_query
* Add id_name to the query in create_new_list_query
* Skip .git folder on file system checks
* Fixed #403 - Dashlets dialog issues on Chrome.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.3.2[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.