---
Title: Releases
weight: 50
---

:experimental:

== 7.2.1

_Released this Mar 11, 2015_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.2.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2.1.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

[discrete]
===== Bug Fixes
* Fixed - GitHub issue #159 workflow number formatting issues
* Fixed - GitHub issue #158 - Currency Formatting Issue when Creating Opportunities from Quotes
* Fixed - GitHub issue #157 MsSQL compatibility issues
* Fixed - GitHub issue #156 invalid 'email' column when searching
* Fixed - GitHub issue #155 missing Project Task dropdown definition
* Fixed - GitHub issue #154 Product Category - Parent Category on list view
* Fixed - GitHub issue #153 - Forgotten Password Link
* Fixed - GitHub issue #149 - Collapsing Studio sidepanels
* Fixed - GitHub issue #147 Fatal Error when AOP function redeclared
* Fixed - GitHub issue #142 -  Issues with colour picker
* Fixed - GitHub issue #141 Next/Previous navigation on Calendar Broken
* Fixed - GitHub issue #140 Issue with custom currency field in reports
* Fixed - GitHub issue #138 Theme colour changes only save pressing 'Enter'
* Fixed - GitHub issue #135 disabled themes can still be used if users current theme
* Fixed - GitHub issue #133 Calendar Shared view Items not showing correctly
* Merged currency fix
* Updated PHP version check to check for php 5.3+
* Fix for search placeholder language and value default.
* Removed old colour selector from install
* Fix for detail view on mobile to make it more optimal.*Fix for colour picker default values in SuiteR theme, as some values were incorrect.
* Removing un-required bootstrap-theme.css, bootstrap-theme.css.map, bootstrap-theme.min.css, bootstrap.css, bootstrap.css.map and Cal.css files from themes/Su$
* Reverting Calendar change as is it causes a bug when navigating to calendar from another module.
* Icons now output directly to the page so they can pickup on the page styles and do not need to load the css for each icon.
* Moved calendar screensize check to cal.js so it only loads on the calendar module.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.2.1[here] or https://suitecrm.com/download[click here] to find the
appropriate upgrade.