---
Title: Releases
weight: 50
---

:experimental:

== 7.4.3

_Released Nov 23, 2015_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.4.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4.3.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

SuiteCRM 7.4.3, the latest cutting edge release, introduces the new
reminder meetings functionality.

This functionality allows users to more efficiently manage call and
meeting reminders with the following features:

* Add multiple reminders to a Meeting/Call so that users can be reminded
about a meeting at different intervals.
* Select if all invitees should get a reminder so that users can choose
who to remind about the Meeting/Call.
* Choose people who should not get a reminder so that users can choose
who to remind about the Meeting/Call.
* Ability to select who receives reminders so that no one else is
reminded about the Meeting/Call.

In addition to the Reminder Meetings functionality, there have also been
many bug-fixes implemented in SuiteCRM 7.4.3.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.4.3[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.