---
Title: 7.9.1
weight: 50
---

:experimental:

= 7.9.1

_Released Jun 15, 2017_

== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.9.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.1.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

[discrete]
==== Additional Features

* *Check PHP Version* - Minimum and Recommended PHP Versions upon installation and upgrade
* *Reply To, Reply All, Forward To and Delete* - https://github.com/salesagility/SuiteCRM/issues/3616[#3616 ] +
This functionality is essentially how you communicate back to your recipient.  This functionality can be done via the Detail View of the Email by the Action Buttons.

{{% notice note %}}
You can only delete a non Imported Email via the List View and an Imported Email via Detail View.
{{% /notice %}}

* *Add Signatures via User Mail Accounts* - https://github.com/salesagility/SuiteCRM/issues/3639[#3639] +
This functionality is different than in the previous email client.  A default signature can be set via the User Email Settings (within Profile) or by per Personal Account.  There is an additional dropdown when setting/editing a Personal Email Account to select an existing Signature to use.  So when you are Composing an Email you can switch between the Mail Account (the From) and the Signature will update accordingly.

* *Import Emails - set the Assign To & Relate To via Emails List and Edit View* - https://github.com/salesagility/SuiteCRM/issues/3639[#3639] +
Again, this functionality is visually different from the previous email client but using the standard user interface as other modules.  Within the ListView you can select your target emails and Import via the Bulk Actions button.  This will open up a pop up and ask to select the appropriate values.

{{% notice note %}}
When an Email has been Imported you are able to alter these fields via the standard Edit View of the Record or using the Subpanels on the DetailView.  Subpanels are only visible when an Email has been Imported.
{{% /notice %}}

* *Flag Emails - Unread, Read, Priority* https://github.com/salesagility/SuiteCRM/issues/3636[#3636 ] & https://github.com/salesagility/SuiteCRM/issues/3638[#3638 ] +
This functionality is again been redesigned to match the similar interface across the application. The User can select their Emails via the List View and flag them appropriately using the Bulks Action menu.

{{% notice note %}}
We currently at the time do not Delete Emails from the imap server.
{{% /notice %}}

* *Quick Create via Emails* https://github.com/salesagility/SuiteCRM/issues/3630[#3630 ] +
This functionality we felt required again to replicate what we have already in the application – the use of the quick create subpanels.  As the subpanels already provide this functionality the user will only be able to create new Records via Emails if the Email itself has been imported thus providing access to the subpanels.

[discrete]
==== Security
* *Security Issue* https://github.com/salesagility/SuiteCRM/issues/3698[#3698 ] - Run testinstall.php only via cli

[discrete]
==== Bug Fixes
* https://github.com/salesagility/SuiteCRM/issues/3676[#3676 ] Fixed #3676 - Module builder export and file template.
* https://github.com/salesagility/SuiteCRM/issues/1855[#1855 ] Fixed #1855 - RSS dashlet formatting
* https://github.com/salesagility/SuiteCRM/pull/3541[#3541 ] Fixed missing label
* https://github.com/salesagility/SuiteCRM/issues/3234[#3234 ] Fixed #3234 - Wrong advanced filter message in Suite7 and SuiteR themes
* https://github.com/salesagility/SuiteCRM/issues/3497[#3497 ] Fixed #3497 - /modules/Tasks/vardefs.php line
* https://github.com/salesagility/SuiteCRM/pull/3554[#3554 ] Removed unnecessary comment [language]
* https://github.com/salesagility/SuiteCRM/pull/3568[#3568 ] Fixed - Removed unused .php file (jjwg_Maps)
* https://github.com/salesagility/SuiteCRM/issues/3566[#3566 ] Resource Calendar - Days and month are not translated
* https://github.com/salesagility/SuiteCRM/issues/3617[#3617 ] Imported email in 7.9 doesn't show the body text
* https://github.com/salesagility/SuiteCRM/issues/3643[#3643 ] 7.9.0 Email: Template's Subject not replacing Subject content in editor
* https://github.com/salesagility/SuiteCRM/issues/3610[#3610 ] Cannot import email - failed to load relationship - v7.9.0
* https://github.com/salesagility/SuiteCRM/issues/3641[#3641 ] Created date/creator not shown after importing email
* https://github.com/salesagility/SuiteCRM/issues/2992[#2992 ] Cannot Duplicate Project Template
* https://github.com/salesagility/SuiteCRM/issues/3363[#3363 ] Export Target List fails (Database failure)
* https://github.com/salesagility/SuiteCRM/pull/3599[#3599 ] Order templates by name in AOP admin
* https://github.com/salesagility/SuiteCRM/issues/3578[#3578 ] Letter to PDF [Language]

*This release resolves a IMPORTANT Security Vulnerability that effect all
releases of SuiteCRM, all users of ALL previous releases are advised to
Upgrade to 7.9.1 or 7.8.5 as soon as possible.*

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.1[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security@suitecrm.com[security@suitecrm.com]

_Special thanks to https://github.com/krzyc[krzyc] for notifying us of
the security issue.