---
title: Target Lists
weight: 185
---

:experimental: ////this is here to allow btn:[] syntax used below 

== Target Lists

The Target Lists module in SuiteCRM is used to separate Targets into
groups, these can be groups of individuals that should be excluded from
a particular Campaign, test groups or a list of Targets grouped by
certain criteria, for example area or market an organisation works in.

=== Target Lists Actions

You can access the Target Lists actions from the Target Lists module
menu drop down or via the Sidebar. The Target Lists actions are as
follows:

* *Create Target List* – A new form is opened in Edit View to allow you to
create a new Target List record.
* *View Target Lists* – Redirects you to the List View for the Target
Lists module. This allows you to search and list Target List records.

To view the full list of fields available when creating a Target List,
See link:./../../appendix-a/#_targets_field_list[Target Lists Field List].

=== Managing Target Lists

* To sort records on the Target List List View, click any column title
which is sortable. This will sort the column either ascending or
descending.
* To search for a Target List, see the link:./../../introduction/user-interface/search[Search] section of
this user guide.
* To update some or all the Target Lists on the List View, use the Mass
Update panel as described in the link:./../../introduction/user-interface/record-management/#_mass_updating_records[Mass Updating Records] section of this user guide.
* To duplicate a Target List, you can click the Duplicate button on the
Detail View and then save the duplicate record.
* To delete one or multiple Target Lists, you can select multiple
records from the List View and click delete. You can also delete a
Target List from the Detail View by clicking the Delete button. For a
more detailed guide on deleting records, see the
link:./../../introduction/user-interface/record-management/#_deleting_records[Deleting Records] section 
of this user guide.
* To view the details of a Target List, click the Target List Name in
the List View. This will open the record in Detail View.
* To edit the Target List details, click Edit icon within the List View
or click the edit button on the Detail View, make the necessary changes,
and click Save.
* For a detailed guide on importing and exporting Target Lists, see the
link:./../../introduction/user-interface/record-management/#_importing_records[Importing Records] and
link:./../../introduction/user-interface/record-management/#_exporting_records[Exporting Records] sections 
of this user guide.
* To track all changes to audited fields, in the Target List, you can
click the View Change Log button on the Target List's Detail View or
Edit View.

=== Target List Types
A target list can specify individuals or organization who need to be included in a campaign or excluded 
from a campaign. This can be controlled using the following target list types:

[cols="30h,70", options="header"]
|=======
|Target List Type |Description
|Default |The normal list of targets you intend to send your campaign to.
|Seed |These targets will receive the campaign, but they won't be recorded in the statistics
for the campaign on the *View Status* page. You can use this list for people who preview and approve your
campaign email before it is actually sent to everybody else, or any other use where tracking is not desired.
|Suppression List - By Domain |Targets with email domain names on this list will be suppressed, so the campaign
email will not be sent to them. So, if you need to keep all emails belonging to "somesite.com" from going out,
you add that domain to this list.
|Suppression List - By Email Address |Targets with individual email addresses on this list will be suppressed,
so the campaign email will not be sent to them. A typical use of this list is for people who have opted-out
of from receiving emails from your company, or from a specific campaign.
|Suppression List - By Id |Here the suppression is made by linking SuiteCRM records (Contacts, Leads, Targets,
Accounts, Users) to the target list. This is different from the previous option because a single record may have
several emails which will all be excluded. When you're setting up a Newsletter Campaign, in order to have an
operational opt-out link in the emails, a suppression list of this kind is required to be linked to the Campaign.
|Test |The list of those you want to receive the test emails from the Campaign, while you're still working on
the form and content of your message. You can send your Campaign to the test list multiple times by using
the btn:[Delete Test Entries] button on the *View Status* page between re-sends.
|=======

