---
title: "Backend-end Developer Install Guide"
weight: 10
---

:imagesdir: /images/en/8.x/developer/extensions/front-end/fe-architecture-intro

{{% notice info %}}
The following documentation is for SuiteCRM Version 8+; to see documentation for Version 7, click link:../../../../developer/introduction[here].
{{% /notice %}}

== 1. Before you start

This guide is meant for developers that want to build SuiteCRM from the source code, without using the provided pre-built package.

In order to do customizations it is not required to build from the source code. We recommend that you try provided packages first, please check:

* the link:../../../admin/releases/[Release page] for more info on where to download the packages
* the link:../../../admin/installation-guide/downloading-installing/[Downloading & Installing] for more info on how to install using a package

If you don't want to use the provided packages please continue through the following steps

== 2. Setup Web Server

The first step to take is to setup the webserver.

Please go through the link:../../../admin/installation-guide/webserver-setup-guide/[Webserver Setup Guide].

== 2. Downloading and Setting up SuiteCRM

=== 2.1 Downloading the latest SuiteCRM files

Assuming you want to install a development environment from the source files, the next step is to actually retrieve the source code for the version you want to use

You can download a zip or directly checkout using git from the link:https://github.com/salesagility/SuiteCRM-Core[SuiteCRM-Core] repo on github

=== 2.2 Copy the files to your webserver root

After checking out the files copy them to your web server web root.

For `apache` webserver the web root is usually under `/var/www` or `/var/www/html`

{{% notice note %}}
Please consider the `DocumentRoot` you have set on your vhost (if using apache). See link:../../../admin/installation-guide/webserver-setup-guide#_4_configuring_url_re_writes[Web Server Setup guide - 4. Configuring URL re-writes]
{{% /notice %}}

{{% notice note %}}
Adding the files to the web root is the most typical install method, but you can have different setups, like subdomains and others.
{{% /notice %}}

=== 2.3 Set permissions

Set the required permissions

If you are using the terminal you can do this by running:

[source,bash]
----
find . -type d -not -perm 2755 -exec chmod 2755 {} \;
find . -type f -not -perm 0644 -exec chmod 0644 {} \;
find . ! -user www-data -exec chown www-data:www-data {} \;
chmod +x bin/console
----

Please have in mind that:

* The user and group name (in the above example `www-data`) needs to be replaced by the actual system user and group that your webserver runs under. This varies depending on your
operating system. Common web server users are as follows:
** `www-data` (Ubuntu Linux/Apache)
** `apache` (Linux/Apache)

* If the group name differs from the username apache is running with, you may need `0664` instead of `0644`, and `2775` instead of `2755`

=== 2.4 (optional) Creating the database

Depending on your setup, you maybe required to create the database before you go through the install process.

The install process will then create the needed tables.

== 3. Install Front-End

Before you continue with this guide you need to first setup the frontend part of the app.

Please go through the link:../front-end-installation-guide/[Front-end Developer install guide]

== 4. Install dependencies

{{% notice note %}}
You only need to do this step once. After the dependencies are installed you should only need to run it again after upgrading to a new SuiteCRM version
{{% /notice %}}


. Install  link:https://getcomposer.org/[Composer]
. Run `composer install` in the root directory of your SuiteCRM instance
. Run legacy theme compile in the root directory
- *NOTE:* the `./vendor/bin/pscss` is added as a composer dev dependency, so you need to run `composer install` *without* `--no-dev`
+
[source,bash]
----
./vendor/bin/pscss -s compressed ./public/legacy/themes/suite8/css/Dawn/style.scss > ./public/legacy/themes/suite8/css/Dawn/style.css
----

== 5. Set permissions

See link:#_2_3_set_permissions[Set permissions]

== 6. Running the installer

From SuiteCRM version 8 and above you have two ways to run installer.

* link:../../../admin/installation-guide/running-the-ui-installer/[Option 1: Installing using the installation page]
* link:../../../admin/installation-guide/running-the-cli-installer/[Option 2: Installing using the cli]
