---
Title: Настройка ограничения входа
weight: 30
---

:author: likhobory
:email: likhobory@mail.ru

== Количество попыток входа по умолчанию

По умолчанию в SuiteCRM включено ограничение входа в систему, которое срабатывает после *3* неудачных попыток входа.

Если пользователю не удастся войти в систему это количество раз подряд, появится сообщение, что выполнено максимальное количество попыток входа.

Пользователю придется подождать не менее минуты, прежде чем он сможет снова попытаться войти в систему.


== Настройка максимального количества попыток входа

Количество попыток настраивается в переменной `LOGIN_THROTTLING_MAX_ATTEMPTS`, стандартное значение которой прописано в файле *.env*, при необходимости его изменения пропишите необходимое значение в файле *.env.local*.

== Детальная настройка

Детальная настройка ограничения попыток входа в систему описана на странице 
https://symfony.com/doc/current/security.html#limiting-login-attempts[Symfony Security - Limiting Login Attempts^].
