---
Title: Настройка расположения файлов сессий
weight: 36
---

:author: likhobory
:email: likhobory@mail.ru


:toc:
:toc-title: Оглавление
:toclevels: 1

//
:sectnums:
:sectnumlevels: 2
//

:experimental:

:btn: btn:

ifdef::env-github[:btn:]  

== Глобальная настройка расположения сессий

Можно изменить расположение сессий глобально, указав новое значение для директивы link:https://www.php.net/manual/ru/session.configuration.php#ini.session.save-path[session.save_path^] в файле php.ini.


== Настройка расположения сессий для SuiteCRM 8.x

В разделе описывается настройка расположения сессий только для SuiteCRM 8.x.

[discrete]
=== Измените session_dir в устаревших файлах конфигурации

В файле `public/legacy/config.php` или `public/legacy/config_override.php` укажите новое значение для директивы `session_dir`.

Предположим, мы хотим, чтобы  файлы сеансов хранились в папке `var/sessions` папки экземпляра SuiteCRM 8, например: */<path-to-your-project>/var/sessions*

[source,php]
----
<?php
...
$sugar_config = array (
...

  'session_dir' => '/<path-to-your-suite8-project>/var/sessions',
  'session_gc' =>
  array (
    'enable' => true,
    'gc_probability' => 1,
    'gc_divisor' => 100,
  ),

----

[discrete]
=== Измените session_dir в конфигурации SuiteCRM 8

Измените настройки Symfony, прописав соответствующие значения в 
`extensions/<your-extension>/config/services/framework.yaml`

Например, для расширения `custom` путь будет выглядеть как
`extensions/custom/config/services/framework.yaml`

[source,yaml]
----
framework:
  session:
    cookie_lifetime: null
    cookie_secure: auto
    cookie_samesite: lax
    gc_probability : 1
    gc_divisor : 100
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions'

----

[discrete]
=== Очистите кеш Symfony

Из корневой папки системы выполните: 

[source,bash]
----
bin/console cache:clear
----

Либо удалите содержимое папки `/<path-to-your-suite8-project>/cache`.

{{% notice note %}}
Apache / php должны иметь доступ на чтение и запись в папку `/<path-to-your-suite8-project>/cache`. +
Это не относится к папке `/<path-to-your-suite8-project>/public/legacy/cache` - не удаляйте её содержимое.
{{% /notice %}}
