---
Title: Настройка доверенных хостов
weight: 50
---

:author: likhobory
:email: likhobory@mail.ru


== Введение

Начиная с версии 8.4.2 появилась новая проверка безопасности, позволяющая определить, является ли допустимым заголовок хоста при выполнении запроса.
Эта проверка выполняется в начале каждого запроса к серверу.

=== Настройка

При проверке используется параметр `trusted_hosts`, который можно указать в файле `public/legacy/config.php` или в файле `public/legacy/config_override.php`, где можно прописать массив строк в формате регулярных выражений для доверенных хостов, например:

[source,php]
----
<?php
...
$sugar_config = array (
...

$sugar_config['trusted_hosts'] = ['^dev\.local$', '^localhost$'];

...

----

=== Доверенные хосты по умолчанию

Если параметр `trusted_hosts` не указан в файлах `public/legacy/config.php` или `public/legacy/config_override.php`, то система будет использовать в качестве доверенных хостов следующие значения:

* значение параметра `site_url` 
* `localhost`




