---
Title: Использование секретов Symfony
weight: 60
---

:author: likhobory
:email: likhobory@mail.ru


:toc:
:toc-title: Оглавление
:toclevels: 2

//
:sectnums:
:sectnumlevels: 2
//

== Введение

Одна из замечательных особенностей использования пакетов и настроек Symfony заключается в том, что мы можем использовать весь потенциал возможностей, предлагаемых фреймфорком Symfony.
Одна из таких возможностей - секреты (см. https://symfony.com/doc/current/configuration/secrets.html[описание^] в официальной документации).

Секреты Symfony позволяют нам безопасно хранить все *конфиденциальные* значения, зашифрованные в хранилище (vault). Кроме того, эти значения также могут быть определены для отдельного окружения.

В нашем случае это может быть использовано для хранения сертификатов и закрытых ключей, к которым мы бы не хотели иметь легкий доступ.

Для добавления секретов сначала выполните действия, описанные в документе link:https://symfony.com/doc/current/configuration/secrets.html[Symfony's documentation: How to Keep Sensitive Information Secret^].

== Добавление нового секрета

После выполнения действий, необходимых для добавления секретов,вы можете добавить новые секреты, выполнив следующую команду:

*php bin/console secrets:set <NAME_OF_ENV_VARIABLE>* +
(в консоли должно появиться приглашение установить значение)

[discrete]
==== Пример:

`php bin/console secrets:set SAML_SP_PRIVATE_KEY`

== Использование секрета в настройках

Как и другие параметры секреты можно добавлять в настройки, 
используя '%env(…​)'

Следующий пример представляет собой частичный фрагмент, взятый из конфигурации saml:

[source,yaml]
----
hslavich_onelogin_saml:

  # ...

  sp:

     ...

    # SuiteCRM's private key for SAML (sp)
    privateKey: '%env(SAML_SP_PRIVATE_KEY)%'

    # ...
----

== Очистка кеша Symfony

⚠️ После внесения изменений в файл `.env.local` обязательно выполните команду `./bin/console cache:clear` с правами пользователя root или
link:../../../../admin/administration-panel/system/#_восстановление[быстрое восстановление^] из меню Администратора.