---
Title: Подготовка к обновлению
weight: 30
---

:author: likhobory
:email: likhobory@mail.ru


== Основные рекомендации

* Перед обновлением системы сверьтесь с 
link:../../compatibility-matrix[таблицей совместимости^] и убедитесь, что у вас установлены все необходимые компоненты.

* Перед выполнением обновления настоятельно рекомендуется сделать резервную копию как файлов системы, так и базы данных.

* Рекомендуем сначала запустить процесс обновления в отдельном экземпляре системы и протестировать полученный результат. 
После успешного тестирования повторите процесс обновления на рабочем экземпляре SuiteCRM.

* По умолчанию команды обновления устанавливают для директивы `error_reporting` менее строгий режим для подавления предупреждений,
 присваивая ей значение `E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE & ~E_WARNING`. +
Если вы хотите установить более строгий режим, укажите `-vvv` для каждой из команд.
Этот ключ присвоит директиве `error_reporting` значение `E_ALL`.

* Обратите внимание: в процессе обновления из корневой папки системы, а также из папки *public/legacy* могут быть удалены любые файлы и папки, не относящиеся к основным файлам SuiteCRM.

* Перед обновлением убедитесь, что переменная *APP_ENV* в файлах *.env* или *.env.local* установлена в значение `prod`.

