---
title: Основная информация
weight: 10
---

:author: likhobory
:email: likhobory@mail.ru


:toc:
:toc-title: Оглавление
:toclevels: 1

//
:sectnums:
:sectnumlevels: 3
//

:icons: font

{{% notice info %}}
Это страница содержит описание для SuiteCRM 8.x. Описание для SuiteCRM 7.x. находится link:../../../../admin/installation-guide/upgrading[здесь].
{{% /notice %}}

== Подготовка к обновлению

Перед обновлением ознакомьтесь с разделом
link:../before-start[Подготовка к обновлению]
и убедитесь, что установленное ПО будет совместимо с SuiteCRM 8.

[discrete]
=== icon:exclamation-triangle[] Необходимые действия

[cols="^1,^1,^5,^3"]
|===
|Версия |Действие |Причина | Раздел в документации

|8.7.0
|Изменение настроек
|Если настроена SAML-аутентификация, то её настройки необходимо обновить.
|link:../../configuration/saml/8.7.0-saml-configuration[Настройка SAML для версий 8.7.0+]
|===

== Шаги обновления

При обновлении обязательно учитывайте установленную версию SuiteCRM.
В зависимости от этого действия по обновлению могут различаться.
Обратите внимание, что в некоторых случаях обновление до актуальной
версии может состоять из нескольких обязательных этапов.

Кратко этапы обновления можно обозначить следующими схемами:

* Обновление с версии 8.2.x: 8.2.x => Актуальная версия

* Обновление с Release Candidate/8.0.x/8.1.x: RC/8.0/8.1 => 8.2.x => Актуальная версия

* Обновление с БЕТА-версий: БЕТА-версия => RC/8.0.x/8.1.x => 8.2.x => Актуальная версия

== Документация по обновлению 

В следующей таблице содержатся ссылки на разделы документации, 
в которых необходимые шаги обновления описаны более детально:

[cols=",^.^]
|===
|Установленная версия => Необходимая версия |Описание обновления

|Release Candidate (RC)/8.0.x/8.1.x => 8.2.x +
8.2.x => Актуальная версия
|link:../upgrading-82x-versions[Обновление c версии 8.2.x+ до более поздних версий]

|RC/8.0.x => 8.1.x
|link:../older-versions/upgrading-80-to-81-versions[Обновление с версии 8.0.x до версии 8.1.x]

|БЕТА-версия => RC
| link:../older-versions/upgrading-rc-versions[Обновление до версии RC]
|===

== Ограничения обновления

* Если установлена версия 8.0.x - 8.1.x, но вы бы хотели обновиться до версии 8.3.x или более поздней версии - сначала обновитесь до версии 8.2.x, после чего вы сможете обновиться до актуальной версии.

* В версии 8.3.1 появилась ошибка, которая привела к сбою процесса обновления, но эта ошибка была исправлена в версии 8.4.
Более подробно проблема описана в разделе
link:../additional-materials/upgrading-issues#_обновление_до_версии_8_3_1[Обновление до версии 8.3.1].
