---
Title: Upgrading to SuiteCRM 8.2.x+ versions
weight: 30
---

{{% notice note %}}
This section only applies when upgrading to a version 8.2.x or greater, i.e, 8.2.x, 8.3.x, etc.
{{% /notice %}}

{{% notice warning %}}
Check the version steps link:../general-info#_version_steps[here]
{{% /notice %}}

== 1. Download the new version package

{{% notice info %}}
For upgrading between SuiteCRM 8.x versions there aren't any upgrade specific packages. The upgrade is done using the installation package of the version we want to upgrade to.
{{% /notice %}}

*1.1.* Create the following folder on you current instance:

* `<your-suitecrm-8-root-folder>/tmp/package/upgrade`

*1.2.* Download the SuiteCRM 8 target version installable package from https://suitecrm.com/download/

*1.3.* Place the package on the `<your-suitecrm-8-root-folder>/tmp/package/upgrade` folder

== 2. Re-set the correct permissions.

== 3. Run the upgrade command

*3.1.* On your SuiteCRM 8 instance root run: `./bin/console suitecrm:app:upgrade -t "<version>"`,
where `<version>` is the name on the SuiteCRM 8 package you've downloaded, i.e. `SuiteCRM-8.6.0`:

[source, bash]
----
./bin/console suitecrm:app:upgrade -t SuiteCRM-8.6.0
----

*3.2.* Re-set the correct permissions.

== 4. Run the post upgrade command

*4.1.* On your SuiteCRM 8 instance root run: `./bin/console suitecrm:app:upgrade-finalize -t "<version>"`, i.e.:

[source, bash]
----
./bin/console suitecrm:app:upgrade-finalize -t SuiteCRM-8.6.0
----

*4.2.* Re-set the correct permissions.

== 5. (Optional) Restart server to reset/clear php level cache

If you are using `opcache`, `apcu` or other php caches, you may need to restart your webserver for the new code to take effect.

== 6. Open your instance

If all the above steps went as expected, you should now be able to login into your instance.
