---
Title: Обновление c версии 8.2.x+ до более поздних версий
weight: 30
---

:author: likhobory
:email: likhobory@mail.ru


:toc:
:toc-title: Оглавление
:toclevels: 1

//
:sectnums:
:sectnumlevels: 3
//


{{% notice note %}}
В этом разделе описывается обновление версий 8.2.x до более поздних версий.
{{% /notice %}}

{{% notice warning %}}
Если обновляемая версия SuiteCRM меньше 8.2.x - обратитесь к разделу link:../general-info/#_шаги_обновления[Шаги обновления].
{{% /notice %}}

== Скачивание необходимой версии SuiteCRM


.. Скачайте необходимый пакет со страницы https://suitecrm.com/download/
+
При обновлении между версиями SuiteCRM 8.x **нет необходимости в каком-либо специальном пакете обновления.** 
Для этого используется обычный установочный пакет той версии, до которой вы планируете произвести обновление. +
Например, для обновления с версии 8.2.x до версии 8.6.0 используйте пакет `SuiteCRM-8.6.0.zip`.

.. В установленном экземпляре системы создайте  папку `<your-suitecrm-8-root-folder>/tmp/package/upgrade`.

.. Скопируйте скачанный пакет в созданную папку `<your-suitecrm-8-root-folder>/tmp/package/upgrade`.

== Выполнение обновления

.. ⚠️ Установите необходимые link:../../installation-guide/downloading-installing/#_установка_прав[права доступа^].

.. Из корневой папки SuiteCRM 8 выполните команду: `./bin/console suitecrm:app:upgrade -t "<версия>"`, +
где `<версия>` - название пакета  с устанавливаемой SuiteCRM 8, например: `SuiteCRM-8.6.0`
+
*Пример:* 
+
[source,console]
-----
./bin/console suitecrm:app:upgrade -t SuiteCRM-8.6.0
-----

.. ⚠️ Установите ещё раз права доступа.

.. Выполните команду финализации
+
Из корневой папки SuiteCRM 8 выполните команду: `./bin/console suitecrm:app:upgrade-finalize -t "<версия>"`, +
где `<версия>` - название пакета  с устанавливаемой SuiteCRM 8, например: `SuiteCRM-8.6.0`
+
*Пример:* 
+
[source,console]
-----
./bin/console suitecrm:app:upgrade-finalize -t SuiteCRM-8.3.0
-----

.. ⚠️ Переустановите ещё раз права доступа.

== Очистка кеша php (опционально)

Если вы используете `OPCache`, `ACP` или другие оптимизаторы,  может потребоваться перезапуск веб-сервера, чтобы применённые изменения вступили в силу.

== Вход в систему

Если все вышеперечисленные шаги были выполнены правильно,  вы сможете войти в обновленный экземпляр SuiteCRM 8.
