---
title: Установка SuiteCRM
weight: 20
---

:author: likhobory
:email: likhobory@mail.ru

:toc:
:toc-title: Оглавление
:toclevels: 3

//
:sectnums:
:sectnumlevels: 2
//


{{% notice info %}}
Это страница содержит описание для SuiteCRM 8.x. Описание для SuiteCRM 7.x. находится link:../../../../admin/installation-guide/downloading-installing[здесь].
{{% /notice %}}

Если вы впервые устанавливаете SuiteCRM, следуйте этому описанию. Если вы обновляете ранее установленную вервию, обратитесь к разделу link:../upgrading[Обновление системы].

== Настройка веб-сервера

Настройте необходимый веб-сервер или проверьте настройки существующего, как это описано в разделе 
link:../webserver-setup-guide/[Настройка веб-сервера].

== Подготовка к установке

 . Загрузите SuiteCRM со страницы https://suitecrm.com/download[https://suitecrm.com/download^].
 . Скопируйте загруженные файлы из архива в соответствующую папку веб-сервера и установите необходимые права (см. ниже).

{{% notice note %}}
У веб-сервера *apache* в качестве корневой папки как правило используется папка `/var/www` или `/var/www/html`. Корневая папка указана в параметре `DocumentRoot` файла конфигурации *apache*.
{{% /notice %}}

== Установка прав

Перейдите в папку, в которую был распакован пакет SuiteCRM и установите права, как это показано ниже:

[source,bash]
----
find . -type d -not -perm 2775 -exec chmod 2755 {} \;
find . -type f -not -perm 0644 -exec chmod 0644 {} \;
find . ! -user www-data -exec chown www-data:www-data {} \;
chmod +x bin/console
----

* При необходимости замените пользователя *www-data* на пользователя, под которым запущен веб-сервер. +
Пользователи, имеющие полный доступ к файлам системы, могут различаться в зависимости от используемой конфигурации системы, например: 
** www-data (Linux/Apache)
** apache   (Linux/Apache)

* Если имя группы отличается от имени пользователя, под которым работает apache, вам могут понадобиться права `0664` вместо `0644` и `2775` вместо `2755`. 

{{% notice note %}}
Приведённые выше команды могут различаться в зависимости от используемой вами ОС. Если у вас возникли трудности с установкой прав - задайте необходимые вопросы на нашем link:https://community.suitecrm.com[форуме^].
{{% /notice %}}

{{% notice note %}}
В зависимости от настроек, вам, возможно, потребуется создать базу данных *до* установки системы. В процессе установки в базу данных будут добавлены необходимые таблицы.
{{% /notice %}}

== Проверка идентификатора сессии

SuiteCRM (по крайней мере, до версии 8.4.0) предполагает, что идентификатор сессии PHP (session.name) установлен в значение *PHPSESSID*. Если при вызовах `/api/graphql` появляется ошибка *403*, установите параметр `session.name` в файле `php.ini` в значение `PHPSESSID`.

== Установка системы

Возможны два варианта установки:

* Используя мастер установки в 
link:../running-the-ui-installer[веб-интерфейсе браузера]
* Используя установку из 
link:../running-the-cli-installer[командной строки]

