---
title: Установка SuiteCRM
weight: 20
---

:author: likhobory
:email: likhobory@mail.ru

:toc:
:toc-title: Оглавление
:toclevels: 3

:experimental:

:imagesdir: /images/ru/admin/Installing

ifdef::env-github[:imagesdir: ./../../../../master/static/images/ru/admin/Installing]

:btn: btn:

ifdef::env-github[:btn:]

{{% notice info %}}
Это страница содержит описание для SuiteCRM Версии 8. Описание для SuiteCRM версии 7 находится link:../../../../admin/installation-guide/downloading-installing[здесь].
{{% /notice %}}

Если вы впервые устанавливаете SuiteCRM, следуйте этому описанию. Если вы обновляете ранее установленную вервию, обратитесь к разделу link:../upgrading[Обновление системы].

== Подготовка к установке

 . Установите версии PHP, веб-сервера, и базы данных, указанные в link:../../compatibility-matrix[Таблице совместимости^].
 . Загрузите SuiteCRM со страницы https://suitecrm.com/download
 . Скопируйте загруженные файлы из архива в соответствующую папку веб-сервера и установите необходимые права (см. ниже).


{{% notice note %}}
Обратите внимание, что часть программного обеспечения, указанного в таблице совместимости,  необходима только для разработчиков, и при стандартной установке *нет необходимости* в установке node, angular и yarn/npm. Загруженный пакет уже содержит все необходимые файлы в папке *public*.
{{% /notice %}}

{{% notice note %}}
Если вы используете веб-сервер *apache*, убедитесь, что модуль `mod_rewrite` включён и корректно настроен. Модуль используется при вызове SuiteCRM-Core API, и если перенаправление отключено, вы получите ошибку `404`.
{{% /notice %}}

== Установка прав

 . Выберите папку веб-сервера, в которую будет установлен SuiteCRM (чаще все это корневая папка сервера, либо одна из подпапок)
 . Распакуйте загруженный архив в выбранную папку.
 . Установите соответствующие права, как это показано ниже:

[source,bash]
----
find . -type d -not -perm 2775 -exec chmod 2775 {} \;
find . -type f -not -perm 0644 -exec chmod 0644 {} \;
find . ! -user www-data -exec chown www-data:www-data {} \;
chmod +x bin/console
----

* При необходимости замените пользователя *www-data* на пользователя, под которым запущен веб-сервер.

Пользователи, имеющие полный доступ к файлам системы, могут различаться в зависимости от используемой конфигурации системы, например: 

** www-data (Linux/Apache)
** apache   (Linux/Apache)
** nobody   (Linux/Apache)
** IUSR_computerName (Windows/IIS)

{{% notice note %}}
Приведённые выше команды могут различаться в зависимости от используемой вами ОС. Если у вас возникли трудности с установкой прав - задайте необходимые вопросы на нашем link:https://community.suitecrm.com[форуме^].
{{% /notice %}}

== Шаги установки

 . Установите систему (suite core и legacy)
 
{{% notice note %}}
В зависимости от настроек, вам, возможно, потребуется создать базу данных *до* выполнения следующей команды, которая создаст в базе данных необходимые таблицы.
{{% /notice %}}

* Выполните команду:

** Вариант 1: `./bin/console suitecrm:app:install` без параметров, команда сама запросит необходимые данные 
** Вариант 2: `./bin/console suitecrm:app:install` с указанными ниже параметрами:
+
[source,bash]
----
./bin/console suitecrm:app:install -u "admin_username" -p "admin_password" -U "db_user" -P "db_password" -H "db_host" -N "db_name" -S "site_url" -d "demo_data"
----
+
где:

*** *“admin_username”* - логин администратора системы
*** *"admin_password"* - пароль администратора системы
*** *"db_user"* - логин администратора базы данных
	**** Убедитесь, что указываемый администратор БД имеет необходимые права на создание и запись в базу данных SuiteCRM.
	**** Для MySQL, MariaDB и SQL Server, установщик по умолчанию выбирает администратора системы в качестве пользователя базы данных. Приложение SuiteCRM использует пользователя базы данных SuiteCRM для связи с базой данных SuiteCRM. 
*** *"db_password"* - пароль администратора базы данных
*** *"db_host"* - имя хоста для  MySQL, MariaDB или SQL Server. Если БД расположена на одной сервере с веб-сервером, то по умолчанию используется значение`localhost`.
*** *"db_name"* - имя базы данных для устанавливаемого экземпляра системы
*** *"site_url"* - адрес устанавливаемого экземпляра системы
*** *"demo_data"* - добавление в БД демонстрационных данных. Допустимые значения: `yes` или `no`. 

Пример:

[source,bash]
----
./bin/console suitecrm:app:install -u "admin" -p "mypass" -U "root" -P "dbpass" -H "mariadb" -N "suitecrm" -S "https://yourcrm.com/" -d "yes"
----

[start=2]
 . По завершении установки ещё раз установите соответствующие права, как это было показано выше, при необходимости заменив пользователя *www-data* на пользователя, под которым запущен веб-сервер: 

[source]
----
find . -type d -not -perm 2775 -exec chmod 2775 {} \;
find . -type f -not -perm 0644 -exec chmod 0644 {} \;
find . ! -user www-data -exec chown www-data:www-data {} \;
chmod +x bin/console
----

[start=3]
 . Установите параметр `DocumentRoot` в значение */{root}/{suitecrm-8}/public*. Как правило параметр расположен в файле `/etc/apache2/sites-available/applications.conf`.
+ 
{{% notice warning %}}
Настоятельно рекомендуется настроить корневую папку веб-сервера или виртуальный хост, указав именно папку *public* в качестве корневой папки, чтобы другие файлы и папки не были доступны из внешней сети.
{{% /notice %}}
+
 . После всех вышеописанных действий экземпляр системы будет доступен по адресу *\https://yourcrm.com*

