---
Title: Переход с версий SuiteCRM 7.x на версию SuiteCRM 8.x
weight: 40
---

:author: likhobory
:email: likhobory@mail.ru


:toc:
:toc-title: Оглавление
:toclevels: 1

:experimental:

:btn: btn:

ifdef::env-github[:btn:]  


==  Предварительная подготовка

. Прежде всего убедитесь, что установленная система соответствует требованиям, указанным в 
link:../../compatibility-matrix[Таблице совместимости^].

Вначале рекомендуется запустить процесс перехода на *тестовом экземпляре системы* 
и уже после удачного переноса запустить процесс на рабочем экземпляре системы.

{{% notice warning %}}
Не забудьте сделать резервные копии файлов системы и БД. 
{{% /notice %}}

. Обновите  установленную версию SuiteCRM 7.x до последней версии ветки 7.12.x. +
Обязательно выполните все действия по обновлению вручную, если они отдельно описаны в примечаниях к релизу для соответствующей версии.

. По умолчанию команды обновления устанавливают для директивы `error_reporting` менее строгий режим 
для подавления предупреждений, присваивая ей значение `E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE & ~E_WARNING`. +
Если вы хотите установить более строгий режим, укажите `-vvv` для каждой из команд.
Этот ключ присвоит директиве `error_reporting` значение `E_ALL`.


== Переход с SuiteCRM 7.12.x на SuiteCRM 8.x

{{% notice note %}}
Запускайте процесс перехода только после обновления до последней версии SuiteCRM 7.12.x.
{{% /notice %}}


=== Загрузка пакета

 . Загрузите необходимый пакет (migration package) с  link:https://suitecrm.com/upgrade-suitecrm/[этой страницы^].

 . Распакуйте скачанный архив в папку, в которой должна быть установлена SuiteCRM 8.x 

 . При необходимости установите соответствующие права доступа.

=== Копирование файлов SuiteCRM 7.12.x 

 . Скопируйте папку с уже установленной SuiteCRM 7.12.x в папку `public` устанавливаемой SuiteCRM 8.x. 

 . Переименуйте скопированную папку с SuiteCRM 7.12.x в `legacy`.

 . При необходимости установите соответствующие права доступа.

{{% notice tip %}}
Если вы используете git, настоятельно рекомендуется удалить папку `.git` из папки `public/legacy/`.
{{% /notice %}}

=== Права доступа

Права доступа должны быть установлены таким образом, чтобы пользователь, работающий в консоли, имел достаточно прав для чтения и записи.

=== Выполнение команды предварительной подготовки

 . Из корневой папки SuiteCRM 8 запустите: 
 
[source,bash]
-----
./bin/console suitecrm:app:setup-legacy-migration
-----

 . Вам будет предложено вручную выполнить ряд действий по изменению некоторых директив в файле конфигурации, расположенном в папке `legacy`:

* Установите директиву `session_dir` в пустое значение (''). По окончании перехода вы можете  установить необходимое значение `session_dir`. +
Обратите внимание, что настройка `session_dir` в SuiteCRM 8 отличается от SuiteCRM 7,  детали описаны в разделе
link:../../configuration/sessions-configuration[Настройка сессий^].

* Измените значение директивы `site_url` на адрес, по которому будет доступна SuiteCRM 8.x.

{{% notice note %}}
Если виртуальный сервер не указывает на каталог  *public* в корневой папке SuiteCRM 8, то необходимо добавить */public*  к значению параметра *site_url*, например `'site_url' => '\https://your-host/crm/public',`.
{{% /notice %}}

[start=3]
.  Вам будет предложено вручную выполнить ряд действий по изменению директивы *RewriteBase* в файле `.htaccess`, расположенном в папке `legacy`: 

Если виртуальный сервер указывает на каталог *legacy*, то директива *RewriteBase* должна выглядеть как `RewriteBase /legacy`. +
В противном случае необходимо указать путь до папки *public*.
Например, если адрес сайта -  *\https://your-host/crm/public*, то директива *RewriteBase* должна выглядеть как `RewriteBase /crm/public/public`.

=== Выполнение команды обновления

Из корневой папки SuiteCRM 8 запустите: `./bin/console suitecrm:app:upgrade -t "<версия>"`, +

где `<версия>` - название пакета  с устанавливаемой SuiteCRM 8, например: `SuiteCRM-8.3.0`

*Пример:* 

[source,bash]
-----
./bin/console suitecrm:app:upgrade -t SuiteCRM-8.3.0
-----

=== Выполнение команды финализации

{{% notice note %}}
Если обновляемый экземпляр системы был значительно кастомизирован, на этом этапе могут возникнуть проблемы.
Убедитесь, что изменённый код совместим как минимум с php версии 7.4.
{{% /notice %}}

Из корневой папки SuiteCRM 8 запустите: 

[source,bash]
-----
./bin/console suitecrm:app:upgrade-finalize
-----

==== Режимы слияния метаданных

В этой команде вы можете указать режим слияния, который вы хотите использовать при объединении метаданных,
 указав необходимый режим после ключа `-m`.

По умолчанию используется режим `keep`.

. Режим *_KEEP_*

* Этот режим сохранит все существующие ранее метаданные, слияние выполняться не будет.
* Этот режим используется по умолчанию.

В консоли выполните: 

[source,bash]
-----
./bin/console suitecrm:app:upgrade-finalize -m keep
-----

[start=2]
. Режим *_MERGE_*

* Этот режим попытается объединить все существующие ранее метаданные с новыми метаданными. Объединение будет выполнено для каждого модуля.
* Объединенные метаданные помещаются в папку *custom* соответствующего модуля:  `public/legacy/custom/<Module>/metadata`
* В эту же папку добавляется файл резервной копии предыдущей версии метаданных

В консоли выполните: 

[source,bash]
-----
./bin/console suitecrm:app:upgrade-finalize -m merge
-----

[start=3]
. Режим *_OVERRIDE_*

* Этот режим заменит все текущие настройки новой версией  метаданных.

{{% notice warning %}}
В результате будут удалены все текущие файлы настроек из папки `public/legacy/custom/<Module>/metadata`!
{{% /notice %}}

В консоли выполните: 

[source,bash]
-----
./bin/console suitecrm:app:upgrade-finalize -m override
-----

=== Переустановка прав

Если во время процесса миграции вы использовали пользователя/группу, которые не совпадают с теми, которые используются веб-сервером,
 вам следует переустановить соответствующие права.

Если все вышеперечисленные шаги были выполнены правильно,  вы сможете войти в обновленный экземпляр SuiteCRM 8.
