---
title: Установка из командной строки
weight: 22
---

:author: likhobory
:email: likhobory@mail.ru

:toc:
:toc-title: Оглавление
:toclevels: 3

//
:sectnums:
:sectnumlevels: 2
//


{{% notice info %}}
Это страница содержит описание для SuiteCRM 8.x. Описание для SuiteCRM 7.x. находится link:../../../../admin/installation-guide/downloading-installing[здесь].
{{% /notice %}}

== Введение

В разделе описывается установка SuiteCRM через командную строку.

{{% notice note %}}
Перед установкой убедитесь, что выполнены все необходимые шаги, описанные в разделе 
link:../downloading-installing/[Установка SuiteCRM].
{{% /notice %}}

== Установка из командной строки

 . Выполните команду:

** Вариант 1: `./bin/console suitecrm:app:install` без параметров, команда сама запросит необходимые данные 
** Вариант 2: `./bin/console suitecrm:app:install` с указанными ниже параметрами:
+
[source,bash]
----
./bin/console suitecrm:app:install -u "admin_username" -p "admin_password" -U "db_user" -P "db_password" -H "db_host" -N "db_name" -Z "db_port" -S "site_url" -d "demo_data"
----
+
где:

*** *"admin_username"* - логин администратора системы
*** *"admin_password"* - пароль администратора системы
*** *"db_user"* - логин пользователя базы данных
	**** Убедитесь, что указываемый пользователь БД имеет необходимые права на создание и запись в базу данных SuiteCRM.
*** *"db_password"* - пароль пользователя базы данных
*** *"db_host"* - имя хоста для  MySQL, MariaDB или SQL Server. Если БД расположена там же, где и веб-сервер, то используется значение `localhost`.
+
{{% notice note %}}
В некоторых системах при указании `localhost` система попытается установить соединение через сокет. Однако в настоящее время подключение через сокет не поддерживается, поэтому в таких случаях лучше всего использовать ip-адрес `127.0.0.1`.
{{% /notice %}}
+
*** *"db_name"* - имя базы данных для устанавливаемого экземпляра системы
*** *"db_port"* - Порт, используемый базой данных. Указывайте этот параметр в том случае, если база данных использует нестандартный порт. По умолчанию используется стандартный порт *3306*.
*** *"site_url"* - адрес устанавливаемого экземпляра системы (при необходимости скопируйте данные из адресной строки браузера)
*** *"demo_data"* - добавление в БД демонстрационных данных. Допустимые значения: `yes` или `no`. 

Пример:

[source,bash]
----
./bin/console suitecrm:app:install -u "admin" -p "mypass" -U "root" -P "dbpass" -H "localhost" -N "suitecrm" -S "https://yourcrm.com/" -d "no"
----

{{% notice tip %}}
В примере указаны только *обязательные* аргументы. Для получения полного списка всех доступных аргументов выполните следующую команду из папки с установленной системой: `./bin/console suitecrm:app:install --help`.
{{% /notice %}}

[start=2]
 . По завершении установки ещё раз установите соответствующие права:
 
[source,bash]
----
find . -type d -not -perm 2755 -exec chmod 2755 {} \;
find . -type f -not -perm 0644 -exec chmod 0644 {} \;
find . ! -user www-data -exec chown www-data:www-data {} \;
chmod +x bin/console
----

Ещё раз обратите внимание на следующее: 

* Имя пользователя, под которым запущен веб-сервер. При необходимости замените пользователя *www-data* на пользователя, под которым запущен веб-сервер. +
Пользователи, имеющие полный доступ к файлам системы, могут различаться в зависимости от используемой конфигурации системы, например: 
** www-data (Linux/Apache)
** apache   (Linux/Apache)

* Если имя группы отличается от имени пользователя, под которым работает apache, вам могут понадобиться права `0664` вместо `0644` и `2775` вместо `2755`. 

== Заключительная проверка файлов конфигурации

 .  Файл `public/legacy/config.php` 

Если виртуальный сервер не указывает на каталог  *public* в корневой папке SuiteCRM 8, то необходимо добавить */public*  к значению директивы *site_url*, например `'site_url' => 'https://your-host/crm/public',`.

[start=2]
 . Файл `public/legacy/.htaccess`

Если виртуальный сервер указывает на каталог *legacy*, то директива *RewriteBase* должна выглядеть как `RewriteBase /legacy`. +
В противном случае необходимо указать путь до папки *public*.
Например, если адрес сайта -  *\https://your-host/crm/public*, то директива *RewriteBase* должна выглядеть как `RewriteBase /crm/public/legacy`.

== Вход в систему

После всех вышеописанных действий экземпляр системы будет доступен по адресу *\https://yourcrm.com*
 
