---
title: Configure SuiteCRM
weight: 3
---

:imagesdir: ./../../../../images/en/developer

:toc:
:toclevels: 4

=== Apache2 Server

Those who have upgraded from an older version of SuiteCRM, will need to
run the "rebuild .htaccess" tool. As the API uses "friendly" urls to
define resources. It may be possible to use the API without this
feature. However, you will want the .htaccess file to configure the
_/api_ entrypoint to the _lib/API/public_ folder.

*The Mod Rewrite Apache2 Module must be installed and configured*

=== IIS Server

IIS Server Administrators will need create a web.config file manually
configure the _/api_ entrypoint to the _lib/API/public_ folder.

*It is important to ensure that the lib/API/OAuth2/ directory cannot be
accessed over a HTTP request*

=== Configure Encryption Keys
Provided that the file permissions enable your web server to write to lib/API/OAuth2/ folder, SuiteCRM will attempt
to auto-generate the keys in this location.

==== Generating public and private keys manually

To generate the private key run this command on the terminal:

`cd /path/to/instance/lib/API/OAuth2`

`openssl genrsa -out private.key 1024`

`openssl rsa -in private.key -pubout -out public.key`
