---
title: JSON API (new)
weight: 8
---

:toc:
:toclevels: 4

== Before you start calling endpoints

Please check the following below:

=== Composer

Install composer packages with

[source,php]
composer install

=== Generate private and public.key for OAUTH2

SuiteCRM Api uses OAuth2 protocol, which needs public and private keys.

First, open a terminal and go to `{{your-SuiteCRM-root}}/Api/V8/OAuth2`

Generate a private key:
[source,php]
openssl genrsa -out private.key 2048

Then a public key:
[source,php]
openssl rsa -in private.key -pubout -out public.key

If you need more information about generating, https://oauth2.thephpleague.com/installation/[please visit this page].

The permission of the key files must be 600 or 660, so change it.
[source,php]
sudo chmod 600 private.key public.key

Also, you have to be sure that the config files are owned by PHP.
[source,php]
sudo chown www-data:www-data p*.key

=== Update encryption key

OAuth2's AuthorizationServer needs to set an encryption key for security reasons. For doing this, please, go to `Api/V8/Config/services/middlewares.php` and find the row starts with `$server->setEncryptionKey('');`

Now update its value with generating a new one using `base64_encode(random_bytes(32))`

If you need more information about this issue, https://oauth2.thephpleague.com/v5-security-improvements/[please visit this page].

=== If you are using Postman

You can easily import postman collections of all endpoint, you can find it in `Api/docs/postman`

== Authentication

SuiteCRM Api allows two kind of grant types:

* Client credential
* Password

.Token request parameters
|===
|Parameter |Description

|*Access Token URL*
|{{your-SuiteCRM-url}}/Api/access_token

|*Username*
|Only available for Password grants. Must be a valid SuiteCRM user name.

|*Password*
|Only available for Password grants. Password for the selected user.

|*Client ID*
|Client ID exists in OAuth2Clients module's ID. Must be a valid GUID.

|*Client Secret*
|Client secret is also in OAuth2Clients module as SHA256 generated value.

|*Scopes*
|Scopes haven't implemented yet
|===

== Available parameters

According to JsonApi specification, the available parameters are the following depending on the GET endpoint:

=== Fields

Fields can filter on attribute object. Allowed keys are valid bean properties.

Example:

[source,php]
{{your-SuiteCRM-url}}/V8/module/Accounts/11a71596-83e7-624d-c792-5ab9006dd493?fields[Accounts]=name,account_type

Result:

[source,json]
{
    "data": {
        "type": "Account",
        "id": "11a71596-83e7-624d-c792-5ab9006dd493",
        "attributes": {
            "name": "lol1111",
            "account_type": "Customer"
        },
        "relationships": {
            "AOS_Contracts": {
                "links": {
                    "related": "/V8/module/Accounts/11a71596-83e7-624d-c792-5ab9006dd493/relationships/aos_contracts"
                }
            }
        }
    }
}

=== Page

Page can filter beans and set pagination. Allowed key are *number* and *size*.

* *page[number*] : number of the wanted page
* *page[size*] : size of the result

Example:

[source,php]
{{suitecrm71.url}}/V8/module/Accounts?fields[Account]=name,account_type&page[number]=3&page[size]=1

Result:

[source,json]
{
    "meta": {
        "total-pages": 54
    },
    "data": [
        {
            "type": "Account",
            "id": "e6e0af95-4772-5773-ae70-5ae70f931feb",
            "attributes": {
                "name": "",
                "account_type": ""
            },
            "relationships": {
                "AOS_Contracts": {
                    "links": {
                        "related": "/V8/module/Accounts/e6e0af95-4772-5773-ae70-5ae70f931feb/relationships/aos_contracts"
                    }
                }
            }
        }
    ],
    "links": {
        "first": "/V8/module/Accounts?fields[Account]=name,account_type&page[number]=1&page[size]=1",
        "prev": "/V8/module/Accounts?fields[Account]=name,account_type&page[number]=2&page[size]=1",
        "next": "/V8/module/Accounts?fields[Account]=name,account_type&page[number]=4&page[size]=1",
        "last": "/V8/module/Accounts?fields[Account]=name,account_type&page[number]=54&page[size]=1"
    }
}

== Endpoints

=== Logout

[source,php]
GET {{your-SuiteCRM-url}}/V8/logout

=== Get a module by ID

[source,php]
GET {{your-SuiteCRM-url}}/V8/module/{moduleName}/{id}

Available parameters: fields

=== Get collection of modules

[source,php]
GET {{your-SuiteCRM-url}}/V8/module/{moduleName}

Available parameters: fields, page

=== Create a module record

[source,php]
POST {{your-SuiteCRM-url}}/V8/module/{moduleName}

Example body:

[source,json]
{
  "data": {
    "type": "Accounts",
    "attributes": {
      "name": "Test"
    }
  }
}

=== Update a module record

[source,php]
PATCH {{your-SuiteCRM-url}}/V8/module/{moduleName}/{id}

Example body:

[source,json]
{
  "data": {
    "type": "Accounts",
    "id": "e6e0af95-4772-5773-ae70-5ae70f931fe"
    "attributes": {
      "name": "Test"
    }
  }
}


=== Delete a module record

[source,php]
DELETE {{your-SuiteCRM-url}}/V8/module/{moduleName}/{id}
