---
title: Customization
weight: 90
---

:imagesdir: /images/en/developer


== Customization

Each customization should be in a base folder `custom/Extension/application/Ext/Api/V8/`.
See more about Slim framework at https://www.slimframework.com.

Extending Slim configuration in `custom/application/Ext/Api/V8/slim.php` is a native php file should returns an array of slim configurations.
Additional configuration will be merged into the default slim configuration.
[source,php]
return [ /* slim configuration here ...*/ ];


Extending Routes in `custom/application/Ext/Api/V8/Config/routes.php` is a native php file given `$app` variable as a Slim application.
Additional routes will be added into the default slim application and available in URL [SuiteCRM-path]/Api/V8/custom
custom/application/Ext/Api/V8/Config/routes.php
[source,php]
// example for custom POST route entry:
$app->post('/my-route/{myParam}', 'MyCustomController:myCustomAction');


Extending Services in `custom/application/Ext/Api/V8/services.php` is a native php file should returns an array of slim services.
Additional services will be merged into the default slim services.
custom/application/Ext/Api/V8/services.php
[source,php]
// example of custom service:
return ['myCustomService' => function() {
    return new MyCustomService();
}];


Extending BeanAliases in `custom/application/Ext/Api/V8/beanAliases.php` is a native php file should returns an array of custom bean aliases.
custom/application/Ext/Api/V8/beanAliases.php
[source,php]
// example of custom service:
return [MyCustom::class => 'MyCustoms'];


Extending Controllers in `custom/application/Ext/Api/V8/controllers.php` is a native php file should returns an array of custom controllers.
custom/application/Ext/Api/V8/controllers.php
[source,php]
// example of custom controllers:
return [MyCustomController::class => function(Container $container) {
    return new MyCustomController();
}];


Extending Factories in `custom/application/Ext/Api/V8/factories.php` is a native php file should returns an array of custom factories.
custom/application/Ext/Api/V8/factories.php
[source,php]
// example of custom factories:
return [MyCustomFactory::class => function(Container $container) {
    return new MyCustomFactory();
}];


Extending Globals in `custom/application/Ext/Api/V8/globals.php` is a native php file should returns an array of custom globals.
custom/application/Ext/Api/V8/globals.php
[source,php]
// example of custom globals:
return [MyCustomGlobal::class => function(Container $container) {
    return new MyCustomFactory();
}];


Extending Helpers in `custom/application/Ext/Api/V8/helpers.php` is a native php file should returns an array of custom helpers.
custom/application/Ext/Api/V8/helpers.php
[source,php]
// example of custom helpers:
return [MyCustomHelper::class => function(Container $container) {
    return new MyCustomHelper();
}];



Extending Middlewares in `custom/application/Ext/Api/V8/middlewares.php` is a native php file should returns an array of custom middlewares.
custom/application/Ext/Api/V8/middlewares.php
[source,php]
// example of custom middlewares:
return [MyCustomMiddleware::class => function(Container $container) {
    return new MyCustomMiddleware();
}];



Extending Params in `custom/application/Ext/Api/V8/params.php` is a native php file should returns an array of custom params.
custom/application/Ext/Api/V8/params.php
[source,php]
// example of custom params:
return [MyCustomParam::class => function(Container $container) {
    return new MyCustomParam();
}];



Extending Validators in `custom/application/Ext/Api/V8/validators.php` is a native php file should returns an array of custom validators.
custom/application/Ext/Api/V8/validators.php
[source,php]
// example of custom validators:
return [MyCustomValidator::class => function(Container $container) {
    return new MyCustomValidator();
}];


=== Basic example of API customization
Create a file for new custom route: `[SuiteCRM-path]/custom/application/Ext/Api/V8/Config/routes.php` with the following content:
[source,php]
<?php
$app->get('/hello', function() {
    return 'Hello World!';
});

