---
title: "Local Setup to Contribute to Documentation"
weight: 1
---

= Local Setup to Contribute to Documentation

In order to contribute to the Documentation efforts, you can edit pages directly on Github. But if you want a more powerful setup for a better work experience, you can choose to set up a local copy of the files, install our build engine Hugo, and build and serve the site locally.

WARNING: this is very provisional and will be made into a proper Guide when time allows.

`sudo apt-get update`

`sudo apt-get install git`

`wget https://github.com/gohugoio/hugo/releases/download/v0.31/hugo_0.31_Linux-64bit.deb`

`sudo dpkg -i hugo_0.31_Linux-64bit.deb`

Check Hugo is operational with 

`hugo version`

Go to some appropriate directory, and use this command to create the SuiteDocs subtree and download everything:

`git clone https://github.com/salesagility/SuiteDocs.git`

`cd SuiteDocs`

`bundle install`

That should pick up the local Gemfile asking for the "asciidoctor" package and install it. Check with:

`asciidoctor --version`

You're ready to go! To build the site you can simply type 

`hugo`

But you won't be using that very often because it's enough to launch the local web server, and any outstanding changes will get rebuilt:

`hugo server --bind=0.0.0.0  --baseUrl=http://10.0.0.200`

(change that `10.0.0.200` into whatever is your local IP address. This will be the URL you put in your browser to navigate the local website).



