---
Title: Notes
Weight: 160
---

= Notes

The Notes module in SuiteCRM can be used to keep a record of any
comments, observations or explanations that a User may have relating
internally to their organisation or relating to another SuiteCRM record
such as an Account, Contact, Lead or many more. Notes are also used to
keep record of interactions with Customers regarding Cases and Bugs.

== Notes Actions

You can access the Notes actions from the Notes module menu drop down or
via the Sidebar. The Notes actions are as follows:

* *Create Note or Attachment* – A new form is opened in Edit View to allow
you to create a new Note record (with attachment).
* *View Notes* – Redirects you to the List View for the Notes module. This
allows you to search and list Note records.
* *Import Notes* – Redirects you will be taken to the Import Wizard for
the Notes module. For more information, see
link:http://docs.suitecrm.com/user/user-interface/#_importing_records[Importing Records].

To view the full list of fields available when creating a Note, See
link:http://docs.suitecrm.com/user/appendix-a/#_notes_field_list[Notes Field List].

== Managing Notes

* To sort records on the Notes List View, click any column title which
is sortable. This will sort the column either ascending or descending.
* To search for a Note, see the link:http://docs.suitecrm.com/user/user-interface/#_search[Search] section of this
user guide.
* To update some or all the Notes on the List View, use the Mass Update
panel as described in the link:http://docs.suitecrm.com/user/user-interface/#_mass_updating_records[Mass Updating
Records] section of this user guide.
* To duplicate a Note, you can click the Duplicate button on the Detail
View and then save the duplicate record.
* To delete one or multiple Notes, you can select multiple records from
the List View and click delete. You can also delete a Note from the
Detail View by clicking the Delete button. For a more detailed guide on
deleting records, see the link:http://docs.suitecrm.com/user/user-interface/#_deleting_records[Deleting Records]
section of this user guide.
* To view the details of a Note, click the Note Subject in the List
View. This will open the record in Detail View.
* To edit the Note details, click Edit icon within the List View or
click the edit button on the Detail View, make the necessary changes,
and click Save.
* For a detailed guide on importing and exporting Notes, see the
link:http://docs.suitecrm.com/user/user-interface/#_importing_records[Importing Records] and
link:http://docs.suitecrm.com/user/user-interface/#_exporting_records[Exporting Records] sections of this user guide.
* To track all changes to audited fields, in the Note record, you can
click the View Change Log button on the Note's Detail View or Edit View.