---
title: "8.2 Releases"
weight: 9860
aliases:
  - /8.x/admin/releases/8.2/
---

:toc:
:toc-title:
:toclevels: 1
:icons: font

== 8.2-beta

_Released 30/06/2022_

=== icon:box-open[] Assets

* https://suitecrm.com/suitecrm-pre-release[Downloads]
* https://github.com/salesagility/SuiteCRM-Core/releases/tag/v8.2.0-beta[Github Release]

===  icon:check[] Release Notes

==== icon:warning[] Important Upgrade Notes

This is a pre-release and NOT recommended for Production use.

==== icon:star[] Documentation
* Add 7.12.x to 8.x migration documentation - https://pre-release.docs.suitecrm.com/8.x/admin/installation-guide/legacy-migration[7.12 Migration Documentation]
* Add step to check config and htaccess to install documentation - https://pre-release.docs.suitecrm.com/8.x/admin/installation-guide/downloading-installing[Installation Documentation]
* Update 8.x upgrade guide with new upgrade steps - https://pre-release.docs.suitecrm.com/8.x/admin/installation-guide/upgrading[Upgrade Documentation]

==== icon:star[] Enhancements

* New 7.12 Migration Process - see pre-release https://pre-release.docs.suitecrm.com/8.x/admin/installation-guide/legacy-migration[Migration Documentation]
* Upgrade Improvements - see updated pre-release https://pre-release.docs.suitecrm.com/8.x/admin/installation-guide/upgrading[Upgrade Documentation]
* Login enhancements - Reimplement login to use Symfony json login
  - Legacy login process is no longer used
  - XSRF token has been Reconfigured
  - `before_login`, `after_login`, `login_error` hooks have yet to be ported to SuiteCRM 8 and are disabled for the moment

==== icon:star[] Styling

* Legacy Timezone Modal Changes
* Legacy ActionDropdown Label Suite8 styling updates
* Legacy Import VCard Suite8 Suite8 styling updates
* Legacy Outbound Email Mobile Suite8 styling updates


=== icon:heart[] Community

We would love to have you feedback and input to help make SuiteCRM 8 Great for everyone.


SuiteCRM 8 marks our biggest SuiteCRM upgrade to date and we are very excited to be sharing it with you. In the coming months, we will continue to enhance SuiteCRM 8 with new features and issue fixes. For more information regarding this, please see our link:https://suitecrm.com/suitecrm-roadmap/[Road Map] which will provide further information on what can be expected from future releases.

If you have found an issue you think we should know about, or have a suggestion/feedback, please link:https://github.com/salesagility/SuiteCRM-Core/issues[Submit An Issue]. Before raising an issue please be sure to check the link:https://docs.suitecrm.com/8.x/admin/releases/[Release Notes and list of Known Issues].

If you want to get involved or submit a Fix, fork the repo and when ready please link:https://github.com/salesagility/SuiteCRM-Core/pulls[Submit An PR] - More detail for developers can be found link:https://docs.suitecrm.com/8.x/developer/installation-guide/[here].

Check the following documentation page for more information on how to upgrade between SuiteCRM 8 versions link:https://docs.suitecrm.com/8.x/admin/installation-guide/upgrading/[Upgrading documentation]

To report any security issues please follow our Security Process and send them directly to us via email security@suitecrm.com

More information regarding our Security Process can be found https://docs.suitecrm.com/community/raising-issues/#_security[here].

'''