---
title: SuiteCRM Super Logger
date: 2018-07-23T12:00:00+01:00
author: Jim Mackin
tags: ["development"]
source: http://www.jsmackin.co.uk/suitecrm/suitecrm-super-logger/
hidden: true
---

I’ve previously created a very simple module for SuiteCRM which adds coloured
logging link:./../../../files/suitesuperlogger.zip[(SuiteCRM Super Logger)].
I’ve now expanded it somewhat to add extra features.

It’s now called *SuiteSuperLogger* and allows specifying the log format in the
config. It can be downloaded from the original
http://www.jsmackin.co.uk/suitecrm/suitecrm-super-logger/[blog post]

<!--more-->

Enabling coloured logging can be done by adding

.Example
[source,php]
$sugar_config['suitesuperlogger']['colour'] = true;

To the config.

Altering the log format can be done by adding the following to
`config_override.php`:

.Example
[source,php]
$sugar_config['suitesuperlogger']['format'] = ':date:[:pid:][:userId:][:level:][:remoteAddr:][:forwardedAddr:][:requestMethod:]:msg:';

The following placeholders are accepted and will be replaced with an
appropriate value:

[width="72",cols="12,60", grid="none", frame="none"]
|===
|*date* |The date the message was logged
|*pid* |The process id
|*userId* |The logged in user id
|*level* |The log level
|*remoteAddr* |The remote address as found in the PHP $_SERVER superglobal.
|*forwardedAddr* |The HTTP X FORWARDED FOR header
|*requestMethod* |The request method (i.e. GET, POST, e.t.c.)
|*msg* |The actual log message
|===
