---
Title: "Предисловие"
Weight: 10
---

:author: likhobory
:email: likhobory@mail.ru

:toc:
:toc-title: Оглавление

= Предисловие

Добро пожаловать в SuiteCRM, систему управления взаимоотношениями с клиентами (Customer Relationship Management System, CRM-систему), основанную на открытом исходном коде. 

SuiteCRM - это бесплатный форк популярной CRM-системы link:https://ru.wikipedia.org/wiki/SugarCRM[SugarCRM^]. Автор системы - компания SalesAgility. Первая версия системы за номером 7.0 была выпущена 21 октября 2013 года на базе бесплатной версии SugarCRM Community Edition 6.5.16. В систему были добавлены как серия модулей собственной разработки, так и несколько бесплатных модулей сторонних разработчиков.
Система имеет открытый код и распространяется под лицензией AGPL версии 3.

 
Как и SugarCRM, SuiteCRM построена на архитектуре link:https://ru.wikipedia.org/wiki/LAMP[LAMP/WAMP^], для корректной работы системы требуется версия PHP 5.5 и выше. В качестве СУБД могут выступать MySQL 5.1 и выше, MariaDB 5.1 и выше, MS SQL 2005 и выше. 

Система позволяет эффективно вносить, систематизировать и хранить информацию обо всех аспектах взаимоотношений организации с клиентами, а также обеспечивает интегрированное управление корпоративной информацией о контрагентах, контактах, предварительных контактах (потенциальных покупателях), сделках, а также о мероприятиях (звонках, встречах, задачах). Система сочетает в себе многие функции, необходимые для управления информацией во многих аспектах вашего бизнеса, в интуитивно понятном и удобном веб-интерфейсе.

Система также предлагает панель диаграмм, позволяющую отслеживать стадии продаж и эффективность проводимых сделок. 

SuiteCRM активно поддерживается сообществом, и, следовательно, может быть быстро доработана под потребности конкретной организации путём добавления необходимого функционала. 

== История возникновения SuiteCRM

SugarCRM Inc. с самых первых своих версий и вплоть до 6 версии параллельно выпускала как бесплатную версию системы (Community Edition), так и коммерческие версии (Professional, Enterprise, Ultimate). В коммерческих версиях было большее количество модулей, нежели в Community Edition. Начиная с версии 6.5 компания фактически прекратила развитие бесплатной версии, исправляя лишь найденные ошибки. С 7-й версии компания SugarCRM стала выпускать только коммерческие версии системы. 

Компания SalesAgility активно разрабатывала модули для SugarCRM Community Edition. Особенностью большей части разработанных SalesAgility модулей было то, что они были крайне похожи на модули, которые были в коммерческих версиях SugarCRM, но которых не было в Community Edition. 

В 2013 году SalesAgility выпускает http://www.opennet.ru/opennews/art.shtml?num=38670[первую версию] SuiteCRM, основанную на последней версии Community Edition и дополнительных модулях, по большей части собственной разработки. Эти Модули делают SuiteCRM по функциональности очень близкой к коммерческой версии SugarCRM Professional 6.5.x. SalesAgility позиционирует свою систему как бесплатную альтернативу платной версии SugarCRM Professional. 

В апреле 2014 года компания SugarCRM Inc. http://www.opennet.ru/opennews/art.shtml?num=39640[официально объявляет] о прекращении разработки версии Community Edition. SalesAgility со своим SuiteCRM решает занять вакантное место продолжателя бесплатной версии, объявляя о том, что их система останется всегда бесплатной и с открытым кодом. 

Кроме модулей, унаследованных от SugarCRM Community Edition, в первый выпуск системы был добавлен следующий функционал:

Дополнительные модули SuiteCRM от SalesAgility: ::

*	Advanced OpenTheme (Тема оформления)   
*	Advanced OpenSales (Продажи)  
*	Advanced OpenWorkflow (Процессы)  
*	Advanced OpenReports (Отчёты)  
*	Advanced OpenEvents (События)  
*	Advanced OpenPortal (Интеграция обращений с внешним порталом) 
*	Advanced OpenDiscovery (Полнотекстовый поиск)  
*	Reschedule (Отложенные звонки)



Дополнительные модули SuiteCRM от сторонних разработчиков: ::

*	https://store.suitecrm.com/addons/securitysuite[SecuritySuite] (Группы пользователей)  
*	http://www.jjwdesign.com/google-maps-for-sugarcrm[Google Maps] (Карты Google) 


== О данном руководстве

Руководство знакомит с некоторыми основными CRM-понятиями, а также с системой SuiteCRM. Руководство описывает процесс установки и обновления системы. В нем также подробно рассматриваются процессы управления взаимоотношениями с клиентами, а также вопросы администрирования системы.

От читателей не требуется наличие навыков программирования или разработки программного обеспечения, но в целом они должны быть знакомы с работой на  персональном компьютере и в частности с одним из браузеров: Mozilla Firefox, Microsoft Internet Explorer, Google Chrome или Safari. 

{{% notice note %}}
Пользователям, не знакомым с SuiteCRM, и не планирующим заниматься администрированием системы, в первую очередь рекомендуются к прочтению раздел 
link:../introduction/getting-started/[Начало работы], описывающий основные технические требования, необходимые для работы в системе, и раздел  
link:../introduction/user-interface[Описание пользовательского интерфейса], знакомящий с основными настройками системы. В описании присутствует масса перекрёстных ссылок, позволяющих быстро перейти к подробному описанию рассматриваемого функционала.
{{% /notice %}}


{{% notice info %}}
Все желающие дополнить данную документацию могу сделать это самостоятельно, детали описаны в разделе link:../../../community/contributing-to-docs[Вклад в создание документации^]. Обсудить документацию можно в link:https://suitecrm.com/suitecrm/forum/suitecrm-forum-russian-general-discussion/17907-suitecrm#60470[русскоязычном разделе форума^].
{{% /notice %}}

== Краткий обзор системы

Система состоит из модулей, каждый из которых представляет собой ту или иную функциональную сторону CRM: Контрагенты, Мероприятия (звонки, встречи, задачи), Предварительные контакты, Сделки, модули Продаж, Отчётов и т.д.
 
Модули предназначены для управления взаимоотношениями с клиентами на каждом этапе отношений, начиная с регистрации предварительного контакта (модуль «Предварительные контакты») и заканчивая технической поддержкой клиента и решением возникших вопросов (модули «Обращения» и «Ошибки»). Поскольку многие из этих этапов взаимосвязаны, каждый модуль отображает связанную с другими модулями информацию. Например, при просмотре информации о контрагенте, система также показывает связанные с ним контакты, мероприятия, сделки и ошибки. Вы можете просматривать и редактировать эту информацию, а также создавать новые связанные с данным контрагентом записи.

Как администратор системы, вы можете контролировать доступ пользователей к модулям. При необходимости вы можете редактировать существующие или создавать собственные модули (при помощи встроенной в систему Студии или сторонними средствами разработки). 
 
== Полезные ссылки

* https://suitecrm.com/forum/index[Официальный форум]

* https://github.com/salesagility/SuiteCRM[Исходный код SuiteCRM]

* https://github.com/salesagility/SuiteDocs[Исходный текст данного руководства в формате AsciiDoc]

* https://suitecrm.com/suitecrm/forum/suitecrm-forum-russian-general-discussion/59[Обсуждение русификации]

* https://suitecrm.com/suitecrm/forum/suitecrm-forum-russian-general-discussion/17910-suitecrm[Установка пакетов русификации в SuiteCRM]

* https://suitecrm.com/suitecrm/forum/suitecrm-forum-russian-general-discussion/17971-suitecrm[Обсуждение данного руководства]

* https://suitecrm.com/suitecrm/forum/suitecrm-forum-russian-general-discussion/17907-suitecrm[Руководства пользователя и администратора для предыдущих версий SuiteCRM]

