---
Title: "Introducción"
Weight: 10
---

:imagesdir: ./../../images/es/user

= Introducción

== ¿Qué contiene la Guia del usuario?

La Guía del usuario de SuiteCRM se ha escrito para el usuario final. Esta guía cubre el viaje del usuario de SuiteCRM de extremo a extremo. Exploraremos todas las áreas desde los aspectos básicos del ingreso en el sistema hasta la creación de flujos de trabajo automatizados complejos e informes.

La Guía del usuario de SuiteCRM se divide en varios capítulos. Estos capítulos están ordenados para que progrese a través de la guía como lo haría lógicamente en el día a día el uso de CRM. Los capítulos contienen sub-secciones que rompen barreras para usted, explicando cómo optimizar el uso del sistema de gestión de relaciones con clientes para gestionar eficazmente los datos de ventas.

Los lectores de la Guía del usuario de SuiteCRM no necesitan tener conocimientos de desarrollo o conocimientos previos de SuiteCRM. Se aconseja que esté informado en la informática, que esté familiarizado con el uso del navegador web elegido y que ya se haya instalado y configurado SuiteCRM.