---
Title: Upgrade for pre release-candidate versions
weight: 30
---

== 1. Prepare for upgrade.

Initial steps:

*1.1.* Open the `config/services/system/upgrades.yaml` config file.

*1.2.* Add a `tmp` entry to the `toKeep` section.

It should look like this:

[source,yaml]
----
parameters:
  upgrades:
    toKeep:
      - 'cache'
      - 'extensions'
      - 'public/extensions'
      - 'public/legacy/modules'
      - 'public/legacy/custom'
      - 'public/legacy/cache'
      - 'public/legacy/upload'
      - 'public/legacy/Api/V8/OAuth2/private.key'
      - 'public/legacy/Api/V8/OAuth2/public.key'
      - 'public/legacy/config.php'
      - 'public/legacy/config_override.php'
      - 'public/legacy/config_si.php'
      - 'public/legacy/suitecrm.log'
      - 'public/legacy/install.log'
      - 'logs'
      - '.env.local'
      - '.env.local.php'
      - 'tmp'
    toExpand:

    ...
----

*1.3.* Run:

* For dev mode run:

[source, bash]
----
composer install
----

* For prod mode run:

[source, bash]
----
composer install --no-dev --prefer-dist --optimize-autoloader
----
== 2. Download the RC package

*2.1.* Create the following folder on you current instance:

* `<your-suitecrm-8-root-folder>/tmp/package/upgrade`

*2.2.* Download the SuiteCRM 8 RC pre-built / installable package

*2.3.* Place the package on the `<your-suitecrm-8-root-folder>/tmp/package/upgrade` folder

== 3. Re-set the correct permissions.

== 4. Run the upgrade command

*4.1.* On your SuiteCRM 8 instance root run: `./bin/console suitecrm:app:upgrade -t "<version>"`,
where `<version>` is the name on the SuiteCRM 8 package you've downloaded, i.e. `SuiteCRM-8.0.0-rc`:

[source, bash]
----
./bin/console suitecrm:app:upgrade -t SuiteCRM-8.0.0-rc
----

*4.2.* Re-set the correct permissions.

== 5. Open your instance

If all the above steps went as expected, you should now be able to login into your instance.
