https://github.com/salesagility/SuiteCRM/releases?after=v7.1.8[Source]

[[releases-salesagilitysuitecrm-github]]
Releases · salesagility/SuiteCRM · GitHub
-----------------------------------------

https://github.com#start-of-content[Skip to content]

https://github.com/[]

* https://github.com/features[Features]
* https://github.com/business[Business]
* https://github.com/explore[Explore]
* https://github.com/marketplace[Marketplace]
* https://github.com/pricing[Pricing]

https://github.com/salesagility/SuiteCRM/releases[This repository]

link:/login?return_to=%2Fsalesagility%2FSuiteCRM%2Freleases%3Fafter%3Dv7.1.8[Sign
in] or link:/join?source=header-repo[Sign up]

* link:/login?return_to=%2Fsalesagility%2FSuiteCRM[Watch]
https://github.com/salesagility/SuiteCRM/watchers[164]
* link:/login?return_to=%2Fsalesagility%2FSuiteCRM[Star]
https://github.com/salesagility/SuiteCRM/stargazers[819]
* link:/login?return_to=%2Fsalesagility%2FSuiteCRM[Fork]
https://github.com/salesagility/SuiteCRM/network[686]

[[salesagility15suitecrm16]]
https://github.com/salesagility[salesagility]/https://github.com/salesagility/SuiteCRM[**SuiteCRM]**
----------------------------------------------------------------------------------------------------

https://github.com/salesagility/SuiteCRM[Code]
https://github.com/salesagility/SuiteCRM/issues[Issues 609]
https://github.com/salesagility/SuiteCRM/pulls[Pull requests 285]
https://github.com/salesagility/SuiteCRM/wiki[Wiki]
https://github.com/salesagility/SuiteCRM/pulse[Insights]

https://github.com/salesagility/SuiteCRM/releases[Releases]
https://github.com/salesagility/SuiteCRM/tags[Tags]

Pre-release

* https://github.com/salesagility/SuiteCRM/tree/v7.3-beta[v7.3-beta]
* https://github.com/salesagility/SuiteCRM/commit/2eaa73477206457911b072badf225d74a55ed4fc[`2eaa734`]

[[beta24]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.3-beta[7.3
Beta]
-------------------------------------------------------------------------

image:https://avatars3.githubusercontent.com/u/5641419?s=40&v=4[@willrennie]
https://github.com/willrennie[willrennie] released this Jun 5, 2015 ·
https://github.com/salesagility/SuiteCRM/compare/v7.3-beta...develop[6733
commits] to develop since this release

[[assets]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.3-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3-beta.tar.gz[*Source
code* (tar.gz)]

*This is a beta release and should not be used in a production
environment.*

Try 7.3 Beta to preview the new features coming in 7.3

Including Inline Editing, Desktop Notifications and More.

https://suitecrm.com/index.php?option=com_content&layout=edit&view=article&id=209[Click
here] to get the full details of this release and to get the upgrade
package from 7.2.x

* https://github.com/salesagility/SuiteCRM/tree/v7.2.2[v7.2.2]
* https://github.com/salesagility/SuiteCRM/commit/016d6c6abee5852f91f119c2201e6d05741d4003[`016d6c6`]

[[section]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.2.2[7.2.2]
-------------------------------------------------------------------

image:https://avatars3.githubusercontent.com/u/5641419?s=40&v=4[@willrennie]
https://github.com/willrennie[willrennie] released this May 20, 2015 ·
https://github.com/salesagility/SuiteCRM/compare/v7.2.2...master[6164
commits] to master since this release

[[assets-1]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2.2.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.2 has been updated to version 7.2.2.

This is a bug fix release which addresses bugs in the SuiteCRM 7.2.1
release and also Post-Auth RCE vulnerabilities in SuiteCRM.

* May 20, 2015

[[section-1]]
https://github.com/salesagility/SuiteCRM/releases/tag/7.2.2[7.2.2] …
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

....
    Update SuiteCRM version to 7.2.2.


* [ bf42349 ][38]
* [ zip ][39]
* [ tar.gz ][40]
....

* May 20, 2015

[[section-2]]
https://github.com/salesagility/SuiteCRM/releases/tag/7.1.7[7.1.7] …
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

....
    Fix Post-Auth RCE Vulnerabilit


* [ d004245 ][42]
* [ zip ][43]
* [ tar.gz ][44]
....

* https://github.com/salesagility/SuiteCRM/tree/v7.1.7[v7.1.7]
* https://github.com/salesagility/SuiteCRM/commit/d0042450f5bb73e1db2ec86460609cb5b2e4fa5b[`d004245`]

[[section-3]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.7[7.1.7]
-------------------------------------------------------------------

image:https://avatars3.githubusercontent.com/u/5641419?s=40&v=4[@willrennie]
https://github.com/willrennie[willrennie] released this May 20, 2015

[[assets-2]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.7.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.7.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.1 has been updated to version 7.1.7.

This is a bug fix release which addresses Post-Auth RCE vulnerabilities
in SuiteCRM.

* https://github.com/salesagility/SuiteCRM/tree/v7.2.1[v7.2.1]
* https://github.com/salesagility/SuiteCRM/commit/dda786a6489bfd8c743150033a29fd460f25b980[`dda786a`]

[[section-4]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.2.1[7.2.1]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Mar 11, 2015 ·
https://github.com/salesagility/SuiteCRM/compare/v7.2.1...master[6220
commits] to master since this release

[[assets-3]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2.1.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.2.1 is now Officially Available to Download*

This is a Bug Fix release that addresses that addresses many issues

For more check out the release notes on the wiki
https://suitecrm.com/wiki/index.php/Release_notes_7.2.1[here]

Download here or https://suitecrm.com/download[click here] to find the
appropriate upgrade.

Big Thanks to everyone who contributed, tested and helped with this
release,

* https://github.com/salesagility/SuiteCRM/tree/v7.1.6[v7.1.6]
* https://github.com/salesagility/SuiteCRM/commit/bac37f5776d3d90b65e06853771fd50339fbf98a[`bac37f5`]

[[section-5]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.6[7.1.6]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Mar 11, 2015

[[assets-4]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.6.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.6.tar.gz[*Source
code* (tar.gz)]

SuiteCRM has been updated to version 7.1.6

This is a bug fix release which addresses many issues

For a full list of what has changed and been fixed check out the release
notes on the wiki

* https://github.com/salesagility/SuiteCRM/tree/v7.2[v7.2]
* https://github.com/salesagility/SuiteCRM/commit/2c529f735a72ad6730a692660249175797be7d0b[`2c529f7`]

[[section-6]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.2[7.2]
---------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Mar 2, 2015 ·
https://github.com/salesagility/SuiteCRM/compare/v7.2...master[6252
commits] to master since this release

[[assets-5]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.2 is now Officially Available to Download*

This release bring many enhancements - a brand new responsive theme,
enhanced reporting, an image field and much more

For more check out the release notes on the wiki
https://suitecrm.com/wiki/index.php/Release_notes_7.2.0[here]

Download here or https://suitecrm.com/download[click here] to find the
appropriate upgrade.

Big Thanks to everyone who contributed, tested and helped with this
release,

Pre-release

* https://github.com/salesagility/SuiteCRM/tree/v7.2beta3[v7.2beta3]
* https://github.com/salesagility/SuiteCRM/commit/169047ae360552505b365be928b959b13d8264ae[`169047a`]

[[beta-373]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.2beta3[7.2 Beta
3]
---------------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Feb 9, 2015 ·
https://github.com/salesagility/SuiteCRM/compare/v7.2beta3...develop[7091
commits] to develop since this release

[[assets-6]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2beta3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2beta3.tar.gz[*Source
code* (tar.gz)]

*This is a beta release and should not be used in a production
environment.*

Try 7.2 Beta 3 to preview the new features coming in 7.2

Including reports, cases and project enhancements

https://suitecrm.com/suitecrm?id=207:download&catid=126:suitecrm-beta[Click
here] to get the full details of this release and to get the upgrade
package from 7.1.x (also valid for upgrading from 7.2 beta/beta2)

* https://github.com/salesagility/SuiteCRM/tree/v7.1.5[v7.1.5]
* https://github.com/salesagility/SuiteCRM/commit/08e610e40ea80f71a29600c450930f872feee6e7[`08e610e`]

[[section-7]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.5[7.1.5]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Jan 19, 2015 ·
https://github.com/salesagility/SuiteCRM/compare/v7.1.5...master[6842
commits] to master since this release

[[assets-7]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.5.tar.gz[*Source
code* (tar.gz)]

SuiteCRM has been updated to version 7.1.5

This is a bug fix release which also addresses some important security
issues

For a full list of what has changed and been fixed check out the release
notes on the wiki

https://github.com/salesagility/SuiteCRM/releases?after=v7.4[Previous]https://github.com/salesagility/SuiteCRM/releases?after=v7.1.5[Next]

* © 2018 GitHub, Inc.
* https://github.com/site/terms[Terms]
* https://github.com/site/privacy[Privacy]
* https://github.com/security[Security]
* https://status.github.com/[Status]
* https://help.github.com[Help] https://github.com[]
* https://github.com/contact[Contact GitHub]
* https://developer.github.com[API]
* https://training.github.com[Training]
* https://shop.github.com[Shop]
* https://github.com/blog[Blog]
* https://github.com/about[About]

You can't perform that action at this time.

You signed in with another tab or window. link:[Reload] to refresh your
session. You signed out in another tab or window. link:[Reload] to
refresh your session.
