https://github.com/salesagility/SuiteCRM/releases?after=v7.8.4[Source]

[[releases-salesagilitysuitecrm-github]]
Releases · salesagility/SuiteCRM · GitHub
-----------------------------------------

https://github.com#start-of-content[Skip to content]

https://github.com/[]

* https://github.com/features[Features]
* https://github.com/business[Business]
* https://github.com/explore[Explore]
* https://github.com/marketplace[Marketplace]
* https://github.com/pricing[Pricing]

https://github.com/salesagility/SuiteCRM/releases[This repository]

link:/login?return_to=%2Fsalesagility%2FSuiteCRM%2Freleases%3Fafter%3Dv7.8.4[Sign
in] or link:/join?source=header-repo[Sign up]

* link:/login?return_to=%2Fsalesagility%2FSuiteCRM[Watch]
https://github.com/salesagility/SuiteCRM/watchers[164]
* link:/login?return_to=%2Fsalesagility%2FSuiteCRM[Star]
https://github.com/salesagility/SuiteCRM/stargazers[819]
* link:/login?return_to=%2Fsalesagility%2FSuiteCRM[Fork]
https://github.com/salesagility/SuiteCRM/network[686]

[[salesagility15suitecrm16]]
https://github.com/salesagility[salesagility]/https://github.com/salesagility/SuiteCRM[**SuiteCRM]**
----------------------------------------------------------------------------------------------------

https://github.com/salesagility/SuiteCRM[Code]
https://github.com/salesagility/SuiteCRM/issues[Issues 609]
https://github.com/salesagility/SuiteCRM/pulls[Pull requests 285]
https://github.com/salesagility/SuiteCRM/wiki[Wiki]
https://github.com/salesagility/SuiteCRM/pulse[Insights]

https://github.com/salesagility/SuiteCRM/releases[Releases]
https://github.com/salesagility/SuiteCRM/tags[Tags]

Pre-release

* https://github.com/salesagility/SuiteCRM/tree/v7.9.0-rc[v7.9.0-rc]
* https://github.com/salesagility/SuiteCRM/commit/e239cdb0b0522e48f8e366a9144bc96849bf6032[`e239cdb`]

[[release-candidate24]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.0-rc[7.9.0
Release Candidate]
----------------------------------------------------------------------------------------

image:https://avatars0.githubusercontent.com/u/26431166?s=40&v=4[@Dillon-Brown]
https://github.com/Dillon-Brown[Dillon-Brown] released this May 8, 2017
·
https://github.com/salesagility/SuiteCRM/compare/v7.9.0-rc...develop[2245
commits] to develop since this release

[[assets]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.0-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.0-rc.tar.gz[*Source
code* (tar.gz)]

*This is a Release Candidate release and should not be used in a
production environment.*

Try 7.9.0 Release Candidate to preview the new features coming in
SuiteCRM 7.9.

The focus of SuiteCRM 7.9 is to introduce a new and responsive Email
Client and enhancements for Campaigns Email Template editor.

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package

Pre-release

* https://github.com/salesagility/SuiteCRM/tree/v7.9.0-beta[v7.9.0-beta]
* https://github.com/salesagility/SuiteCRM/commit/e5c3d1ce8d86ac83511e61ee53f7d68bc4e3badf[`e5c3d1c`]

[[beta33]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.0-beta[7.9.0
Beta]
-----------------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this Apr 25, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.9.0-beta...develop[2391
commits] to develop since this release

[[assets-1]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.0-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.0-beta.tar.gz[*Source
code* (tar.gz)]

*This is a Beta release and should not be used in a production
environment.*

Try 7.9.0 Beta to preview the new features coming in SuiteCRM 7.9.

The focus of SuiteCRM 7.9 is to introduce a new and responsive Email
Client and enhancements for Campaigns Email Template editor.

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package

* https://github.com/salesagility/SuiteCRM/tree/v7.8.3[v7.8.3]
* https://github.com/salesagility/SuiteCRM/commit/8b386259cf0e6123f7ba6d27a4aab32d81c19bd0[`8b38625`]

[[section]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.3[7.8.3]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this Apr 11, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.3...master[2023
commits] to master since this release

[[assets-2]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.3.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.8.3 is now Available to Download*

SuiteCRM 7.8.3 is a Bug Fix release

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.3[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

* https://github.com/salesagility/SuiteCRM/tree/v7.8.2[v7.8.2]
* https://github.com/salesagility/SuiteCRM/commit/8a8a300bd7664bd3b7fb2cb6fda0f348a9dcd23e[`8a8a300`]

[[section-1]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.2[7.8.2]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this Feb 27, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.2...master[2123
commits] to master since this release

[[assets-3]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.2.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.8.2 is now Available to Download*

This release addresses an Important Security Issue and addresses many
other Issues

Users of ALL previous releases are advised to Upgrade to 7.8.2 as soon
as possible

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.2[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

* https://github.com/salesagility/SuiteCRM/tree/v7.8.1[v7.8.1]
* https://github.com/salesagility/SuiteCRM/commit/b4218b0759cf3f7d40d820bb62729d17d4e5eb31[`b4218b0`]

[[section-2]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.1[7.8.1]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this Feb 6, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.1...master[2230
commits] to master since this release

[[assets-4]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.1.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.8.1 is now Available to Download*

SuiteCRM 7.8.1 is a Bug Fix release

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.1[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

* https://github.com/salesagility/SuiteCRM/tree/v7.8.0[v7.8.0]
* https://github.com/salesagility/SuiteCRM/commit/673712cc1faf269d470767430bf734e09f126b6a[`673712c`]

[[section-3]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.0[7.8]
-----------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this Jan 30, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.0...master[2263
commits] to master since this release

[[assets-5]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.0.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.0.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.8 is now Available to Download*

*New Filter* functionality which replaces the legacy Basic/Advanced
Search layouts. If you still prefer the old search view on any modules
you can add a setting within the config_overwrite.php file - see Release
Notes. +
*New Workflow Calculated fields* - a new action that allows you to enter
formulas to execute complex actions. Contributed by
http://www.dtbc.eu/[diligent technology & business consulting GmbH] +
*Improved SuiteP theme* - introduced Sass (for developers new steps will
be introduced for when contributing style changes), cleaned up CSS and
tidied up many areas of the system.

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.8[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

Pre-release

* https://github.com/salesagility/SuiteCRM/tree/v7.8.0-rc[v7.8.0-rc]
* https://github.com/salesagility/SuiteCRM/commit/779ee2083a36a4c4efb4fd6c8b04c418c5241f37[`779ee20`]

[[release-candidate72]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.0-rc[7.8
Release Candidate]
--------------------------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Jan 23, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.0-rc...develop[2992
commits] to develop since this release

[[assets-6]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-rc.tar.gz[*Source
code* (tar.gz)]

*This is a Pre release and should not be used in a production
environment.*

Try 7.8.0 RC to preview the new features coming in SuiteCRM 7.8.

The focus of SuiteCRM 7.8 is to enhance and refine the SuiteP theme and
fix many issues

SuiteP Rewritten in SASS, Refined List View filters, added support for
PHP 7.1 and this release includes a great contribution of Workflow
Calculated Fields from diligent technology & business consulting GmbH ()

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package

Pre-release

* https://github.com/salesagility/SuiteCRM/tree/v7.8.0-beta.2[v7.8.0-beta.2]
* https://github.com/salesagility/SuiteCRM/commit/711cda1b5851b113c8885a9d67297bd66305ec39[`711cda1`]

[[beta-280]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.0-beta.2[7.8
Beta 2]
-------------------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Jan 16, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.0-beta.2...develop[3096
commits] to develop since this release

[[assets-7]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-beta.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-beta.2.tar.gz[*Source
code* (tar.gz)]

*This is a Beta release and should not be used in a production
environment.*

Try 7.8.0 Beta 2 to preview the new features coming in SuiteCRM 7.8.

The focus of SuiteCRM 7.8 is to enhance and refine the SuiteP theme and
fix many issues

SuiteP Rewritten in SASS, Refined List View filters and added support
for PHP 7.1

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package

* https://github.com/salesagility/SuiteCRM/tree/v7.7.9[v7.7.9]
* https://github.com/salesagility/SuiteCRM/commit/b64d0fd5df3e11c59387e7e3c0ea7c114a0a2361[`b64d0fd`]

[[section-4]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.9[7.7.9]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Dec 31, 2016 ·
https://github.com/salesagility/SuiteCRM/compare/v7.7.9...master[2920
commits] to master since this release

[[assets-8]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.9.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.9.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.7.9 is now Available to Download*

This release addresses an Important Security Issue and addresses many
other Issues

Users of ALL previous releases are advised to Upgrade to 7.7.9 as soon
as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.7.9[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks to https://github.com/gunnicom[gunnicom] and
https://github.com/sk1p[sk1p] for notifying us of the
https://github.com/salesagility/SuiteCRM/issues/2831[security issue].

Pre-release

* https://github.com/salesagility/SuiteCRM/tree/v7.8.0-beta[v7.8.0-beta]
* https://github.com/salesagility/SuiteCRM/commit/02047a72628ed38e0a768d5fbec949f898351a05[`02047a7`]

[[beta96]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.0-beta[7.8
Beta]
---------------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Dec 30, 2016 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.0-beta...develop[3235
commits] to develop since this release

[[assets-9]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-beta.tar.gz[*Source
code* (tar.gz)]

*This is a Beta release and should not be used in a production
environment.*

Try 7.8.0 Beta to preview the new features coming in SuiteCRM 7.8.

The focus of SuiteCRM 7.8 is to enhance and refine the SuiteP theme and
fix many issues

SuiteP Rewritten in SASS and Refined List View filters

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package

https://github.com/salesagility/SuiteCRM/releases?after=7.9.6[Previous]https://github.com/salesagility/SuiteCRM/releases?after=v7.8.0-beta[Next]

* © 2018 GitHub, Inc.
* https://github.com/site/terms[Terms]
* https://github.com/site/privacy[Privacy]
* https://github.com/security[Security]
* https://status.github.com/[Status]
* https://help.github.com[Help] https://github.com[]
* https://github.com/contact[Contact GitHub]
* https://developer.github.com[API]
* https://training.github.com[Training]
* https://shop.github.com[Shop]
* https://github.com/blog[Blog]
* https://github.com/about[About]

You can't perform that action at this time.

You signed in with another tab or window. link:[Reload] to refresh your
session. You signed out in another tab or window. link:[Reload] to
refresh your session.
