https://github.com/salesagility/SuiteCRM/releases?after=7.9.6[Source]

[[releases-salesagilitysuitecrm-github]]
Releases · salesagility/SuiteCRM · GitHub
-----------------------------------------

https://github.com#start-of-content[Skip to content]

https://github.com/[]

* https://github.com/features[Features]
* https://github.com/business[Business]
* https://github.com/explore[Explore]
* https://github.com/marketplace[Marketplace]
* https://github.com/pricing[Pricing]

https://github.com/salesagility/SuiteCRM/releases[This repository]

link:/login?return_to=%2Fsalesagility%2FSuiteCRM%2Freleases%3Fafter%3D7.9.6[Sign
in] or link:/join?source=header-repo[Sign up]

* link:/login?return_to=%2Fsalesagility%2FSuiteCRM[Watch]
https://github.com/salesagility/SuiteCRM/watchers[164]
* link:/login?return_to=%2Fsalesagility%2FSuiteCRM[Star]
https://github.com/salesagility/SuiteCRM/stargazers[819]
* link:/login?return_to=%2Fsalesagility%2FSuiteCRM[Fork]
https://github.com/salesagility/SuiteCRM/network[686]

[[salesagility15suitecrm16]]
https://github.com/salesagility[salesagility]/https://github.com/salesagility/SuiteCRM[**SuiteCRM]**
----------------------------------------------------------------------------------------------------

https://github.com/salesagility/SuiteCRM[Code]
https://github.com/salesagility/SuiteCRM/issues[Issues 609]
https://github.com/salesagility/SuiteCRM/pulls[Pull requests 285]
https://github.com/salesagility/SuiteCRM/wiki[Wiki]
https://github.com/salesagility/SuiteCRM/pulse[Insights]

https://github.com/salesagility/SuiteCRM/releases[Releases]
https://github.com/salesagility/SuiteCRM/tags[Tags]

* https://github.com/salesagility/SuiteCRM/tree/v7.8.7[v7.8.7]
* https://github.com/salesagility/SuiteCRM/commit/6f540808a0bf9334ca55013c4abe6698c580f81b[`6f54080`]

[[v7.8.724]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.7[v7.8.7]
--------------------------------------------------------------------

image:https://avatars0.githubusercontent.com/u/26431166?s=40&v=4[@Dillon-Brown]
https://github.com/Dillon-Brown[Dillon-Brown] released this Oct 3, 2017
· https://github.com/salesagility/SuiteCRM/compare/v7.8.7...7.8.x[257
commits] to 7.8.x since this release

[[assets]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.7.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.7.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.8.7 LTS is now Available to Download*

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.7[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

* https://github.com/salesagility/SuiteCRM/tree/v7.9.5[v7.9.5]
* https://github.com/salesagility/SuiteCRM/commit/da2f36eb904933f9b5f4d5a7809ee6b26d05b43a[`da2f36e`]

[[section]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.5[7.9.5]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Sep 6, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.9.5...master[633
commits] to master since this release

[[assets-1]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.5.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.9.5 is now Available to Download*

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.5[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

* https://github.com/salesagility/SuiteCRM/tree/v7.8.6[v7.8.6]
* https://github.com/salesagility/SuiteCRM/commit/de18c84462d4e173bee9c14b0cb71dce855354cc[`de18c84`]

[[v7.8.645]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.6[v7.8.6]
--------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/6449723?s=40&v=4[@mattlorimer]
https://github.com/mattlorimer[mattlorimer] released this Sep 6, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.6...7.8.x[356
commits] to 7.8.x since this release

[[assets-2]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.6.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.6.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.8.6 LTS is now Available to Download*

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.6[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

* https://github.com/salesagility/SuiteCRM/tree/v7.9.4[v7.9.4]
* https://github.com/salesagility/SuiteCRM/commit/24ce66ea84a8f7dbf6628c9539109bc17ec4476e[`24ce66e`]

[[section-1]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.4[7.9.4]
-------------------------------------------------------------------

image:https://avatars0.githubusercontent.com/u/26431166?s=40&v=4[@Dillon-Brown]
https://github.com/Dillon-Brown[Dillon-Brown] released this Jul 20, 2017
· https://github.com/salesagility/SuiteCRM/compare/v7.9.4...master[850
commits] to master since this release

[[assets-3]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.4.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.9.4 is now Available to Download*

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.4[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

* https://github.com/salesagility/SuiteCRM/tree/v7.9.3[v7.9.3]
* https://github.com/salesagility/SuiteCRM/commit/3daeb36ed366d83a56609165e50048c2fa46f57a[`3daeb36`]

[[section-2]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.3[7.9.3]
-------------------------------------------------------------------

image:https://avatars0.githubusercontent.com/u/26431166?s=40&v=4[@Dillon-Brown]
https://github.com/Dillon-Brown[Dillon-Brown] released this Jul 17, 2017
· https://github.com/salesagility/SuiteCRM/compare/v7.9.3...master[867
commits] to master since this release

[[assets-4]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.3.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.9.3 is now Available to Download*

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.3[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

Special thanks to [@sergio91pt]https://github.com/sergio91pt[64] for
raising/reviewing security issues.

* https://github.com/salesagility/SuiteCRM/tree/v7.9.2[v7.9.2]
* https://github.com/salesagility/SuiteCRM/commit/084f2f3f1f805cea2603323b1924f998ebffe0e9[`084f2f3`]

[[section-3]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.2[7.9.2]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this Jun 30, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.9.2...master[1109
commits] to master since this release

[[assets-5]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.2.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.9.2 is now Available to Download*

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.2[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

Checkout our
https://suitecrm.com/forum/announcements/14874-suitecrm-7-9-2-maintenance-patch-now-available[SuiteCRM]
forum announcement.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

* https://github.com/salesagility/SuiteCRM/tree/v7.9.1[v7.9.1]
* https://github.com/salesagility/SuiteCRM/commit/032cc000331e1d9a411e468f292e8f9d14d553fd[`032cc00`]

[[section-4]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.1[7.9.1]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this Jun 15, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.9.1...master[1189
commits] to master since this release

[[assets-6]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.1.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.9.1 is now Available to Download*

This release resolves a IMPORTANT Security Vulnerability that effect all
releases of SuiteCRM, all users of ALL previous releases are advised to
Upgrade to 7.9.1 or 7.8.5 as soon as possible.

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.1[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

Special thanks to https://github.com/krzyc[krzyc] for notifying us of
the security issue.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

* https://github.com/salesagility/SuiteCRM/tree/v7.8.5[v7.8.5]
* https://github.com/salesagility/SuiteCRM/commit/1b69962444472196760d139a65c00379f161b3ac[`1b69962`]

[[section-5]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.5[7.8.5]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this Jun 15, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.5...7.8.x[375
commits] to 7.8.x since this release

[[assets-7]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.5.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.8.5 is now Available to Download*

This release addresses an Important Security Issue and addresses many
other Issues

Users of ALL previous releases are advised to Upgrade to 7.8.5 or 7.9.1
as soon as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.8.5[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks to https://github.com/krzyc[krzyc] for notifying us of
the security issue.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com].

* https://github.com/salesagility/SuiteCRM/tree/v7.9.0[v7.9.0]
* https://github.com/salesagility/SuiteCRM/commit/2e1122effe9684c524dcc9e21b77d1eba45b4787[`2e1122e`]

[[section-6]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.0[7.9.0]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this May 29, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.9.0...master[1419
commits] to master since this release

[[assets-8]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.0.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.0.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.9.0 is now Available to Download*

*New Email Client* New designed SuiteP Email client - see Release Notes
for more details +
*New Preferred Email Template Editor* - a new user preference to select
either a TinyMCE, Mozaik, or direct HTML +
*Improved Project Module* - Gantt chart, Project creation and task
allocation improvements +
*Updated View Summary* - Updated styling and new grouped by 'type' +
*Deprecated Suite7 & SuiteR themes* - don't worry, we have announced LTS
for 7.8.x

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.0[Release Notes]
which also includes a 7.9.0 specific User Guide.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

* https://github.com/salesagility/SuiteCRM/tree/v7.8.4[v7.8.4]
* https://github.com/salesagility/SuiteCRM/commit/e7fe1d56b62f650824cbbfca1fcd8da8dda46205[`e7fe1d5`]

[[section-7]]
https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.4[7.8.4]
-------------------------------------------------------------------

image:https://avatars1.githubusercontent.com/u/4041275?s=40&v=4[@samus-aran]
https://github.com/samus-aran[samus-aran] released this May 29, 2017 ·
https://github.com/salesagility/SuiteCRM/compare/v7.8.4...master[1958
commits] to master since this release

[[assets-9]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.4.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.8.4 is now Available to Download*

SuiteCRM 7.8.4 is a Bug Fix release

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.4[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.

Special thanks to https://github.com/haris-raheem[haris-raheem] for
providing further enhancements for the Projects Module.

https://github.com/salesagility/SuiteCRM/releases[Previous]https://github.com/salesagility/SuiteCRM/releases?after=v7.8.4[Next]

* © 2018 GitHub, Inc.
* https://github.com/site/terms[Terms]
* https://github.com/site/privacy[Privacy]
* https://github.com/security[Security]
* https://status.github.com/[Status]
* https://help.github.com[Help] https://github.com[]
* https://github.com/contact[Contact GitHub]
* https://developer.github.com[API]
* https://training.github.com[Training]
* https://shop.github.com[Shop]
* https://github.com/blog[Blog]
* https://github.com/about[About]

You can't perform that action at this time.

You signed in with another tab or window. link:[Reload] to refresh your
session. You signed out in another tab or window. link:[Reload] to
refresh your session.
