---
Title: 7.5.0
weight: 50
---

:experimental:

= 7.5.0

_Released Jan 18, 2016_

== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

SuiteCRM 7.5, the latest cutting edge release, focuses on enhancing the
Reports module. A full list of new functionality is detailed below:

* *Cleaner Reports Interface* - Making the report writer and results view
more user friendly and less cluttered.
* *AND/OR Conditions* - Improving your ability to refine results using a
mixture of OR as well as AND logical operators.
* *New Charting Engine* - Present your report results using eye catching
configurable charts to clearly communicate your intended metrics.
* *Grouped Reports View* - Grouped Reports view, including dashlets, which
can be expanded/collapsed and grouped on multiple fields.
* *Custom file removal* - Removing a large volume of files from the custom
directory ensuring only required custom files remain.
* *Formatting Options* - Display dates and other key fields in a format
effective for your audience.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.5[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.