---
Title: Обновление системы
weight: 30
---

:author: likhobory
:email: likhobory@mail.ru


:toc:
:toc-title: Оглавление
:toclevels: 3

:experimental:

:imagesdir: ./../../../images/ru/admin/Upgrading

ifdef::env-github[:imagesdir: ./../../../../master/static/images/ru/admin/Upgrading]

:btn: btn:

ifdef::env-github[:btn:]

= Обновление системы

В данном разделе описывается процесс обновления системы при помощи мастера обновления. 

Прежде всего, необходимо скачать необходимый https://suitecrm.com/upgrade-suitecrm[пакет обновления].
 
{{% notice warning %}}
Перед выполнение обновления настоятельно рекомендуется сделать резервную копию системы!
{{% /notice %}}

== Таблица совместимости 

Таблицы совместимости для всех версий системы рассматриваются на 
link:/admin/compatibility-matrix.ru[этой] странице.

Поддерживаемые платформы, веб-серверы, базы данных и браузеры представлены ниже:

[discrete]
==== Платформа 

* Linux - любая версия с поддержкой PHP 
* Unix - любая версия с поддержкой PHP 
* Mac OS - любая версия с поддержкой PHP 	
* Windows - любая версия с поддержкой PHP 

[discrete]
==== Веб-сервер 

* Apache 	2.2, 2.4
* IIS 	8, 8.5 

[discrete]
==== База данных

* MariaDB 	
* MySQL 	
* SQL Server 	

[discrete]
==== Браузеры*

* Chrome 	
* Firefox 	
* IE 	11 (режим совместимости не поддерживается) 
* Edge	
* Safari 
	
''''
[discrete]
====== *Представлен перечень протестированных браузеров, в других браузерах система, вероятно, также  будет работоспособна.

== Обновление системы с SugarCRM CE до SuiteCRM

Обновление возможно для всех версий SugarCRM Community Edition ветки 6.х.

Если установлена более ранняя версия SugarCRM CE, то вначале её необходимо обновить до версии 6.х при помощи этих пакетов обновления, после чего можно приступать к обновлению до SuiteCRM.
Обновление с SugarCRM 7.х и более поздних версий не предусмотрено.

== Подготовка к обновлению

*	Перед запуском обновления создайте резервные копии как файлов системы, так и файлов базы данных. 
*	Если в php.ini настроен и включён какой-либо PHP-ускоритель, то на время обновления его необходимо отключить. 
*	Если используется Zend Core 2.0, то перед запуском обновления необходимо увеличить следующие стандартные параметры: 
 .	В файле …\Zend\Core\etc\fastcgi.conf увеличьте значение параметра ConnectionTimeout до 3000 секунд и параметра RequestTimeout до 6000 секунд.
 .	В файле php.ini увеличьте значение параметра max_execution_time до 6000 секунд.
*	Поскольку файл обновления достаточно большой по объёму, необходимо выполнить следующее:

 .	В разделе *_Настройки конфигурации_* панели администрирования системы увеличьте значение параметра *_Максимальный размер загружаемого файла_* до 21000000 байт (20 мегабайт). 
 .	В файле php.ini  увеличьте значения следующих параметров: 
**	post_max_size – не менее 60MB.
**	upload_max_filesize settings – не менее 60MB.
**	max_input_time – не менее 60.
**	memory_limit - 256MB
*	Если в качестве веб-сервера используется Apache Web и в файле httpd.conf используется параметр LimitRequestBod,то его значение должно быть не менее   2GB. 
После выполненных настроек необходимо перезапустить веб-сервер. Затем можно перейти к обновлению системы.
*	Убедитесь, что в процессе обновления пользователь веб-сервера имеет права на запись как в базе данных системы, так и в папке (включая все подпапки) с файлами обновляемой системы.
*	Обновление системы может выполняться до 30 минут. Если используется веб-сервер IIS, убедитесь, что допустимое время выполнения CGI-скрипта установлено более чем в 300 секунд.  
*	Если код какого-либо модуля был изменён, перед обновлением настоятельно рекомендуется не оставлять файлы модуля в стандартных папках, а скопировать их в папку Custom, поскольку в процессе обновления изменённые файлы могут быть перезаписаны новыми версиями аналогичных файлов. 
