---
Title: Настройка групп пользователей для входящих E-mail
weight: 50
---

:author: likhobory
:email: likhobory@mail.ru

:toc:
:toc-title: Оглавление

//
:sectnums:
:sectnumlevels: 2
//

== Введение

В этом разделе описывается доступность различных записей, которую можно менять, используя 
link:../../../../user/security-suite-groups/[Группы пользователей].


==  Доступность персональных записей

Для следующих модулей возможно создание персональных записей:

* Входящие E-mail
* Внешние подключения OAuth
* Внешние провайдеры OAuth

Персональные записи доступны только их владельцам и администраторам системы.


== Доступность групповых записей

=== Входящие E-mail и Внешние подключения OAuth

Также как и персональные записи, все групповые записи доступны администраторам системы.

Обычные пользователи по умолчанию не имеют доступа к групповым записям. Групповые записи будут им доступны только если:

* Обычному пользователю назначена 
link:../../users/#_роли[роль] с настроенными правами доступа для  модулей *Входящие E-mail* и *Внешние подключения OAuth*
* Обычный пользователь и групповая запись принадлежат общей 
link:../../users/#_группы[Группе]

Это поведение отличается от стандартного поведения SuiteCRM: по умолчанию записи доступны всем, и администратору необходимо настраивать группы пользователей, чтобы ограничить доступ к записям.

Для модулей *Входящие E-mail* и *Внешнее подключение OAuth* работает прямо противоположное правило: их записи по умолчанию скрыты.

=== Внешние провайдеры OAuth

В отличие от *Входящих E-mail* и *Внешних подключений OAuth*, групповые записи для *Внешних провайдеров OAuth* доступны по умолчанию, и при необходимости ограничения доступа необходима настройка групп пользователей и ролей.


*Внешний провайдер OAuth* доступен всем, поскольку настройки группового провайдера предназначены для использования всеми пользователями, имеющими учётную запись в этом домене.

Например, при настройке поставщика Microsoft для *_@exampleinc.onmicrosoft.com_* любой пользователь, имеющий учётную запись в этом домене, может использовать этого провайдера.

Для *Входящих E-mail* и *Внешних подключений OAuth* общего доступа не требуется. Это настройки для конкретной учётной записи электронной почты, например, для *_sales@exampleinc.onmicrosoft.com_*. В этом случае мы просто предоставляем доступ к письмам этой учётной записи тем пользователям, которые должны иметь к ней доступ.


==  Настройка доступности субпанели "Группы пользователей"

Как уже упоминалось <<Входящие E-mail и Внешние подключения OAuth,выше>>, обычные пользователи по умолчанию не имеют доступа к групповым записям модулей *Входящие E-mail* и *Внешнее подключение OAuth*.

Однако, если настройки доступа были изменены, и эти групповые записи стали доступны обычным пользователям системы, то по умолчанию субпанель *Группы пользователей* также становится доступна обычным пользователям. Таким образом, эти пользователи имеет возможность изменить правила доступа к конкретной записи вышеуказанных модулей, что может быть не всегда оправдано с точки зрения безопасности.

Чтобы этого избежать, ограничьте доступ к *Группам пользователей* таким образом, чтобы они отображалась только для администраторов системы. 


