---
Title: 7.6 Release Candidate
weight: 50
---

:experimental:

_Released Apr 20, 2016_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.6-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6-rc.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

*This is a Release Candidate and should not be used in a production environment.*

The focus of SuiteCRM 7.6 is to enhance the functionality of the native
Campaign module.

The Release Candidate includes the latest enhancements to the following:

* *Campaign Wizard* - A simplified Campaign Wizard that is easily
understood. Includes an enhanced UI and progress bar.
* *Email Templates* - The ability to add Tracker Links to Email Templates
while creating the template so that they do not need to be created
beforehand.
* *Web To Lead Form* - Web-To-Lead Forms are now HTML 5 compliant for
easier integration with modern Websites.
* *Target List* - Create Target Lists of Contacts based on associated
Accounts. This allows for contact lists to be segmented by Account
properties without the need to use a report.