---
Title: Releases
---

= SuiteCRM Releases

https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.9[7.9.9]
-------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Jan 11, 2018

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.9.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.9.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.9[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.10[7.8.10]
---------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Jan 11, 2018

[[assets-1]]
Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.10.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.10.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.10[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

https://github.com/salesagility/SuiteCRM/releases/tag/v7.10-beta-3[7.10 Beta 3]
-------------------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Dec 18, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.10-beta-3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.10-beta-3.tar.gz[*Source
code* (tar.gz)]

Try 7.10 Beta 3 to preview the new features coming in SuiteCRM 7.10

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade packages

Changes since Beta 2:

* 4 SuiteP colour schemes (Day, Dawn, Dusk, Night)
* Email Performance Improvements
* Bug Fixing
* API swagger documentation added

https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.8[7.9.8]
-------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Dec 14, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.8.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.8.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.8[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.9[7.8.9]
-------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Dec 14, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.9.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.9.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.9[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]


https://github.com/salesagility/SuiteCRM/releases/tag/v7.10-beta-2[7.10 Beta 2]
-------------------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Dec 1, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.10-beta-2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.10-beta-2.tar.gz[*Source
code* (tar.gz)]

Try 7.10 Beta 2 to preview the new features coming in SuiteCRM 7.10

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package


https://github.com/salesagility/SuiteCRM/releases/tag/v7.10-beta[7.10 Beta]
---------------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Nov 17, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.10-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.10-beta.tar.gz[*Source
code* (tar.gz)]

Try 7.10 Beta to preview the new features coming in SuiteCRM 7.10

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package


https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.7[7.9.7]
-------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Oct 18, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.7.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.7.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.7[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.8[7.8.8]
-------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Oct 18, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.8.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.8.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.8[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]


https://github.com/salesagility/SuiteCRM/releases/tag/7.9.6[7.9.6]
------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Oct 3, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/7.9.6.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/7.9.6.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.6[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.7[v7.8.7]
--------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Oct 3, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.7.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.7.tar.gz[*Source
code* (tar.gz)]

*SuiteCRM 7.8.7 LTS is now Available to Download*

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.7[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.5[7.9.5]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Sep 6, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.5.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.5[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.6[v7.8.6]
--------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Sep 6, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.6.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.6.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.6[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.4[7.9.4]
-------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Jul 20, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.4.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.4[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.3[7.9.3]
-------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this Jul 17, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.3.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.3[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

We have also added a Code of Conduct to help build a more welcoming
environment for our community. +
https://github.com/salesagility/SuiteCRM/blob/master/CODE_OF_CONDUCT.md[SuiteCRM
Code of Conduct]

Special thanks to https://github.com/sergio91pt[sergio91pt] for
raising/reviewing security issues.

https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.2[7.9.2]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jun 30, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.2.tar.gz[*Source
code* (tar.gz)]

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.2[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Checkout our
https://suitecrm.com/forum/announcements/14874-suitecrm-7-9-2-maintenance-patch-now-available[SuiteCRM]
forum announcement.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]

https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.1[7.9.1]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jun 15, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.1.tar.gz[*Source
code* (tar.gz)]

This release resolves a IMPORTANT Security Vulnerability that effect all
releases of SuiteCRM, all users of ALL previous releases are advised to
Upgrade to 7.9.1 or 7.8.5 as soon as possible.

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.1[Release Notes].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks to https://github.com/krzyc[krzyc] for notifying us of
the security issue.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com]


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.5[7.8.5]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jun 15, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.5.tar.gz[*Source
code* (tar.gz)]

This release addresses an Important Security Issue and addresses many
other Issues

Users of ALL previous releases are advised to Upgrade to 7.8.5 or 7.9.1
as soon as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.8.5[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

We have also updated our Security Process asking the community to send
their security issues directly to us via email
mailto:security%40suitecrm.com[security@suitecrm.com].


https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.0[7.9.0]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this May 29, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.0.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.0.tar.gz[*Source
code* (tar.gz)]

* *New Email Client* New designed SuiteP Email client - see Release Notes
for more details +
* *New Preferred Email Template Editor* - a new user preference to select
either a TinyMCE, Mozaik, or direct HTML +
* *Improved Project Module* - Gantt chart, Project creation and task
allocation improvements +
* *Updated View Summary* - Updated styling and new grouped by 'type' +
* *Deprecated Suite7 & SuiteR themes* - don't worry, we have announced LTS
for 7.8.x

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php/Release_notes_7.9.0[Release Notes]
which also includes a 7.9.0 specific User Guide.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.4[7.8.4]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this May 29, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.4.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.8.4 is a Bug Fix release

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.4[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks to https://github.com/haris-raheem[haris-raheem] for
providing further enhancements for the Projects Module.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.0-rc[7.9.0 Release Candidate]
----------------------------------------------------------------------------------------

https://github.com/Dillon-Brown[Dillon-Brown] released this May 8, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.0-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.0-rc.tar.gz[*Source
code* (tar.gz)]

Try 7.9.0 Release Candidate to preview the new features coming in
SuiteCRM 7.9.

The focus of SuiteCRM 7.9 is to introduce a new and responsive Email
Client and enhancements for Campaigns Email Template editor.

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package


https://github.com/salesagility/SuiteCRM/releases/tag/v7.9.0-beta[7.9.0 Beta]
-----------------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Apr 25, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.9.0-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.9.0-beta.tar.gz[*Source
code* (tar.gz)]

Try 7.9.0 Beta to preview the new features coming in SuiteCRM 7.9.

The focus of SuiteCRM 7.9 is to introduce a new and responsive Email
Client and enhancements for Campaigns Email Template editor.

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.3[7.8.3]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Apr 11, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.3.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.8.3 is a Bug Fix release

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.3[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.2[7.8.2]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Feb 27, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.2.tar.gz[*Source
code* (tar.gz)]

This release addresses an Important Security Issue and addresses many
other Issues

Users of ALL previous releases are advised to Upgrade to 7.8.2 as soon
as possible

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.2[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.1[7.8.1]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Feb 6, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.1.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.8.1 is a Bug Fix release

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.8.1[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.0[7.8.0]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jan 30, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.0.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.0.tar.gz[*Source
code* (tar.gz)]

* *New Filter* - a functionality which replaces the legacy Basic/Advanced
Search layouts. If you still prefer the old search view on any modules
you can add a setting within the config_overwrite.php file - see Release
Notes. +
* *New Workflow Calculated fields* - a new action that allows you to enter
formulas to execute complex actions. Contributed by
http://www.dtbc.eu/[diligent technology & business consulting GmbH]
* *Improved SuiteP theme* - introduced Sass (for developers new steps will
be introduced for when contributing style changes), cleaned up CSS and
tidied up many areas of the system.

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.8[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.0-rc[7.8 Release Candidate]
--------------------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Jan 23, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-rc.tar.gz[*Source
code* (tar.gz)]

Try 7.8.0 RC to preview the new features coming in SuiteCRM 7.8.

The focus of SuiteCRM 7.8 is to enhance and refine the SuiteP theme and
fix many issues

SuiteP Rewritten in SASS, Refined List View filters, added support for
PHP 7.1 and this release includes a great contribution of Workflow
Calculated Fields from diligent technology & business consulting GmbH ()

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.0-beta.2[7.8 Beta 2]
-------------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Jan 16, 2017

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-beta.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-beta.2.tar.gz[*Source
code* (tar.gz)]

Try 7.8.0 Beta 2 to preview the new features coming in SuiteCRM 7.8.

The focus of SuiteCRM 7.8 is to enhance and refine the SuiteP theme and
fix many issues

SuiteP Rewritten in SASS, Refined List View filters and added support
for PHP 7.1

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.9[7.7.9]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Dec 31, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.9.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.9.tar.gz[*Source
code* (tar.gz)]

This release addresses an Important Security Issue and addresses many
other Issues

Users of ALL previous releases are advised to Upgrade to 7.7.9 as soon
as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.7.9[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks to https://github.com/gunnicom[gunnicom] and
https://github.com/sk1p[sk1p] for notifying us of the
https://github.com/salesagility/SuiteCRM/issues/2831[security issue].


https://github.com/salesagility/SuiteCRM/releases/tag/v7.8.0-beta[7.8 Beta]
---------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Dec 30, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.8.0-beta.tar.gz[*Source
code* (tar.gz)]

Try 7.8.0 Beta to preview the new features coming in SuiteCRM 7.8.

The focus of SuiteCRM 7.8 is to enhance and refine the SuiteP theme and
fix many issues

SuiteP Rewritten in SASS and Refined List View filters

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.8[7.7.8]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Nov 16, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.8.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.8.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.7.8 is a Bug Fix release

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.7.8[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.10[7.6.10]
---------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Nov 16, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.10.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.10.tar.gz[*Source
code* (tar.gz)]

This release addresses the bug for search using MultiSelect fields

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.6.10[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.7[7.7.7]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Nov 7, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.7.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.7.tar.gz[*Source
code* (tar.gz)]

This release addresses Important Security Issues and addresses many
other Issues

Users of ALL previous releases are advised to Upgrade to 7.7.7 as soon
as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.7.7[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks for http://karmainsecurity.com[Egidio Romano] for
notifying us of these security issues.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.9[7.6.9]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Nov 7, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.9.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.9.tar.gz[*Source
code* (tar.gz)]

This release addresses Important Security Issues and other core
functionality

Users of ALL previous releases are advised to Upgrade to 7.6.9 as soon
as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.6.9[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks for http://karmainsecurity.com[Egidio Romano] for
notifying us of these security issues.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.6[7.7.6]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Oct 19, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.6.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.6.tar.gz[*Source
code* (tar.gz)]

This release addresses Important Security Issues and addresses many
other Issues

Users of ALL previous releases are advised to Upgrade to 7.7.6 as soon
as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.7.6[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks for http://karmainsecurity.com[Egidio Romano] for
notifying us of these security issues.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.8[7.6.8]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Oct 19, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.8.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.8.tar.gz[*Source
code* (tar.gz)]

This release addresses Important Security Issues and addresses Report
Issues

Users of ALL previous releases are advised to Upgrade to 7.6.8 as soon
as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.6.8[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks for http://karmainsecurity.com[Egidio Romano] for
notifying us of these security issues.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.5[7.7.5]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Sep 28, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.5.tar.gz[*Source
code* (tar.gz)]

* Updates a Security vulnerability with Serialized Input, to prevent
possible object,file, beans and SQL injection attacks
* Bug fixes and UI styling for a variety of areas include, Reports,
Calendar, Responsiveness and more.

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.7.5[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks for http://karmainsecurity.com[Egidio Romano] for
notifying us of this security update.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.7[7.6.7]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Sep 28, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.7.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.7.tar.gz[*Source
code* (tar.gz)]

*Includes SugarCRM 6.5.24* -
http://support.sugarcrm.com/Documentation/Sugar_Versions/6.5/CE/Sugar_Release_Notes_6.5.24/[more
information here] +
Updates a Security vulnerability with Serialized Input, to prevent
possible object,file, beans and SQL injection attacks

Users of ALL previous releases are advised to Upgrade to 7.6.7 as soon
as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.6.7[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks for http://karmainsecurity.com[Egidio Romano] and
https://github.com/salesagility/SuiteCRM/issues/1843[adminibt] for
notifying us of this security update.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.4[7.7.4]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Aug 31, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.4.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.7.4 includes bug fixes for dropdown editor (browser
specific), dashlets, calendar, studio layout updates and improve styling
on top bar for non module filter settings.

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.7.4[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.3[7.7.3]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Aug 26, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.3.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.7.3 includes a fix due to a regression issue with basic
search, this release also includes PHP 5.3 for Spots modules, fix the
ability to drag Dashlets to multi column Dashboards and have collapsible
subpanels system setting.

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.7.3[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.2[7.7.2]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Aug 23, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.2.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.7.2 features bug fixes for calendar, php7, MSSQL upgrades and
improves Theme SuiteP UI and functionality

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.7.2[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7.1[7.7.1]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Aug 11, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.1.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.7.1 features bug fixes, improves Theme SuiteP UI and
functionality

Please see the
https://suitecrm.com/wiki/index.php/Release_notes_7.7.1[Release Notes]
on list of Bug fixes noted on Github and
https://suitecrm.com/forum/index[SuiteCRM Forums].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7[7.7.0]
-----------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Aug 2, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.tar.gz[*Source
code* (tar.gz)] +

=== What's new?
* *SuiteP Theme* - We want SuiteCRM 7.7 to be something special this
Summer. Packed with new and improved features and an amazing new UI, it
will transform the way you view SuiteCRM.
* *Analytic Reporting Tool - "SuiteSpots"* - Using Drag and Drop
functionality you can create in depth Pivot Tables and charts using your
customer data.
* *Module Group Selection upon Installation Configurations* - When
installing you can choose which groups of modules you wish to include as
default. This will give users the choice of how what they feel they need
from the word go.
* *Updated* Silent Installer
* *New Calendar* library
* *New Search filter* for Event Delegates subpanel
* *Improved* Project and Project Templates functionality

=== Security
Includes *SugarCRM 6.5.24* - more information here - ()

Special thanks for
https://github.com/salesagility/SuiteCRM/issues/1843[adminibt] for
notifying us of this security update.

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.7[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7-rc2[7.7 Release Candidate 2]
---------------------------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jul 26, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7-rc2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7-rc2.tar.gz[*Source
code* (tar.gz)]

Try 7.7 Release Candidate 2 to preview the new features coming in
SuiteCRM 7.7.

The focus of SuiteCRM 7.7 Release Candidate 2 is to introduce our new
theme SuiteP (SuitePea).

* Further adding to the SuiteP theme
* Improvements in Project Templates and Projects functionality
* Introducing Business Hours Module
* Search Filter by Events Delegates
* Bug fixes for Email Assignment notifications, Pipeline By Sales Stage
Dashlet, and more

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package from
7.5.x, 7.6.x, 7.7beta1, 7.7beta2 and 7.7.RC

https://github.com/salesagility/SuiteCRM/releases/tag/v7.7-rc[7.7 Release Candidate]
------------------------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jul 18, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7-rc.tar.gz[*Source
code* (tar.gz)]

Try 7.7 Release Candidate to preview the new features coming in SuiteCRM
7.7.

The focus of SuiteCRM 7.7 Release Candidate is to introduce our new
theme SuiteP (SuitePea).

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package from
7.5.x, 7.6.x, 7.7beta1 and 7.7beta2


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.6[7.6.6]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jul 18, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.6.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.6.tar.gz[*Source
code* (tar.gz)]

This release resolves Multiple XSS Vulnerabilities in Yahoo YUI
component & YUI IO Utility

** Removes the use of uploader.swf file (and references) within
self-hosted YUI library that can be vulnerable to XSS attacks

Users of ALL previous releases are advised to Upgrade to 7.5.5 or 7.6.6
as soon as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.6.6[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks to
https://github.com/salesagility/SuiteCRM/issues/1724[chadbennett] for
alerting and helping us resolve this vulnerability.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.5.5[7.5.5]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jul 20, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.5.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5.5.tar.gz[*Source
code* (tar.gz)]

This release resolves Multiple XSS Vulnerabilities in Yahoo YUI
component & YUI IO Utility

** Removes the use of uploader.swf file (and references) within
self-hosted YUI library that can be vulnerable to XSS attacks

Users of ALL previous releases are advised to Upgrade to 7.5.5 or 7.6.6
as soon as possible

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks to
https://github.com/salesagility/SuiteCRM/issues/1724[chadbennett] for
alerting and helping us resolve this vulnerability.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.5[7.6.5]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jul 4, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.5.tar.gz[*Source
code* (tar.gz)]

This release resolves a Security vulnerability with Serialized Input, to
prevent possible object injection attacks

Users of ALL previous releases are advised to Upgrade to 7.5.4 or 7.6.5
as soon as possible

For more detail and to see all issues addressed in this release view the
https://suitecrm.com/wiki/index.php?title=Release_notes_7.6.5[Release
Notes]

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Special thanks to http://karmainsecurity.com[Egidio Romano] for alerting
and helping us resolve this vulnerability.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.5.4[7.5.4]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Jul 4, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.5.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5.4.tar.gz[*Source
code* (tar.gz)]

This release resolves a Security vulnerability with Serialized Input, to
prevent possible object injection attacks

* Removes the option to allow serialized user input to the SuiteCRM Rest
Client.
* Changed serialized User input to use JSON

Users of ALL previous releases are advised to Upgrade to 7.5.4 or 7.6.5
as soon as possible

Download here from the SuiteCRM GitHub Repository or visit the official
website to find the appropriate upgrade.

Special thanks to http://karmainsecurity.com[Egidio Romano] for alerting
and helping us resolve this vulnerability.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.7-beta2[7.7 Beta 2]
---------------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jun 27, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7-beta2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7-beta2.tar.gz[*Source
code* (tar.gz)]

Try 7.7 Beta 2 to preview the new features coming in SuiteCRM 7.7.

The focus of SuiteCRM 7.7 beta 2 is to introduce our new theme SuiteP
(SuitePea).

Fixes for Campaigns, Sending Emails and other bugs.

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package from
7.4.x, 7.5.x, 7.6.x and 7.7beta1

https://github.com/salesagility/SuiteCRM/releases/tag/v7.7-beta1[7.7 Beta]
--------------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Jun 15, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.7-beta1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7-beta1.tar.gz[*Source
code* (tar.gz)]

Try 7.7 Beta 1 to preview the new features coming in SuiteCRM 7.7.

The focus of SuiteCRM 7.7 is to introduce our new Analytical Reporting
Tool - SuiteSpots, and provide more options upon installing SuiteCRM.

The first Beta release includes enhancements to the following:

* *New Analytic Reporting Tool* - *SuiteSpots* - Using Drag and Drop
functionality you can create in depth Pivot Tables and charts using your
customer data.

* *New Module Group Selection upon installation Configurations* - When
installing you can choose which groups of modules you wish to include as
default. This will give users the choice of what modules they need from
the word go.
* Fixes for Campaigns, Calls/Meetings Reminders and other bugs

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package from
7.4.x, 7.5.x, and 7.6.x


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.4[7.6.4]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this May 30, 2016 

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.4.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.6.4 features bug fixes, improves Campaign Wizard UI and
improves Reporting functionality on MSSQL servers

* Add the budget fields into Campaign Header screen
* Test emails send out immediately (rather than queued)
* Improved UI for creating Email Marketing Records and Templates via the
Wizard
* Update the Campaign Wizard Summary's interface

And more below:

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

Thank you to all community members who logged bugs and contributed to
this release.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.3[7.6.3]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this May 17, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.3.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release for SuiteCRM 7.6.x and includes updated
Campaign Wizard UI, resolving issues with running scheduled email
campaigns and upgrading using MSSQL.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.2[7.6.2]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this May 10, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.2.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release for SuiteCRM 7.6.2 and includes updated
Campaign Wizard UI.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

View
https://suitecrm.com/wiki/index.php/Release_notes_7.6.2#SuiteCRM_7.6.2[release
notes]


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6.1[7.6.1]
-------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this May 2, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.1.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release for SuiteCRM 7.6 to resolve legacy
customisations https://github.com/salesagility/SuiteCRM/issues/1300[code
issue] when upgrading to 7.6.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

View
https://suitecrm.com/wiki/index.php/Release_notes_7.6.1#SuiteCRM_7.6.1[release
notes]


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6[7.6]
---------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Apr 27, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6.tar.gz[*Source
code* (tar.gz)]


SuiteCRM 7.6, the latest cutting edge release, focuses on enhancing the
functionality of the native Campaign module as well as including the
latest bug fixes.

The release includes the latest enhancements to the following:

* *Campaign Wizard* - A simplified Campaign Wizard that is easily
understood. Includes an enhanced UI and progress bar.
* *Email Templates* - The ability to add Tracker Links to Email Templates
while creating the template so that they do not need to be created
beforehand.
* *Web To Lead Form* - Web-To-Lead Forms are now HTML 5 compliant for
easier integration with modern Websites.
* *Target List* - Create Target Lists of Contacts based on associated
Accounts. This allows for contact lists to be segmented by Account
properties without the need to use a report.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6-rc[7.6 Release Candidate]
------------------------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Apr 20, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6-rc.tar.gz[*Source
code* (tar.gz)]

Try 7.6 Release Candidate to preview the new features coming in SuiteCRM
7.6.

The focus of SuiteCRM 7.6 is to enhance the functionality of the native
Campaign module.

The Release Candidate includes the latest enhancements to the following:

* *Campaign Wizard* - A simplified Campaign Wizard that is easily
understood. Includes an enhanced UI and progress bar.
* *Email Templates* - The ability to add Tracker Links to Email Templates
while creating the template so that they do not need to be created
beforehand.
* *Web To Lead Form* - Web-To-Lead Forms are now HTML 5 compliant for
easier integration with modern Websites.
* *Target List* - Create Target Lists of Contacts based on associated
Accounts. This allows for contact lists to be segmented by Account
properties without the need to use a report.

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade packs


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6-beta.2[7.6 Beta 2]
-----------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Apr 13, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6-beta.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6-beta.2.tar.gz[*Source
code* (tar.gz)]

Try 7.6 Beta 2 to preview the new features coming in SuiteCRM 7.6.

The focus of SuiteCRM 7.6 is to enhance the functionality of the native
Campaign module.

This Beta release includes the latest enhancements to the following:

* *Campaign Wizard* - A simplified Campaign Wizard that is easily
understood. Includes an enhanced UI and progress bar.

* *Email Templates* - The ability to add Tracker Links to Email Templates
while creating the template so that they do not need to be created
beforehand.

* *Web To Lead Form* - Web-To-Lead Forms are now HTML 5 compliant for
easier integration with modern Websites.

* *Target List* - Create Target Lists of Contacts based on associated
Accounts. This allows for contact lists to be segmented by Account
properties without the need to use a report.

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade packs


https://github.com/salesagility/SuiteCRM/releases/tag/v7.6-beta-1[7.6 Beta]
---------------------------------------------------------------------------

https://github.com/samus-aran[samus-aran] released this Mar 30, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.6-beta-1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.6-beta-1.tar.gz[*Source
code* (tar.gz)]

Try 7.6 Beta 1 to preview the new features coming in SuiteCRM 7.6.

The focus of SuiteCRM 7.6 is to enhance the functionality of the native
Campaign module.

The first Beta release includes enhancements to the following:

* *Campaign Wizard* - A simplified Campaign Wizard that is easily
understood. Includes an enhanced UI and progress bar.

* *Email Templates* - The ability to add Tracker Links to Email Templates
while creating the template so that they do not need to be created
beforehand.

* *Web To Lead Form* - Web-To-Lead Forms are now HTML 5 compliant for
easier integration with modern Websites.

* *Target List* - Create Target Lists of Contacts based on associated
Accounts. This allows for contact lists to be segmented by Account
properties without the need to use a report.

https://suitecrm.com/download/download-pre-release[Click here] to get
the full details of this release and to get the upgrade package from
7.4.x and 7.5.x


https://github.com/salesagility/SuiteCRM/releases/tag/v7.5.3[7.5.3]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Mar 15, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.5.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5.3.tar.gz[*Source
code* (tar.gz)]

This release resolves Security Issues and other various issues

Its is recommended to update to 7.5.3 as soon as possible

For more information view the release notes on the SuiteCRM Wiki
https://suitecrm.com/wiki/index.php/Release_notes_7.5.3[here].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.5.2[7.5.2]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Mar 7, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.5.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5.2.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release for SuiteCRM 7.5 release.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.5.1[7.5.1]
-------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Jan 26, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.5.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5.1.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release for SuiteCRM 7.5 release.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.5[7.5]
---------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Jan 18, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.5, the latest cutting edge release, focuses on enhancing the
Reports module. A full list of new functionality is detailed below:

* *Cleaner Reports Interface* - Making the report writer and results view
more user friendly and less cluttered.
* *AND/OR Conditions* - Improving your ability to refine results using a
mixture of OR as well as AND logical operators.
* *New Charting Engine* - Present your report results using eye catching
configurable charts to clearly communicate your intended metrics.
* *Grouped Reports View* - Grouped Reports view, including dashlets, which
can be expanded/collapsed and grouped on multiple fields.
* *Custom file removal* - Removing a large volume of files from the custom
directory ensuring only required custom files remain.
* *Formatting Options* - Display dates and other key fields in a format
effective for your audience.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.5-rc[7.5 Release Candidate]
------------------------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Jan 11, 2016

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.5-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5-rc.tar.gz[*Source
code* (tar.gz)]

Try 7.5 Release Candidate to preview the new features coming in SuiteCRM
7.5.

The focus of SuiteCRM 7.5 is to enhance the functionality of the native
Reports module and introduce new charting functionality/designs.

This release candidate release includes the following new features, as
well as bug-fixes to the 7.5 Beta 2 release:

* Enhancements to the User Interface.
* Grouped Report View.
* AND/OR reporting operators.
* New RGraph charting engine.

https://suitecrm.com/suitecrm?id=222[Click here] to get the full details
of this release and to get the upgrade package from 7.3.x, 7.4.x, 7.5
Beta 1 and 7.5 Beta 2.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.5-beta.2[7.5 Beta 2]
-----------------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Dec 21, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.5-beta.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5-beta.2.tar.gz[*Source
code* (tar.gz)]

Try 7.5 Beta 2 to preview the new features coming in SuiteCRM 7.5.

The focus of SuiteCRM 7.5 is to enhance the functionality of the native
Reports module and introduce new charting functionality/designs.

This second Beta release includes enhancements to the User Interface,
AND/OR reporting operators, new RGraph charting functionality and bug
fixes to the 7.5 Beta 1 release.

https://suitecrm.com/suitecrm?id=222[Click here] to get the full details
of this release and to get the upgrade package from 7.3.x, 7.4.x and 7.5
Beta 1.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.5-beta[7.5 Beta]
-------------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Dec 14, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.5-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.5-beta.tar.gz[*Source
code* (tar.gz)]

Try 7.5 to preview the new features coming in SuiteCRM 7.5.

The focus of SuiteCRM 7.5 is to enhance the functionality of the native
Reports module.

The first Beta release includes enhancements to the User Interface and
the introduction of AND/OR operators.

https://suitecrm.com/suitecrm?id=222[Click here] to get the full details
of this release and to get the upgrade package from 7.3.x and 7.4.x


https://github.com/salesagility/SuiteCRM/releases/tag/v7.4.3[7.4.3]
-------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Nov 23, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.4.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4.3.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.4.3, the latest cutting edge release, introduces the new
reminder meetings functionality.

This functionality allows users to more efficiently manage call and
meeting reminders with the following features:

* Add multiple reminders to a Meeting/Call so that users can be reminded
about a meeting at different intervals.
* Select if all invitees should get a reminder so that users can choose
who to remind about the Meeting/Call.
* Choose people who should not get a reminder so that users can choose
who to remind about the Meeting/Call.
* Ability to select who receives reminders so that no one else is
reminded about the Meeting/Call.

In addition to the Reminder Meetings functionality, there have also been
many bug-fixes implemented in SuiteCRM 7.4.3.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.4.2[v7.4.2]
--------------------------------------------------------------------

_Merged branch 'reminders' into 7.4.2_


https://github.com/salesagility/SuiteCRM/releases/tag/v7.4.1[7.4.1]
-------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Nov 10, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.4.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4.1.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release for SuiteCRM 7.4 release.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.4[7.4]
---------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Oct 30, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4.tar.gz[*Source
code* (tar.gz)]

This release bring many enhancements - Favourites, Knowledge Base,
Improved PHP Compatibility and More..

For more information view the release notes on the SuiteCRM Wiki
https://suitecrm.com/wiki/index.php/Release_notes_7.4.0[here].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.3.2[7.3.2]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Oct 22, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.3.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3.2.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release for SuiteCRM 7.3 release.

For more information view the release notes on the SuiteCRM Wiki
https://suitecrm.com/wiki/index.php/Release_notes_7.3.2[here].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.4-rc[7.4 Release Candidate]
------------------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Oct 19, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.4-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4-rc.tar.gz[*Source
code* (tar.gz)]

Try 7.4RC to preview the new features coming in 7.4

Including Favourites, Knowledge Base, Improved PHP Compatibility and
More.

https://suitecrm.com/suitecrm?id=224[Click here] to get the full details
of this release and to get the upgrade package from 7.3.x and 7.4 Beta 1
or Beta 2


https://github.com/salesagility/SuiteCRM/releases/tag/v7.4-beta.2[7.4 Beta 2]
-----------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Oct 12, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.4-beta.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4-beta.2.tar.gz[*Source
code* (tar.gz)]

Try 7.4 Beta 2 to preview the new features coming in 7.4

Including Favourites, Knowledge Base, Improved Installer and More.

https://suitecrm.com/suitecrm?id=222[Click here] to get the full details
of this release and to get the upgrade package from 7.3.x and 7.4 Beta 1


https://github.com/salesagility/SuiteCRM/releases/tag/v7.4-beta[7.4 Beta]
-------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Oct 5, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.4-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4-beta.tar.gz[*Source
code* (tar.gz)]

Try 7.4 Beta to preview the new features coming in 7.4

Including Favourites, Knowledge Base and More.

https://suitecrm.com/suitecrm?id=222[Click here] to get the full details
of this release and to get the upgrade package from 7.3.x


https://github.com/salesagility/SuiteCRM/releases/tag/v7.3.1[7.3.1]
-------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Aug 25, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.3.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3.1.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release for SuiteCRM 7.3 release.

For more information view the release notes on the SuiteCRM Wiki
https://suitecrm.com/wiki/index.php/Release_notes_7.3.1[here].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.2.4[7.2.4]
-------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Aug 20, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2.4.tar.gz[*Source
code* (tar.gz)]

This is a bug-fix release.

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.3[7.3]
---------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Aug 14, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3.tar.gz[*Source
code* (tar.gz)]

This release bring many enhancements - inline editing, desktop
notifications, enhancements to Reports, enhancements to Workflow and bug
fixes.

For more information view the release notes on the SuiteCRM Wiki
https://suitecrm.com/wiki/index.php/Release_notes_7.3.0[here].

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.3beta3[7.3 Beta 3]
---------------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Aug 7, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.3beta3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3beta3.tar.gz[*Source
code* (tar.gz)]

_Don't do a final move for invalid/malicious files. See #333._


https://github.com/salesagility/SuiteCRM/releases/tag/v7.2.3[7.2.3]
-------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Aug 7, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2.3.tar.gz[*Source
code* (tar.gz)]

Update version number to the latest release version.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.8[7.1.8]
-------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Aug 7, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.8.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.8.tar.gz[*Source
code* (tar.gz)]

_Don't do a final move for invalid/malicious files. See #333._


https://github.com/salesagility/SuiteCRM/releases/tag/v7.3-beta[7.3 Beta]
-------------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this Jun 5, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.3-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3-beta.tar.gz[*Source
code* (tar.gz)]

Try 7.3 Beta to preview the new features coming in 7.3

Including Inline Editing, Desktop Notifications and More.

https://suitecrm.com/index.php?option=com_content&layout=edit&view=article&id=209[Click
here] to get the full details of this release and to get the upgrade
package from 7.2.x


https://github.com/salesagility/SuiteCRM/releases/tag/v7.2.2[7.2.2]
-------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this May 20, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2.2.tar.gz[*Source
code* (tar.gz)]

SuiteCRM 7.2 has been updated to version 7.2.2.

This is a bug fix release which addresses bugs in the SuiteCRM 7.2.1
release and also Post-Auth RCE vulnerabilities in SuiteCRM.


https://github.com/salesagility/SuiteCRM/releases/tag/7.1.7[7.1.7]
------------------------------------------------------------------

Fix Post-Auth RCE Vulnerability


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.7[7.1.7]
-------------------------------------------------------------------

https://github.com/willrennie[willrennie] released this May 20, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.7.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.7.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release which addresses Post-Auth RCE vulnerabilities
in SuiteCRM.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.2.1[7.2.1]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Mar 11, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2.1.tar.gz[*Source
code* (tar.gz)]

This is a Bug Fix release that addresses that addresses many issues

For more check out the release notes on the wiki
https://suitecrm.com/wiki/index.php/Release_notes_7.2.1[here]

Download here or https://suitecrm.com/download[click here] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.6[7.1.6]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Mar 11, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.6.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.6.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release which addresses many issues

For a full list of what has changed and been fixed check out the release
notes on the wiki


https://github.com/salesagility/SuiteCRM/releases/tag/v7.2[7.2]
---------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Mar 2, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2.tar.gz[*Source
code* (tar.gz)]

This release bring many enhancements - a brand new responsive theme,
enhanced reporting, an image field and much more

For more check out the release notes on the wiki
https://suitecrm.com/wiki/index.php/Release_notes_7.2.0[here]

Download here or https://suitecrm.com/download[click here] to find the
appropriate upgrade.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.2beta3[7.2 Beta 3]
---------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Feb 9, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2beta3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2beta3.tar.gz[*Source
code* (tar.gz)]

Try 7.2 Beta 3 to preview the new features coming in 7.2

Including reports, cases and project enhancements

https://suitecrm.com/suitecrm?id=207:download&catid=126:suitecrm-beta[Click
here] to get the full details of this release and to get the upgrade
package from 7.1.x (also valid for upgrading from 7.2 beta/beta2)


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.5[7.1.5]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Jan 19, 2015

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.5.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.5.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release which also addresses some important security
issues

For a full list of what has changed and been fixed check out the release
notes on the wiki


https://github.com/salesagility/SuiteCRM/releases/tag/v7.2beta2[7.2 Beta 2]
---------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Dec 9, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2beta2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2beta2.tar.gz[*Source
code* (tar.gz)]

Try 7.2 Beta 2 to preview the new features coming in 7.2

Including reports, cases and project enhancements

https://suitecrm.com/suitecrm?id=207:download&catid=126:suitecrm-beta[Click
here] to get the full details of this release and to get the upgrade
package from 7.1.x (also valid for upgrading from 7.2 beta)


https://github.com/salesagility/SuiteCRM/releases/tag/v7.2beta[7.2 Beta]
------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Oct 31, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.2beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.2beta.tar.gz[*Source
code* (tar.gz)]

Try 7.2 Beta to preview the new features coming in 7.2

The main new feature of this release is the new Project Management with
Gantt charts

In addition the SuiteCRM install process has been given a new look and
feel as well as many bug fixes and other little additions, and there is
still more to come.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.4[7.1.4]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Sep 25, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.4.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release which also addresses some important security
issues

For a full list of what has changed and been fixed check out the release
notes on the wiki


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.3[7.1.3]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Aug 13, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.3.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release

For a full list of what has changed and been fixed check out the release
notes on the wiki


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.2[7.1.2]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Jul 7, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.2.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release

For a full list of what has changed and been fixed check out the release
notes on the wiki


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1.1[7.1.1]
-------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Apr 7, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.1.tar.gz[*Source
code* (tar.gz)]

This is a bug fix release

For a full list of what has changed and been fixed check out the release
notes on the wiki


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1[7.1]
---------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Apr 1, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.tar.gz[*Source
code* (tar.gz)]

This release packs in many new features, most notably the many
enhancements to workflow, the new lucene powered search, (to enable see
AOD in the admin panel), the multi tabbed homepage, the ability to
filter the history sub-panel and more

https://github.com/salesagility/SuiteCRM/releases/tag/v7.1RC2[7.1 Release Candidate 2]
--------------------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Mar 28, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1RC2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1RC2.tar.gz[*Source
code* (tar.gz)]

Try out the Latest release of SuiteCRM, the final Release Candidate
before Mondays release!

Help to find the remaining bugs!

Thanks all the feedback and fixes contributed for this release


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1RC[7.1 Release Candidate]
-----------------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Mar 24, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1RC.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1RC.tar.gz[*Source
code* (tar.gz)]


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1beta2[7.1 Beta2]
--------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Mar 14, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1beta2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1beta2.tar.gz[*Source
code* (tar.gz)]

Try out the Latest Beta release of SuiteCRM with many improvements and
some major enhancements to Workflow


https://github.com/salesagility/SuiteCRM/releases/tag/v7.1beta[7.1 Beta]
------------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Feb 4, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.1beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1beta.tar.gz[*Source
code* (tar.gz)]

Try 7.1 Beta to preview the new features coming in 7.1 including
enhanced search, improved workflow and default theme plus social
integration.


https://github.com/salesagility/SuiteCRM/releases/tag/v7.0.2[v7.0.2]
--------------------------------------------------------------------

https://github.com/mattlorimer[mattlorimer] released this Jan 20, 2014

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.0.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.0.2.tar.gz[*Source
code* (tar.gz)]

Bug fix release which also adds in two new language translations for
Spanish and Russian


https://github.com/salesagility/SuiteCRM/releases/tag/v7.0.1[v7.0.1: Update README.md]
--------------------------------------------------------------------------------------

https://github.com/salesagility[salesagility] released this Nov 25, 2013

Assets
~~~~~~

* https://github.com/salesagility/SuiteCRM/archive/v7.0.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.0.1.tar.gz[*Source
code* (tar.gz)]

Adding details to SuiteCRM readme.md