---
Title: Техническая поддержка
Weight: 20
---

:author: likhobory
:email: likhobory@mail.ru


== Поддержка

Мы являемся сторонниками программного обеспечения с открытым исходным кодом.   +
Пожалуйста, не обращайтесь к нам за технической поддержкой по электронной почте или по телефону.   +
Вместо этого воспользуйтесь нашим https://community.suitecrm.com[форумом поддержки], 
 где может получить необходимую информацию любой желающий.   +
Наши разработчики ежедневно отвечают на поступающие вопросы, кроме этого, помощь оказывают и другие члены сообщества.  +
Если у вас есть желание доработать SuiteCRM непосредственно под ваши потребности, либо вы хотите воспользоваться нашим хостингом или расширенной поддержкой - 
 свяжитесь с нами, заполнив https://suitecrm.com/about/about-us/contact[эту контактную форму].


== Расширенная поддержка

Доступны различные варианты расширенной технической поддержки,
 начиная с 2 часов общения  в месяц (через систему тикетов или по телефону) и заканчивая 
 12-часовой поддержкой в месяц (через систему тикетов, по телефону или по электронной почте), 
 на протяжении которых наши знания и умения будут в вашем полном распоряжении.
