---
title: "7.4.x"
weight: 9950
---

:author: likhobory
:email: likhobory@mail.ru

:toc:
:toc-title:
:toclevels: 1


:experimental:

{{% notice note %}}
В этом разделе представлена полная история изменений системы. +
Краткая история основных нововведений и изменений системы представлена в русскоязычном разделе link:https://suitecrm.com/suitecrm/forum/suitecrm-forum-russian-general-discussion/17973-suitecrm[форума^].
{{% /notice %}}

== *7.4.3*

_Released Nov 23, 2015_

=== *Assets*

* https://github.com/salesagility/SuiteCRM/archive/v7.4.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4.3.tar.gz[*Source
code* (tar.gz)]

=== *Release Notes*

SuiteCRM 7.4.3, the latest cutting edge release, introduces the new
reminder meetings functionality.

This functionality allows users to more efficiently manage call and
meeting reminders with the following features:

* Add multiple reminders to a Meeting/Call so that users can be reminded
about a meeting at different intervals.
* Select if all invitees should get a reminder so that users can choose
who to remind about the Meeting/Call.
* Choose people who should not get a reminder so that users can choose
who to remind about the Meeting/Call.
* Ability to select who receives reminders so that no one else is
reminded about the Meeting/Call.

In addition to the Reminder Meetings functionality, there have also been
many bug-fixes implemented in SuiteCRM 7.4.3.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.4.3[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

'''
== *7.4.2*

_Merged branch 'reminders' into 7.4.2_

'''

== *7.4.1*

_Released Nov 10, 2015_

=== *Assets*

* https://github.com/salesagility/SuiteCRM/archive/v7.4.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4.1.tar.gz[*Source
code* (tar.gz)]

=== *Release Notes*

This is a bug fix release for SuiteCRM 7.4 release.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.4.1[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

'''

== *7.4.0*

_Released Oct 30, 2015_

=== *Assets*

* https://github.com/salesagility/SuiteCRM/archive/v7.4.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4.tar.gz[*Source
code* (tar.gz)]

=== *Release Notes*

This release bring many enhancements - Favourites, Knowledge Base,
Improved PHP Compatibility and More..

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.4[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

'''

== *7.4 Release Candidate*

_Released Oct 19, 2015_

=== *Assets*

* https://github.com/salesagility/SuiteCRM/archive/v7.4-rc.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4-rc.tar.gz[*Source
code* (tar.gz)]

=== *Release Notes*

*This is a beta release and should not be used in a production environment.*

Including Favourites, Knowledge Base, Improved PHP Compatibility and
More.

'''

== *7.4 Beta 2*

_Released Oct 12, 2015_

=== *Assets*

* https://github.com/salesagility/SuiteCRM/archive/v7.4-beta.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4-beta.2.tar.gz[*Source
code* (tar.gz)]

=== *Release Notes*

*This is a beta release and should not be used in a production environment.*

Including Favourites, Knowledge Base, Improved Installer and More.

'''

== *7.4 Beta*

_Released Oct 5, 2015_

=== *Assets*

* https://github.com/salesagility/SuiteCRM/archive/v7.4-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.4-beta.tar.gz[*Source
code* (tar.gz)]

=== *Release Notes*

*This is a beta release and should not be used in a production environment.*

Including Favourites, Knowledge Base and More.

'''