---
Title: 7.7.0
weight: 50
---

:experimental:

_Released Aug 2, 2016_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.7.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

[discrete]
===== Security
Includes btn:[http://support.sugarcrm.com/Documentation/Sugar_Versions/6.5/CE/Sugar_Release_Notes_6.5.24/[SugarCRM 6.5.24]]

[discrete]
===== Additional Features
* *SuiteP Theme* - We want SuiteCRM 7.7 to be something special this
Summer. Packed with new and improved features and an amazing new UI, it
will transform the way you view SuiteCRM.
* *Analytic Reporting Tool - "SuiteSpots"* - Using Drag and Drop
functionality you can create in depth Pivot Tables and charts using your
customer data.
* *Module Group Selection upon Installation Configurations* - When
installing you can choose which groups of modules you wish to include as
default. This will give users the choice of how what they feel they need
from the word go.
* *Updated* Silent Installer
* *New Calendar* library
* *New Search filter* for Event Delegates subpanel
* *Improved* Project and Project Templates functionality

Download here from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

_Special thanks for
https://github.com/salesagility/SuiteCRM/issues/1843[adminibt] for
notifying us of this security update._