---
Title: 7.7 Beta
weight: 50
---

:experimental:

_Released Jun 15, 2016_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.7-beta1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.7-beta1.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

*This is a beta release and should not be used in a production environment.*

The focus of SuiteCRM 7.7 is to introduce our new Analytical Reporting
Tool - SuiteSpots, and provide more options upon installing SuiteCRM.

The first Beta release includes enhancements to the following:

* *New Analytic Reporting Tool* - *SuiteSpots* - Using Drag and Drop
functionality you can create in depth Pivot Tables and charts using your
customer data.

* *New Module Group Selection upon installation Configurations* - When
installing you can choose which groups of modules you wish to include as
default. This will give users the choice of what modules they need from
the word go.
* Fixes for Campaigns, Calls/Meetings Reminders and other bugs
