---
Title: 7.1.2
weight: 50
---

:experimental:

_Released Jul 7, 2014_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.1.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.1.2.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

*Upgraded Sugar to 6.5.17*

SugarCRM have not released an official list of fixes, but thanks to Matthew Poer we have been able to list some fixes between SugarCRM 6.5.16 and 6.5.17:

* When sending an email, the Asynchronous request is sent via POST instead of GET.
* Module loader's security scanner now blocks simplexml_load_file and simplexml_load_string.
* The RSS dashlet replaces a function that once used simplexml_load_file with a new set of commands that replicate the functionality, but more (I presume) more securely.
* Quick Search can no longer be configured to search against users.user_hash (the user passwords).
* Minor bugfix in modules/Users/controller.php, a new save function to help it support a different server environment.
* Modules/Users/Save.php adjusted to further ensure that non-admins cannot adjust settings for other users.

{{% notice note %}}
6.5.17 introduces an important security patch.
{{% /notice %}}

[discrete]
===== Bug Fixes
* Fixed IE11 detected as Mozilla browser
* Fixed MSSQL vardef compatibility issues
* Fixed history filters search conflicts with meetings search
* Fixed Contact not populated in Contracts
* Fixed install issues
* Fixed Contracts print pdf missing
* Fixed issue where workflow may cause errors while saving a record
* Facebook/twiter fixes
* Optimised Calendar query
* Fixed footer response time text.
* Fixed twitter/facebook connector defaults
* Fixed Bugs admin panel is missing
* Fixed AOD doesn't add default config entry on install
* Fixed missing language strings on after install
* Fixed QuickCRM didn’t work with Russian language and adds support for dynamicenum
* Fixed invalid query when using relate fields in AOR
* Fixed My Activity Stream pagination issues
* Fixed My Activity Stream doesn't show in Add Dashlets
* AOD Don't use the stored index since this may be closed.
* AOD Update index on delete and restore.
* Fixed AOD bug in removing indexed records causing duplicates. Add UTF8 support. Add support for indexing numbers. Add boosts on various modules and fields.
* Fixed AOD bug caused by deleted beans appearing in search results.
* Restored meetings searchdefs.php
* Fixed Documents generated query errors
* Fixed AOD install issue on MSSQL
* Fixed issue where the export query would fail with a search on a related object
* Fixed YUI Loader Calender dashlet issue
* Fixed blank date wrongly formatted in WorkFlow when running on save
* Fixed Issue where WorkFlow would duplicated line items in AOS
* Fixed attachments from email templates don't appear when using workflow
* Fixed Issue where line items would generate incorrectly in the pdf when only one item displayed in the line
* Fixed bug "could not redeclare class in twitter connector"
* Fixed Issue when modify record that has new_with_id set to true causes it to fail
* Fixed Issue where workflow may fail on custom fields
* QuickCRM : Fix bug with web app
* Fixed in AOW lang. strings
* Fixed Missing Reschedule Language strings
* Fixed renamed reschedule field 'call', causing reserved keyword issue in query
* Upgraded Security Suite to version 2.7.4