---
Title: Calls
Weight: 120
---

= Calls

The Calls module in SuiteCRM allows Users to schedule and log a record
of inbound and outbound calls that they may be a participant of.

== Calls Actions

You can access the Calls actions from the Calls module menu drop down or
via the Sidebar. The Calls actions are as follows:

* *Log Call* – A new form is opened in Edit View to allow you to create a
new Call record.
* *View Calls* – Redirects you to the List View for the Calls module. This
allows you to search and list Call records.
* *Import Calls* – Redirects you to the Import Wizard for the Calls
module. For more information, see link:./../../introduction/user-interface/#_importing_records[Importing Records].

To view the full list of fields available when logging a Call, See
link:./../../appendix-a/#_calls_field_list[Calls Field List].

== Managing Calls

* To sort records on the Calls List View, click any column title which
is sortable. This will sort the column either ascending or descending.
* To search for a Call, see the link:./../../introduction/user-interface/#_search[Search] section of this
user guide.
* To update some or all of the Calls on the List View, use the Mass
Update panel as described in the link:./../../introduction/user-interface/#_mass_updating_records[Mass Updating Records] section of this user guide.
* To duplicate a Call, you can click the Duplicate button on the Detail
View and then save the duplicate record.
* To close a Call, click on the 'x' icon on the Calls List View. You can
also close a Call by clicking the Close button on the Detail View of a
Call. You can also click the Close and Create New button. This will
close the Call you are viewing and redirect you to the Edit View to
create a new record.
* To Reschedule a call, you can click the Reschedule button on the
Detail View of a Call. For a detailed guide on rescheduling calls, see
the link:./../../advanced-modules/reschedule/[Reschedule] section of this user guide.
* To delete one or multiple Calls, you can select multiple records from
the List View and click delete. You can also delete a Call from the
Detail View by clicking the Delete button. For a more detailed guide on
deleting records, see the link:./../../introduction/user-interface/#_deleting_records[Deleting Records]
section of this user guide.
* To view the details of a Call, click the Call Subject in the List
View. This will open the record in Detail View.
* To edit the Call details, click Edit icon within the List View or
click the edit button on the Detail View, make the necessary changes,
and click Save.
* For a detailed guide on importing and exporting Calls, see the
link:./../../introduction/user-interface/#_importing_records[Importing Records] and
link:./../../introduction/user-interface/#_exporting_records[Exporting Records] sections of this user guide.
* To track all changes to audited fields, in the Call record, you can
click the View Change Log button on the Call Detail View or Edit View.
