---
Title: Contacts
Weight: 80
---

= Contacts

In SuiteCRM a Contact is an individual who is typically associated with
an Account (organisation) or Opportunity (qualified prospect). For
example if Techco is the Account, then John Smith, Sales Manager of
Techco is the Contact. This module holds all information relating to
these individuals and also provides a vantage point for any history
relating to a Contact record, for example if they were involved in a
Meeting, raised a Case or sent an Email.

== Contacts Actions

You can access the Contacts actions from the Contacts module menu drop
down or via the Sidebar. The Contacts actions are as follows:

* *Create Contact* – A new form is opened in Edit View to allow you to
create a new Contact record.
* *View Contacts* – Redirects you to the List View for the Contacts
module. This allows you to search and list Contact records.
* *Import Contacts* – Redirects you to the Import Wizard for the Contacts
module. For more information, see link:./../../introduction/user-interface/#_importing_records[Importing Records].

To view the full list of fields available when creating an Contact, See link:./../../appendix-a/#_contacts_field_list[Contacts Field List].

== Managing Contacts

* To sort records on the Contacts List View, click any column title
which is sortable. This will sort the column either ascending or
descending.
* To search for a Contact, see the link:./../../introduction/user-interface/#_search[Search] section of this
user guide.
* To update some or all the Contacts on the List View, use the Mass
Update panel as described in the link:./../../introduction/user-interface/#_mass_updating_records[Mass Updating Records] section of this user guide.
* To duplicate a Contact, you can click the Duplicate button on the
Detail View and then save the duplicate record.
* To merge duplicate Contacts, select the records from the Contacts List
View, click the Merge link in the Actions drop-down list, and progress
through the merge process. For more information on Merging Duplicates,
see the link:./../../introduction/user-interface/#_merging_records[Merging Records] section of this user
guide.
* To delete one or multiple Contacts, you can select multiple records
from the List View and click delete. You can also delete a Contact from
the Detail View by clicking the Delete button. For a more detailed guide
on deleting records, see the link:./../../introduction/user-interface/#_deleting_records[Deleting Records]
section of this user guide.
* To view the details of a Contact, click the Contact Name in the List
View. This will open the record in Detail View.
* To edit the Contact details, click Edit icon within the List View or
click the edit button on the Detail View, make the necessary changes,
and click Save.
* For a detailed guide on importing and exporting Contacts, see the
link:./../../introduction/user-interface/#_importing_records[Importing Records] and
link:./../../introduction/user-interface/#_exporting_records[Exporting Records] sections of this user guide.
* To track all changes to audited fields, in the Contact record, you can
click the View Change Log button on the Contact's Detail View or Edit
View.
* Setting up the export of contacts in vCard format: by default, exporting contacts to vCard format is not available. The system administrator needs to replace the fields *First Name* and *Last Name* with the field *Name* using link: ../../../../admin/administration-panel/developer-tools/#_Studio], after which the {btn}[vCard] button will be available to the right of the *Name* field.
