---
Title: Documents
Weight: 170
---

= Documents

The Documents module can be used as a repository for Customer issued or
internal files. This content can be uploaded, revised and viewed in
addition to relating to individual records within SuiteCRM.

== Documents Actions

You can access the Documents actions from the Documents module menu drop
down or via the Sidebar. The Documents actions are as follows:

* *Create Document* – A new form is opened in Edit View to allow you to
create a new Document record.
* *View Documents* – Redirects you to the List View for the Documents
module. This allows you to search and list Document records.

To view the full list of fields available when creating a Document, See
link:/user/appendix-a/#_documents_field_list[Documents Field List].

== Managing Documents

* To sort records on the Documents List View, click any column title
which is sortable. This will sort the column either ascending or
descending.
* To search for a Document, see the link:/user/introduction/user-interface/#_search[Search] section of this
user guide.
* To update some or all the Documents on the List View, use the Mass
Update panel as described in the link:/user/introduction/user-interface/#_mass_updating_records[Mass Updating Records] section of this user guide.
* To duplicate a Document, you can click the Duplicate button on the
Detail View and then save the duplicate record.
* To delete one or multiple Documents, you can select multiple records
from the List View and click delete. You can also delete a Document from
the Detail View by clicking the Delete button. For a more detailed guide
on deleting records, see the link:/user/introduction/user-interface/#_deleting_records[Deleting Records]
section of this user guide.
* To view the details of a Document, click the Document Name in the List
View. This will open the record in Detail View.
* To view an attachment, click the attachment link on the List View or
Detail View of the Document. To update a document, you can create a
Document Revision.
* To edit the Document details, click Edit icon within the List View or
click the edit button on the Detail View, make the necessary changes,
and click Save.
* For a detailed guide on importing and exporting Documents, see the
link:/user/introduction/user-interface/#_importing_records[Importing Records] and
link:/user/introduction/user-interface/#_exporting_records[Exporting Records] sections of this user guide.
* To track all changes to audited fields, in the Document record, you
can click the View Change Log button on the Document's Detail View or
Edit View.