Title: Opportunities	
Weight: 90	
---	
	
= Opportunities	
	
An Opportunity is a qualified Sales prospect with a likely chance that	
they will be able to do business with your company. You have established	
that they have buying power and have entered into the buying cycle. This	
module allows you to track your Opportunities throughout the Sales	
Pipeline until the deal is 'Closed Lost or 'Closed Won'.	
	
== Opportunities Actions	
	
You can access the Opportunities actions from the Opportunities module	
menu drop down or via the Sidebar. The Opportunities actions are as	
follows:	
	
* *Create Opportunity* – A new form is opened in Edit View to allow you to	
create a new Account record.	
* *View Opportunities* – Redirects you to the List View for the	
Opportunities module. This allows you to search and list Opportunity	
records.	
* *Import Opportunities* – Redirects you to the Import Wizard for the	
Opportunities module. For more information, see	
link:/user/introduction/user-interface/#_importing_records[Importing Records].	
	
To view the full list of fields available when creating an Opportunity,	
See link:/user/appendix-a/#_opportunities_field_list[Opportunities Field List].	
	
== Managing Opportunities	
	
* To sort records on the Opportunities List View, click any column title	
which is sortable. This will sort the column either ascending or	
descending.	
* To search for a Opportunity, see the link:/user/introduction/user-interface/#_search[Search] section of	
this user guide.	
* To update some or all the Opportunities on the List View, use the Mass	
Update panel as described in the link:/user/introduction/user-interface/#_mass_updating_records[Mass Updating Records] section of this user guide.	
* To duplicate a Opportunity, you can click the Duplicate button on the	
Detail View and then save the duplicate record.	
* To merge duplicate Opportunities, select the records from the	
Opportunities List View, click the Merge link in the Actions drop-down	
list, and progress through the merge process. For more information on	
Merging Duplicates, see the link:/user/introduction/user-interface/#_merging_records[Merging Records]	
section of this user guide.	
* To delete one or multiple Opportunities, you can select multiple	
records from the List View and click delete. You can also delete a	
Opportunity from the Detail View by clicking the delete button. For a	
more detailed guide on deleting records, see the	
link:/user/introduction/user-interface/#_deleting_records[Deleting Records] section of this user guide.	
* To view the details of a Opportunity, click the Opportunity Name in	
the List View. This will open the record in Detail View.	
* To edit the Opportunity details, click the Edit icon within the List	
View or click the edit button on the Detail View, make the necessary	
changes, and click Save.	
* For a detailed guide on importing and exporting Opportunities, see the	
link:/user/introduction/user-interface/#_importing_records[Importing Records] and	
link:/user/introduction/user-interface/#_exporting_records[Exporting Records] sections of this user guide.	
* To track all changes to audited fields, in the Opportunity record, you	
can click the View Change Log button on the Opportunities Detail View or	
Edit View.
