---
Title: Oportunidades
Weight: 90
---

Una oportunidad es un prospect cualificado con una alta probabilidad de
hacer negocios con su compañia. Se ha establecido que tiene posibilidad
de compra y a entrado en el ciclo de ventas. Este módulo permite seguir 
las oportunidades a través del proceso de ventas hasta que el acuerdo 
es cerrado como 'perdido' o 'ganado'.

== Acciones de Oportunidades

Se puede acceder a las acciones desde el menu desplegable del módulo 
o desde la barra lateral. Las acciones disponibles son las siguientes:

* *Crear una Oportunidad* – Una vez cliqueada, un nuevo formulario se abre en la Vista de Edición para permitirte crear un nuevo registro de Oporunidad.
* *Ver Oportunidades* - Una vez cliqueada, serás redireccionado a la Vista de Lista del módulo de Oportunidades. Esto te permite buscar y listar registros de Oportunidades.
* *Importar Oportunidades* - Te redirige al Asistente de Importación para el módulo de oportunidades. Para más información, 
ve a la sección de link:./../../introduction/user-interface/#_importando_registros[Importando Registros].

== Gestionando Oportunidades

* Para ordenar registros en la Vista de Lista de oportunidades, cliquea sobre el título de cualquier columna que sea ordenable. Esto ordenará los registros según los valores de ese campo en orden ascendente o descendente.
* Para buscar una oportunidad, ver la sección de Búsqueda de la Guía de
Usuario.
* Para actualizar algunas o todas las oportunidades en la Vista de Lista, usa
el panel de Actualización Masiva según se describe en la sección de
Actualización Masiva de Registros de la Guía de Usuario.
* Para duplicar una Oportunidad, puedes cliquear el botón Duplicar en la
Vista de Detalle y luego guardar el registro duplicado.
* Para combinar Oportunidades duplicadas, selecciona los registros desde la
Vista de Lista de oportunidades, cliquea en el enlace de Combinar en el menú
desplegable de Acciones para comenzar el proceso de combinado. Para más
información sobre combinar duplicados, ver la sección de Combinado de
Registros de la Guía de Usuario.
* Para eliminar una o multiples oportunidades, puedes seleccionar múltiples
registros desde la Vista de Lista y cliquear Eliminar. También puedes
eliminar una Oportunidad desde la Vista de Detalle utilizando el botón
Eliminar de la misma. Para mayor información sobre el eliminado de
registros, ver la sección Eliminando Registros de la Guía de Usuario.
* Para ver los detalles de una Oportunidad, cliquea sobre el Nombre de la
Oportunidad en la Vista de Lista. Esto abrirá la Vista de Detalle del
registro.
* Para editar los detalles de una Oportunidad, cliquea en el botón Editar
en la Vista de Lista o en la Vista de Detalle, haz los cambios
necesarios, y cliquea en Guardar.
* Para una guía detallada sobre la importación y exportación de
Contactos, ver la sección Importando Registros y Exportando Registros de
la Guía de Usuario.
* Para mantener un seguimiento de los cambios realizados sobre campos
auditados en el registro de una Oportunidad, puedes cliquear el botón Ver
Historial de Cambios en la Vista de Detalle o de Edición de la Oportunidad.
