---
Title: Tasks
Weight: 150
---

= Tasks

SuiteCRM can assist Users with productivity, offering a way to record,
relate and assign Tasks and to-do items that require action.

== Tasks Actions

You can access the Tasks actions from the Tasks module menu drop down or
via the Sidebar. The Tasks actions are as follows:

* *Create Task* – A new form is opened in Edit View to allow you to create
a new Task record.
* *View Tasks* – Redirects you to the List View for the Tasks module. This
allows you to search and list Task records.
* *Import Tasks* – Redirects you to the Import Wizard for the Tasks
module. For more information, see link:./../../introduction/user-interface/record-management/#_importing_records[Importing Records].

To view the full list of fields available when creating a Task, See
link:./../../appendix-a/#_tasks_field_list[Tasks Field List].

== Managing Tasks

* To sort records on the Tasks List View, click any column title which
is sortable. This will sort the column either ascending or descending.
* To search for a Task, see the link:./../../introduction/user-interface/search[Search] section of this
user guide.
* To update some or all of the Task on the List View, use the Mass
Update panel as described in the link:./../../introduction/user-interface/record-management/#_mass_updating_records[Mass Updating Records] section of this user guide.
* To duplicate a Task, you can click the Duplicate button on the Detail
View and then save the duplicate record.
* To close a Task, click on the 'x' icon on the Tasks List View. You can
also close a Meeting by clicking the Close button on the Detail View of
a Task. You can also click the Close and Create New button. This will
close the Task you are viewing and redirect you to the Edit View to
create a new record.
* To delete one or multiple Tasks, you can select multiple records from
the List View and click delete. You can also delete a Task from the
Detail View by clicking the Delete button. For a more detailed guide on
deleting records, see the link:./../../introduction/user-interface/record-management/#_deleting_records[Deleting Records]
section of this user guide.
* To view the details of a Task, click the Meeting Subject in the List
View. This will open the record in Detail View.
* To edit the Task details, click Edit icon within the List View or
click the edit button on the Detail View, make the necessary changes,
and click Save.
* For a detailed guide on importing and exporting Tasks, see the
link:./../../introduction/user-interface/record-management/#_importing_records[Importing Records] and
link:./../../introduction/user-interface/record-management/#_exporting_records[Exporting Records] sections of this user guide.
* To track all changes to audited fields, in the Task record, you can
click the View Change Log button on the Task's Detail View or Edit View.