---
title: Downloading & Installing
weight: 20
---

== Downloading and installing SuiteCRM

If you are installing SuiteCRM for the first time, follow the
instructions in this section. If you have an earlier version of SuiteCRM
installed, refer to the upgrade section for instructions on how to
upgrade your SuiteCRM instance. Follow the steps listed below to install
SuiteCRM:

.  Install the platform-appropriate (Linux or Windows) version of PHP,
web server, and database on your machine.
.  Download the SuiteCRM files from suitecrm.com(see “Downloading the
latest SuiteCRM files” section).
.  Copy the SuiteCRM files to your web server.
.  Install SuiteCRM by following the SuiteCRM installation wizard.

=== Downloading the latest SuiteCRM files

.  Navigate to the SuiteCRM Downloads section at
http://suitecrm.com/download
.  Download your flavour of SuiteCRM. We advise that all users download
the latest SuiteCRM release. The latest version will contain the latest
features and bug fixes.
.  If you experience any issues during registering an account on our
website or downloading SuiteCRM, please use our support forums.

=== Copying SuiteCRM files to web server

Once your SuiteCRM package has downloaded, you will need to unzip the
files and set permissions required for the installation process. The
following steps explain in detail the prerequisites to setting up your
SuiteCRM files for installation:

.  Locate the directory on the web server in which the SuiteCRM
directory will be located(most commonly the root directory, or within a
subdirectory).
.  Unzip SuiteCRM into the directory selected in Step 1. This creates a
“SuiteCRM” directory within your selected parent directory.
.  At this stage, you may wish to rename the default “SuiteCRM”
directory.
.  Set the correct permissions on the SuiteCRM directory (Linux):
+
[source]
----
  sudo chown -R www-data:www-data .
  sudo chmod -R 755 .
  sudo chmod -R 775 cache custom modules themes data upload
  sudo chmod 775 config_override.php 2>/dev/null
----
.  That `www-data` needs to be replaced by the actual system user that your web server runs under. This varies depending on your
operating system. Common web server users are as follows:
..  www-data (Ubuntu Linux/Apache)
..  apache (Linux/Apache)
..  nobody (Linux/Apache)
..  IUSR_computerName (Windows/IIS)
The commands/steps taken to setting permissions differ dependant on
your operating system. If you are experiencing issues with setting
permissions on your SuiteCRM instance, visit our support forums.

=== Recommended installation pre-requisites

* PHP
* JSON
* XML Parsing
* MB Strings Module
* Writable SugarCRM Configuration File (config.php)
* Writeable Custom Directory
* Writable Modules Sub-Directories and Files
* Writable Upload Directory
* Writable Data Sub-Directories
* Writable Cache Sub-Directories
* PHP Memory Limit (at least 128M)
* ZLIB Compression Module
* ZIP Handling Module
* PCRE Library
* IMAP Module
* cURL Module
* Upload File Size
* Sprite Support

=== Installing SuiteCRM

Once you have successfully copied the SuiteCRM files to your web server,
you need to install SuiteCRM by following the on-screen installation
wizard. You can navigate to the wizard by entering the following in your
web browser:

`http://<yourServer>/<yourSuiteCRMDirectory>/install.php` 

You can perform a typical installation or a custom installation. Typical
installation is recommended, but you can choose custom installation for
the following reasons: The same Database Admin User should not be used
as the SuiteCRM database administrator Locale settings should be
specified during installation instead of after logging into SuiteCRM

=== Performing a typical installation of SuiteCRM

.  Launch your browser and enter the following URL:

`http://<yourServer>/<yourSuiteCRMDirectory>/install.php`

* This displays the Welcome page.
.  Click Next.
* The Installer displays installation instructions and requirements to
help determine successful SuiteCRM installation.
.  Review the information and click Next.
* This displays the SuiteCRM License Agreement.
.  Review the license, check I Accept, and click Next. The installer
checks the system for compatibility and then displays the Installation
Options page.
* Note: You can modify any of your settings at any time prior to
clicking Install in the Confirm Setting menu. To modify any settings,
click the Back button on your browser to return to the appropriate page.
.  Select Typical Install.
.  Click Next. This displays the Database Type page.
.  Select the database that is installed on your system and click Next. This displays the Database Configuration page.

.. Enter the database name. The Installer uses “suitecrm” as the default
name for the database. You can specify a new name. +
.. Enter the Host Name or the Host Instance for the MySQL, MariaDB or
SQL Server. The host name is, by default, set to localhost if your
database server is running on the same machine as your web server. +
.. Enter the username and password for the Database Administrator and
specify the SuiteCRM Database Username. +
.. Ensure that the Database Administrator you specify has the
permissions to create and write to the SuiteCRM database.
*  For My SQL, MariaDB and SQL Server, by default, the Installer selects
  the Admin User as the SuiteCRM Database User. The SuiteCRM application
  uses SuiteCRM Database User to communicate with the SuiteCRM database.
  You can create a different SuiteCRM Database user at this time.
*  To select an existing user, choose Provide existing user from
the SuiteCRM Database Username drop-down list. To create a new SuiteCRM
Database user, choose Define user. Enter the database username and
password in the relevant fields. Re-enter the password to confirm it.
The new user information is displayed in System Credentials on the
Confirm Settings page at the end of the installation process.
.. Accept No as the default value if you do not want the SuiteCRM Demo
data. Select Yes to populate the database with the SuiteCRM Demo data.
.  Click Next. The Installer validates the credentials of the specified
administrator. If a database with that name already exists, it displays
a dialog box asking you to either accept the database name or choose a
new database. If you use an existing database name, the database tables
will be dropped.
.  Click Accept to accept the database name or click Cancel and enter a
new name in the Database Name field.
* This displays the Site Configuration page.
. Enter a name for the SuiteCRM administrator.
* The SuiteCRM administrator (default name admin) has administrative
privileges in SuiteCRM. You can change the default username.
. Enter a password for the SuiteCRM admin, re-enter it to confirm the
password, and click Next.
* This displays the Confirm Settings page. The Confirm Settings page
displays a summary of the specified settings. Click Back on your browser
to navigate to previous pages if you want to change the settings.
. Click Print Summary for a printout of the settings for your records.
* Click Show Passwords and then click Print Summary to include the
database user password and the SuiteCRM admin password in the printout.
When you click Show Passwords, the system displays the passwords and
changes the button name to Hide Passwords. You can click this button to
hide the passwords again.
. Click Install.
* This displays the Perform Setup page with the installation progress.
. Click Next when the setup is complete.
* This displays the Registration page(registration is optional).
. Enter the necessary information and click Send Registration to
register your SuiteCRM instance with SuiteCRM; or click No Thanks to
skip registration.
* This displays the SuiteCRM login page. You can now log into SuiteCRM
with the SuiteCRM admin name and password that you specified during
installation.

=== Performing a custom installation of SuiteCRM

.  Launch your browser and go to your new SuiteCRM installation. The URL should be similar to the following:
`http://crm.yourserver.com/Suite-CRM-Directory/install.php`
 
.  The _Welcome to the SuiteCRM Setup Wizard_ screen
You need to accept the licence agreement first. To do so:
..  Click the _I Accept_ checkbox.
..  Click _Next_ to continue.
.  The _Pre-Installation requirements_ screen
The installer will display installation instructions and requirements.
..  Please review the information and resolve any issues.
..  Click _Next_ to continue.
.  The _Configuration_ screen
This is where you will configure SuiteCRM to work with your customized environment.
..  _Database Configuration_
...  _Specify Database Type_
Select the type of database you will be using. If you do not see your
database here, please make sure you have installed the correct php
modules.
...  _Provide Database Name_
....  _Database Name_
`suitecrm` is default name for the database. You can specify a
custom name as well.
....  _Host Name_
It is set to `localhost` by default. If your database server is
running on a different machine as your web server, you can specify a
custom location.
....  _User_ & _Password_
Enter the username and password for the Database Administrator and
specify the SuiteCRM Database Username. _Note_: You must ensure that
the Database Administrator you specify has the permissions to create
and write to the SuiteCRM database.
....  _SuiteCRM Database User_
The SuiteCRM application uses the SuiteCRM Database user to
communicate with the SuiteCRM database. For MySQL, MariaDB and SQL
Server, the Installer selects the Admin user by default. You can also
select an existing database user or create a new one. To do so Enter
the database username and password in the relevant fields and re-enter
the password to confirm it. This new user information displays in
_System Credentials_ on the _Confirm Settings_ page at the end of the installation process.
..  _Site Configuration_
...  _Identify Administration User_
....  _SuiteCRM Application Admin Name_
This is the username of the administrator account. Ex:
`johnsmith`
....  _SuiteCRM Admin User Password_
This is the password of the administrator account. Please re-enter it
in the _Re-enter SuiteCRM Admin User Password_ section for validation.
....  _URL of SuiteCRM Instance_
The URL to the CRM. Ex:
http://crm.yourserver.com/Suite-CRM-Directory
....  _Email Address_
This is the administrator's email address. Ex:
`john.smith@yourserver.com`
...  _More Options_
In this section you can opt to:
* Populate SuiteCRM with demo data
* Add SMTP server specifications
* Add branding (Name and logo)
* Set the system locale
* Set security options
Once you are happy with all the settings on the page click _Next_ to
begin installation.
.  The _Installation_ screen
The Installer validates the credentials of the specified
administrator. If a database with the specified name already exists,
it displays a dialog box prompting you to either accept the database
name or choose a new database. If you use an existing database name,
the database tables will be dropped. Click Accept to drop current
tables or click Cancel and specify a new database name.
.  Login to your new SuiteCRM instance!
