---
title: Using the Upgrade Wizard
weight: 40
---

== Using the Upgrade Wizard

The Upgrade Wizard provides a quick way to upgrade to the latest version
of the SuiteCRM application. It includes critical upgrade logic as well
as the SQL commands needed to upgrade the application. Ensure that the
config.php file for your installation, located in the SuiteCRM root
directory, is writable, before using the Upgrade Wizard. Note: Manual
upgrades by file replacements and running the upgrade SQL are not
supported.

== Debugging steps for use in upgrade version prior to 7.11.11 and 7.10.23
Known issues with the upgrade process fixed as part of this release will unfortunately not take effect until the next upgrade cycle. Therefore it is vital that if you encounter any issue while installing that you review and follow the recommended process as noted below:

==== 1: The screen becomes blank and stops loading.
*Symptoms*

* Only visible are the background colours for the header and left-sidebar.
* The page has stopped loading, and the refresh icon is stationary.
* The loading centre box has disappeared

*Action*

1. Press the home button
2. Wait until you arrive on the home page. Navigate to the Administration Menu and press on upgrade wizard.
3. Your page may not change away from the Administration Menu however you will notice the refresh icon revolving, indicating that the upgrade is completing.
4. Wait until you are redirected to the commit page at which point you can resume your upgrade as usual.

==== 2: Timeout Error Page
*Symptoms*

* CRM is no longer visible, and a browser error page has appeared.
* The page has stopped loading, and the refresh icon is stationary.

*Action*

1. Refresh the page. You will be redirected back to the home page of your SuiteCRM instance.
2. Navigate to the Administration Menu and press on upgrade wizard.
3. Your page will not change away from the Administration Menu however you will notice the refresh icon revolving, indicating that the upgrade is completing.
4. Wait until you are redirected to either the first page of the Upgrade Wizard at which point you upgrade is complete and you should be able to press home continue using the CRM as usual in the new version or the commit page at which point you can resume your upgrade as usual.

Note: This issue could potentially arise twice during the upgrade process; however, it's solved by following the instructions for a second time.

=== Upgrading SuiteCRM using the Upgrade Wizard

1.  Download the appropriate SuiteCRM Upgrade zip file from the SuiteCRM
website to your local machine. For example, download the
SuiteCRMPro-Upgrade-6.4.x-to-6.5.0.zipfile to upgrade SuiteCRM
Professional from version 6.4.x to 6.5.0. Download the appropriate
conversion file to convert to SuiteCRM Professional or SuiteCRM
Enterprise.
2.  Log into your existing SuiteCRM application as the administrator and
click admin on the right-hand corner of the page.
3.  Click Upgrade Wizard in the Systems panel of the Administration Home
page.
* This displays the Upgrade Wizard page.
4.  Click Next.
* This displays the System Checks page. SuiteCRM begins the system
check process. The Systems Check page indicates that there were no
issues if the system check process completes successfully. Issues with
file permissions, database, and server settings are listed on the page
if the system check process encountered any problems.
5.  Click Next if the system check is successful.
* This displays the Upload an Upgrade page.
6.  Click Browse, and navigate to the location of the upgrade zip file
and select it.
* The path to the file displays in the Upload an Upgrade field.
7.  Click Upload Upgrade to upload the package to the SuiteCRM
application.
* The system uploads the package and displays it on the page. Use the
Delete Package button to remove the package if necessary.
8.  Click Next.
* This displays the Preflight Check page.
* Click Show Schema Change Script to view differences in the SuiteCRM
databases schema between your current and new SuiteCRM versions.
* By default, the Upgrade Wizard Runs SQL option is selected as the
database update method. Select Manual SQL Queries from the Database
Update Method drop-down list and select the Check when SQL has been
manually run box, if you ran the SQL queries manually.
9.  Click Recheck to rerun Preflight Check. Click Next to skip this
step.
* This displays the Commit Upgrade page.
* You can also click Show to see a list of files that were copied and
the rebuilt results. You can also view skipped queries.
10. Click Next.
* During the upgrade process, SuiteCRM performs a three-way merge
between the customized instance on old version, default instance on old
version, and default instance on new version. This three-way merge adds
any fields that have been added to the default module layouts in the new
version to the corresponding module layouts in the existing version, if
the module layouts in the old version were not customized through Studio
(or in the appropriate upgrade-safe way) prior to the upgrade. The
three-way merge also changes the placement of fields in
non-Studio-customized module layouts to match the placement in the
default module layouts.
* SuiteCRM displays the Confirm Layouts page as Step 5 of the upgrade
process if the existing module layouts have been customized, and there
are changes to the default fields and field placement in the new module
layouts.
* The Confirm Layouts page lists the module layouts that have changed in
the new version. The administrator has the option of applying the
changes to the existing module layouts. By default, all of the listed
module layouts are selected to be merged during the upgrade.
* For example, in 6.1.0, SuiteCRM added the Assigned To fields to the
default Detail View and Edit View layouts for Notes and for Email
Templates. If the instance being upgraded has a customized EditView
layout for Notes, but no customized layouts for Email Templates, the
=== following will occur during the upgrade:

a. The Confirm Layouts page appears as Step 5 in the Upgrade Wizard +
b. The Confirm Layouts page displays the Notes module with the EditView
and DetailView layouts. The Email Templates layouts do not display on
the Confirm Layouts page because the existing layouts were not
customized. +
c. The Administrator has the option of choosing to merge the changes in
the Notes module with the existing customized EditView layout.
11. Uncheck the module if you do not want to add the new fields to a
module.
12. Click Next.
* This displays a message confirming that the layouts were successfully
merged (if you chose to update your modules).
13. Click Next.
14. The Debrief page confirms the upgrade installation. Complete the
steps for manual merging of files or running SQL queries now.
15. Click Done.
* This displays the Home page indicating that the upgrade is complete.
16. Click Repair and select the Rebuild Relationships and Rebuild
Extensions options in the Systems panel of the Administration Home page.
* For more information, see Repair.
17. Manually merge the files by extracting the skipped file from the
patch zip file if you unchecked any files to prevent the Upgrade Wizard
from overwriting them. Merge the file installed in the SuiteCRM
application directory.
* Note:Check the upgradeWizard.log file in the SuiteCRM folder for
information on unsuccessful SuiteCRM upgrades.