---
title: "7.3.x Releases"
weight: 9960
---

:toc:
:toc-title:
:toclevels: 1

:experimental:

== 7.3.2

_Released Oct 22, 2015_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.3.2.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3.2.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

[discrete]
===== Bug Fixes
* Fixed  #416 Studio: New Drop Down List Issue
* Fixed Email user issue in workflow
* Fixed report join issues
* Fixed #430 Create Calendar entry on mobile view
* Fixed issue #455
* Prep module builder for php7 compatibility
* Fixed issue #560
* Fixed partners link in About screen. Fixes #547
* Fixed issue #437
* Fixed issue #360
* Fixed #512 - Issue with all/more menu not being scrollable on resolutions that have a height smaller than 700px.
* Remove duplicate hidden input causing issues
* Fixed issue #506
* Fixed issue #363
* Update generatePdf.php to avoid blank pages
* Reduced padding on Layout Editor. Previously caused all fields to move to the left side of editor on some resolutions, due to lack of space.
* Removed gap between Quick-Create Plus on top-right and its Dropdown. Fixes #433
* Removed Redundant Code that caused some pages to not load on some Mobile Devices.
* Fixing multiple issues with Calendar and sidebar conflicts, sidebar white space appearing and small CSS fixes.
* Fixed issue #380
* Fixed issue #383
* Escaping the ID in the query as it comes from the $_REQUEST object.
* Adding additional checks on data.
* Adding additional checks on data.
* Fixed all major vulnerabilities
* Fixed issue #381
* Fixed issue #353 This fix should be combined with Jims proposal to remove references
* Fixed issue #305
* Fixed issue #51
* Fixed injection venerability in the delete function.
* XSS Venerability echoing out request data.
* XSS Venerability
* Adding the City field to the Lead Convert form in the Contact section
* Scrolling in Edit of Layout in Studio/ModuleBuilder not possible
* Update TemplateHandler.php
* Fixed issue 446
* Allow demodata in silent install
* Fixed when login session expires. Alerts now looks for the login form then stops updating the alert manager.
* Fixed #410 php didnt know to reference the button colour or the actual save button
* Add id_name to the query in create_new_list_query
* Add id_name to the query in create_new_list_query
* Skip .git folder on file system checks
* Fixed #403 - Dashlets dialog issues on Chrome.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.3.2[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.


'''

== 7.3.1

_Released Aug 25, 2015_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.3.1.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3.1.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

[discrete]
===== Bug Fixes
* Fixed #368 - Progress message added until Studio Field saving and show results.
* Re-implementing another bootstrap fix that was overwritten updating to v3.3.5.
* Fixed small issues with top right user menu link moving when screen resizes. Fixing small conflict in Bootstrap CSS.
* Make cookies httponly by default in SugarApplication::setCookie
* Mark the subpanel cookies as httponly
* Mark cookies httponly in the users module.
* Mark the user theme cookie as httponly.
* Use httponly cookies in the facebook social connector.
* Remove the deprecated linkedin code.
* Fixed #392 - Issues with Action Menu CSS.
* Fixed #374 - AOR Chart Label - show readable labels on all charts
* Fixing link to wiki/documentation in README.md, updating links to https.
* Implement desired menu icon for mobile navigation.
* Small fixes to menu CSS, adding missing files which were causing errors in console.
* Fixed #69, Fixed #197 - Addressing issues around the print page functionality.
* Fixed #365 - Responsive template bugs related to css layers. This also addresses issues with the popup when navigating to Settings -> Mail Accounts -> Add.
* Ensuring desktop notifications icon/section has its own div ID. It is bad practice to use the same ID twice or more as an ID should be unique.
* Updated Bootstrap to version 3.3.5, removed redundant bootstrap.js file from the theme, moved images out of js directory for colour picker and placed in their own directory(so as to not conflict with theme images).
* Removing non-required input closing tags as this is incorrect syntax.
* Fixed #210 - Workflows firing date and 'Run On' select fixed.
* Remove display errors
* Fixed #181 - Error with AOR email link fixed
* Added variable which was missing from campaign log - date_modified. (clashes with import wizard)
* Remove references to the unknown expenses module from the events subpanel. Related to the 500 error in #353.
* Check database name validation in different database types
* Changes to make inline edit work with flexi relationships such as parent on task module
* Fixed #249 - sugarcrm_login.png needs to be changed to suitecrm_login.png
* Fixed #351 - Removed duplicate language entry for LBL_DELETE_USER_CONFIRM.
* Fixed #359, Fixed #358. Issues which cause Calls to crash in Spanish language pack due to trailing comma.
* Fixed #354 - Inline editing breaking module builder Vardefs.
* Fixed #279, Fixed #300 - Addresses issues with scrolling on toolbox and panels sections of Studio.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.3.1[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

'''

== 7.3.0

_Released Aug 14, 2015_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

[discrete]
===== Additional Features
* Inline Editing
	- Edit fields directly on the List and Detail View by double clicking the field.
	- To turn inline editing off for a particular field view the field in studio and uncheck "Inline Editing"

* Desktop Notifications
	- Get Meeting/Calls Notifications direct to your desktop (enable per compatible browser in user preferences)
	- View missed Notifications in the top bar

[discrete]
===== Enhancements
* Improved Mobile Navigation
	- New improved mobile menu layout, designed to give you full control, using less screen space.
* Update cases from detail view.
* Numerous workflow enhancements e.g is null, contains etc.
* Numerous reports enhancements e.g date periods, dashlet improvements.

Download https://github.com/salesagility/SuiteCRM/releases/tag/v7.3[here] from the SuiteCRM GitHub Repository or
https://suitecrm.com/download[visit the official website] to find the
appropriate upgrade.

'''

== 7.3 Beta 2

_Released Aug 7, 2015_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.3beta3.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3beta3.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

_Don't do a final move for invalid/malicious files. See #333._

'''

== 7.3 Beta

_Released Jun 5, 2015_

=== Assets

* https://github.com/salesagility/SuiteCRM/archive/v7.3-beta.zip[*Source
code* (zip)]
* https://github.com/salesagility/SuiteCRM/archive/v7.3-beta.tar.gz[*Source
code* (tar.gz)]

=== Release Notes

*This is a beta release and should not be used in a production environment.*

Including Inline Editing, Desktop Notifications and More.

'''