---
title: "Frontend extension - Migrate to SuiteCRM 8.8+"
weight: 20
---

:imagesdir: /images/en/8.x/developer/extensions/front-end/migration

{{% notice info %}}
The following documentation is for SuiteCRM Version 8+; to see documentation for Version 7, click link:../../../../../../developer/introduction[here].
{{% /notice %}}


== 1. Intro

The following guide explains how to migrate extensions created in a version prior to SuiteCRM 8.8. So they can work on SuiteCRM 8.8+.

In SuiteCRM 8.8 angular version has been updated to v18. This brought some changes to the SuiteCRM setup.

⚠️ *Important*: SuiteCRM is still using Webpack and Module Federation. We will not be using esbuild and Native Federation for the time being.

== 2. Structure Changes

* `core/app/common` is now inside `core/app/src/lib/common/`.
* `zone.js` has been disabled (using provideExperimentalZonelessChangeDetection)
* `angular.json` is now a generated file and is no longer under version control.
** Using the `yarn merge-angular-json` it is generated from `base-angular.json` and any extensions' `angular.json`.
** The `base-angular.json` is now under `core/angular/base-angular.json`.


== 3. Command Changes

* `yarn run build:common` is no longer needed.
* `yarn build` can be run to build in production.
** `yarn build-dev` can be run to build in development.
* New command `yarn merge-angular-json` added. to merge all angular jsons from any extensions and core and merge them into the generated `angular.json`.
* `yarn build:extension <extensions name>` to build an extension. e.g `yarn build:extension defaultExt`.
** Replaces `yarn build:<extension>`, e.g. `yarn build:defaultExt`.

== 4. Frontend Extension Configuration yarn run build:common changes

{{% notice warning %}}
If using extensions please ensure to update extension configuration.
{{% /notice %}}

* Update `webpack.config.js`. (You can use the `webpack.config.js` on `defaultExt` as reference).
* To build an extensions you must now run `yarn build:extension <extensions name>` e.g `yarn build:extension defaultExt`
** `yarn build-dev:extension <extensions name>` to build in development
* `yarn merge-angular-json` will merge all angular jsons from any extensions and core and merge them into the generated `angular.json`
* Each extension should have its' own `angular.json` file.
** This should not be commited
* Removed `angular.json`. -> *No other structure changes for extensions*.
