
---
weight: 23
title: "Appendix C - Automated Testing"
---

:imagesdir: ./../../../images/en/developer

:toc:
:toclevels: 4



== Introduction

Automated testing provides a means to ensure that the quality of the SuiteCRM is kept to a high standard of quality. SuiteCRM has automated test framework, which is powered by the http://codeception.com[codeception] testing framework.

=== Installing the testing framework

In your terminal emulator or command prompt.

`cd /path/to/suitecrm/instance`

Run the command:

`composer install`

== Test Suites

SuiteCRM offers many different test suites.

[width="80",cols="30,50",options="header",]
|=======================================================================
| Suite | Description

| acceptance | ensure that the software meets requirements of a user story
| functional | ensure that the subsystems of the code base interact correctly
| unit | Unit tests reflect that a single unit of code eg a method
| api | functional test which test the api version 8 responses
| install | acceptance test to test that the install wizard is working correctly
| demo | used to test the suitecrm demo site
|=======================================================================


=== Running Codeception for the first time
Codeception and the other commands live inside the vendor/bin/ directory of your SuiteCRM instance. To test that your configuration is working you need to first install your copy of suitecrm. After installing SuiteCRM you can run the unit tests:

`./vendor/bin/codecept run unit`


== Requirements

Each tests suites has its own set of requirements.

=== Unit tests

To run the unit test, you just need to the install the testing framework.

You can continue to run the unit test suite using the command:

`./vendor/bin/codecept run unit`

=== Functional and API tests

The functional and api tests require that you import the database (or .sql) files which exist the tests/_data folder. You also need to configure the test environment variables.

You can run the functional test suite using the command:

`./vendor/bin/codecept run functional`

You can run the api test suite using the command:

`./vendor/bin/codecept run api`

=== Acceptance, Demo and Install tests

The acceptance, demo and install tests require to configure the test environment. You will also need to have en external testing browser service such as https://docs.seleniumhq.org/[Selenium] or https://www.browserstack.com/[Browser Stack].

You can run the acceptance test suite using the command:

`./vendor/bin/codecept run acceptance`

You can run the api test suite using the command:

`./vendor/bin/codecept run api`


== Add vendor bin to your PATH

To make it easier to run codeception and the other commands which live in vendor/bin/ directory. You can add the vendor/bin location to your PATH environment variable.

*Adding vendor/bin to PATH (Bash):*

`export PATH=$PATH:/path/to/instance/vendor/bin`

*Adding vendor/bin to PATH (Command Prompt):*

`set PATH=%PATH%;C:\path\to\instance\vendor\bin`

This allows you to call the codecept command without having to prefix the command with its location. When running codecept you should ensure that your current working directory is the same as your suitecrm instance.

`cd /path/to/suitecrm/instance/`

`codecept run unit`

== Configuring the test environment

SuiteCRM requires you to configure the automated test with your development environment. There are a number of ways to configure your environment.

* You can configure the automated test by adding an yml file to the tests/_envs folder
* You can edit the yml files for each test suite
* You can set up environment variables in the terminal or command prompt (recommended)


=== Environment Variables

This is the preferred method to store sensitive information, as it prevent security information from being committed to the git repository.
You can automate different development environments using environment variables.

==== Test Suite Requirements

*Install Test Suite:*

[width="80",cols="30,50",options="header",]
|=======================================================================
| Variable | Description

| DATABASE_DRIVER | MYSQL or MSSQL
| DATABASE_HOST |path to database server
| DATABASE_NAME |name of the database
| DATABASE_USER |database user
| DATABASE_PASSWORD |database password
|=======================================================================

*Acceptance, API, and Install Test Suites:*
|=======================================================================
| Variable | Description

| INSTANCE_URL |URL of the SuiteCRM instance which the tester need to access
| INSTANCE_ADMIN_USER |admin user for logging in
| INSTANCE_ADMIN_PASSWORD |admin password for logging in
|=======================================================================


*API Test Suites:*
|=======================================================================
| Variable | Description

| INSTANCE_CLIENT_ID |id of the client
| INSTANCE_CLIENT_SECRET |secret of the client
|=======================================================================

==== Setup environment variables (bash):
Open terminal and run robo

`./vendor/bin/robo configure:tests`

==== Setup environment variables (Command Prompt):

Open terminal and run robo

`.\vendor\bin\robo configure:tests`

==== Setup environment variables (Docker Compose):

You can add a .env file into your docker compose setup:

[source,bash]
DATABASE_DRIVER=MYSQL
DATABASE_NAME=automated_tests
DATABASE_HOST=localhost
DATABASE_USER=automated_tests
DATABASE_PASSWORD=automated_tests
INSTANCE_URL=http://path/to/instance
INSTANCE_ADMIN_USER=admin
INSTANCE_ADMIN_PASSWORD=admin
INSTANCE_CLIENT_ID=suitecrm_client
INSTANCE_CLIENT_SECRET=secret

then reference it in your php container (docker-compose.yml):

[source,docker]
version: '3'
services:
  php:
      image: php:7.0-apache
      restart: always
      ports:
        - 9001:80
      environment:
       - DATABASE_DRIVER: $DATABASE_DRIVER
       - DATABASE_NAME: $DATABASE_NAME
       - DATABASE_HOST: $DATABASE_HOST
       - DATABASE_USER: $DATABASE_USER
       - DATABASE_PASSWORD: $DATABASE_PASSWORD
       - INSTANCE_URL: $INSTANCE_URL
       - INSTANCE_ADMIN_USER: $INSTANCE_ADMIN_USER
       - INSTANCE_ADMIN_PASSWORD: $INSTANCE_ADMIN_PASSWORD
       - INSTANCE_CLIENT_ID: $INSTANCE_CLIENT_ID
       - INSTANCE_CLIENT_SECRET: $INSTANCE_CLIENT_SECRET

== Running the test environment

The SuiteCRM automated testing framework can support different environments. You can see the different configurations for test environments in tests/_env folder. There are different prefixes fore each testing environment you choose to deploy.

* selenium- Configures the features for selenium web driver environment
* browser-stack- Configures features for browser stack environment
* travis-ci- Configures features for travis-ci environment


To run the tests in a single environment, add a --env flag to the codecept command; seperating each configuration by a comma:

`codecept run acceptance --env selenium-hub,selenium-iphone-6`

It is also possible to run multi environments at the same time by adding multiple --env flags:

`codecept run acceptance --env selenium-hub,selenium-iphone-6  --env selenium-hub,selenium-hd --env browser-stack,browser-stack-ipad-2`

The tests will be executed 3 times. One for each environment


=== Selenium

The SuiteCRM testing framework can be configured to use selenium as the browser service.

==== Using Selenium with a local PHP environment

You may prefer to run in a local PHP environment instead of using docker compose. This requires that you need to have selenium running locally on your computer. When running in a local environment, you do not need to include the selenium-hub environment variable. Instead, you must choose which browser you have set up locally:

`codecept run demo --env selenium-chrome`



==== Using Docker Compose with the Selenium Hub

In your selenium development environment, It is recommended that you employ docker compose to set up a selenium hub with a selenium node. As this will ensure your version of chrome and firefox are kept up-to-date with the latest version. Plus you can then run multiple version of PHP on the same host machine.

You can configure selenium using docker compose. Please ensure you have the following in your docker-compose.yml file.

[source,docker]
version: '3'
services:
    selenium-hub:
      image: selenium/hub
      restart: always
      ports:
        - 4444:4444
    selenium-node-chrome:
      image: selenium/node-chrome-debug
      restart: always
      ports:
        - 5900:5900
      links:
        - selenium-hub:hub
      environment:
              - "HUB_PORT_4444_TCP_ADDR=selenium-hub"
              - "HUB_PORT_4444_TCP_PORT=4444"
    selenium-node-firefox:
      image: selenium/node-firefox-debug
      restart: always
      ports:
        - 5901:5900
      links:
        - selenium-hub:hub
      environment:
              - "HUB_PORT_4444_TCP_ADDR=selenium-hub"
              - "HUB_PORT_4444_TCP_PORT=4444"

*Note: you can also choose different images for the nodes, for example the nodes without vnc support*


==== Screen Resolutions / Fake Devices

Here are the different configurations for each target device we test for:

[width="80",cols="60,20",options="header",]
|=======================================================================
| Device | Resolution

| selenium-iphone-6 | 375x667
| selenium-ipad-2 | 768x1024
| selenium-xga | 1024x768
| selenium-hd | 1280x720
| selenium-fhd | 1920x1080
|=======================================================================

==== Run Selenium Hub

`codecept run acceptance --env selenium-hub,selenium-xga`

*Please note:* that the SuiteCRM automated test framework uses *height* and *width* values to define the window size instead of the window_size. window_size is ignored by the automated test framework.


==== Selecting Browser

You can select the browser you wish to test by adding it to the --env.

`codecept run demo --env selenium-hub,selenium-chrome`

or

`codecept run demo --env selenium-hub,selenium-firefox`

=== Browser Stack
The SuiteCRM testing framework can be configured to use browser stack service. It requires that you have an account with browser stack that enables automated testing. You also need to configure the testing framework with your username and access key. You can get your details from the https://www.browserstack.com/automate[automate] menu item.

==== Environment Variables

Browser stack require some extra environment variables to be configured

*Browser Stack:*
|=======================================================================
| Variable | Description

| BROWSERSTACK_USERNAME |browser stack user name
| BROWSERSTACK_ACCESS_KEY |access to to use browser stack
|=======================================================================

==== Browser stack local

When you need to test a application that resides on a private server, You will need to run the browser-stack-local env option:

`codecept run demo --env browser-stack-hub,browser-stack-local`


==== Devices

Here are the different configurations for each target device we test for:

[width="80",cols="60,20",options="header",]
|=======================================================================
| Device | Resolution

| browser-stack-chrome-fhd | 1920x1080
| browser-stack-edge-fhd | 1920x1080
| browser-stack-firefox-fhd | 1920x1080
| browser-stack-safari-fhd | 11920x1080
| browser-stack-iphone-6 | 375x667
| browser-stack-ipad-2 | 768x1024
|=======================================================================

using the following command:

`codecept run demo --env browser-stack-hub,browser-stack-local,browser-stack-chrome-fhd`


== References

* http://codeception.com[codeception]
* https://docs.seleniumhq.org/[Selenium]
* https://www.browserstack.com/[Browser Stack]

