---
Title: JSON API Error Object
---

JSON API Error Object
---------------------

Implementation of JSON API Error Object Specification. 
See more: http://jsonapi.org/format/#error-objects[^]

Usage
~~~~~

[source,php]
--

// creating a new Error Object:
$error = new JsonApiErrorObject();

// set some know data about the error:
$error->setTitle(new LangText('LBL_ERROR_LABEL_TITLE'));
$error->setDetail(new LangText('LBL_ERROR_LABEL_DETAIL'));
$error->setCode(ERROR_CODE);
// etc.. see more in source and phpDoc

// creating new Error Object with known data directly in constructor, all parameters are optional:
$error = new JsonApiErrorObject(
    new LangText('LBL_ERROR_LABEL_TITLE'),      // title: a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
    new LangText('LBL_ERROR_LABEL_DETAIL'),     // detail: a human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized.
    ERROR_ID,                                   // id: a unique identifier for this particular occurrence of the problem.
    ERROR_CODE,                                 // code: an application-specific error code, expressed as a string value.
    STATUS,                                     // status: the HTTP status code applicable to this problem, expressed as a string value.
    ['about' => 'Descrioption about the problem'],          // links: a links object
    ['pointer' => '/test/foo/bar', 'parameter' => 'wrong'], // source: an object containing references to the source of the error
    ['some' => 'meta info']                     // meta: a meta object containing non-standard meta-information about the error.
);

// retriving Error Object from an Exception:
try {
  // ...do stuff
} catch (Exception $e) {
  $error->retrieveFromException($e)
}

// retrieving Error object from a ServerRequestInterface:
$error->retrieveFromRequest($request);

// converting to an array:
$error->export();

// converting to a JSON string:
$error->exportJson();

--
