
---
Title: Contributor Agreement
---

== Where can I find the Contributor Agreement?

You can find the contributor agreement
https://www.clahub.com/agreements/salesagility/SuiteCRM[here].

== What is the Contributor Agreement?

The Contributor Agreement is a document which outlines the license
agreement between you (the developer) and us (SalesAgility) for any
contributions made to the SuiteCRM project.

== Why do I need to sign it?

We want SuiteCRM to be the biggest, best, long-term open source CRM
project available globally, so we need to protect the project:

* The Contributor Agreement protects the project and deflects action to
the contributor.
* This means that any legal action for any contributions made to the
project are against Contributor and not Project.
* The Contributor Agreement needs to be signed only once for all pull
requests and contributions in relation to the SuiteCRM project.

== What next?

You will be notified by email if your pull request/contribution is
accepted and included in the SuiteCRM project.
