---
Title: Providing a Feature
weight: 80
---

To contribute a feature to SuiteCRM, similar to providing a Bug Fix, you
must create a forked repository of SuiteCRM and set up your git and
development environment.

Once done, create a new branch from `develop` and name it
relevant to the feature's propose e.g `campaign-wizard-ui`. Following our
link:../coding-standards[Coding Standards] develop the new feature and ensure
your forked repository is kept up to date with minor/major releases. See
our link:../forking[Quick
Guide to Fork SuiteCRM] to update your repository.

Make sure your commit messages are relevant and descriptive. When ready
to submit for review make a Pull Request detailing your feature's
functionality.

Ensure that in your Pull Request that the base fork is
`salesagility/SuiteCRM` and base branch is `develop` and the head fork
is `your repository` and the base branch is your feature branch.

Add any new PHPUnit tests to the new feature branch if required e.g new
modules or classes.

== Reviewing Features

We will review the code and provide feedback within the Pull Request and
issues relating to your feature. If the feature is to be included in the
core product we will request for the forked repo to have an Issues tab
so we can raise any bugs from our testing. This will also allow you to
fix those issues using the below commit message format similar to how to
submit bug fixes to the `hotfix-7.10.x` branch.

`git commit -m "Fixed #1436 - Reports with nested Parentheses are removing parameters"`

{{% notice note %}}
You can add an Issues tab to your forked repository via the `Settings` tab.
{{% /notice %}}

New features that have been accepted and merged will be included in the
next suitable Major release of the project for e.g 7.10 or 7.11 are major
releases. Minor releases only include bug fixes or in-house features
developed, e.g 7.10.5 or 7.11.2 would be minor releases.

