---
Title: Настройка Elasticsearch
Weight: 2
---

:author: likhobory
:email: likhobory@mail.ru

:toc:
:toc-title: Оглавление

{{% notice info %}}
Поисковый движок Elasticsearch доступен в версии 7.11 и выше.
{{% /notice %}}

{{% notice note %}}
SuiteCRM версии 7.11 поддерживает Elasticsearch 5.6. +
SuiteCRM версии 7.12 поддерживает Elasticsearch 7.x.
{{% /notice %}}

Для работы Elasticsearch необходимо Java 8 , поддерживается только *Oracle Java* и *OpenJDK*.

Наиболее быстрый способ установки и запуска сервера Elasticsearch - 
либо из официального образа https://ru.wikipedia.org/wiki/Docker[Docker^], либо из .deb-пакета для систем на базе Debian (например, Ubuntu).


В этом руководстве мы рассмотрим вариант установки Elasticsearch на машине с ОС Ubuntu. 
Другие варианты установки Elasticsearch рассматриваются на странице https://www.elastic.co/guide/en/elasticsearch/reference/5.6/install-elasticsearch.html[официальной документации^].


== Установка из образа Docker (рекомендуется)

{{% notice note %}}
Если Docker отсутствует в системе - установите пакет согласно 
link:https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1[официальному описанию^]. +
После установки убедитесь, что текущий пользователь  link:https://docs.docker.com/install/linux/linux-postinstall[добавлен в группу^] *docker*.
{{% /notice %}}

Загрузка образа с Elasticsearch:

[source,bash]
docker pull docker.elastic.co/elasticsearch/elasticsearch:5.6.13

=== Запуск через *docker run*

Данный способ чаще всего используется при разработке или тестировании:

[source,bash]
docker run -p 9200:9200 -p 9300:9300 \
-e "discovery.type=single-node" -e "xpack.security.enabled=false" \
docker.elastic.co/elasticsearch/elasticsearch:5.6.13

=== Запуск через пакетный менеджер  *docker-compose*

В этом способе все необходимые параметры описываются заранее в отдельном файле.
Создайте файл `docker-compose.yml` со следующим содержимым:

[source,yaml]
----
version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.13
        container_name: elasticsearch
        restart: unless-stopped
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
----

Запустите менеджер командой:

[source,bash]
docker-compose up

== Установка из .deb-пакета

Загрузите пакет `apt-transport-https`:

[source,bash]
sudo apt-get install apt-transport-https

Загрузите и установите публичный ключ:

[source,bash]
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -


Сохраните путь к репозиторию в файле `/etc/apt/sources.list.d/elastic-5.x.list`:

[source,bash]
echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list

Обновите репозиторий и установите OpenJDK 11 и Elasticsearch:

[source,bash]
sudo apt-get update && sudo apt-get install openjdk-11-jre elasticsearch

{{% notice note %}}
Возможно вам потребуется изменить номер версии OpenJDK в соответствии с версией, доступной в вашем дистрибутиве.
{{% /notice %}}

Запустите Elasticsearch командой:

[source,bash]
sudo systemctl start elasticsearch.service

или следующей командой (на устаревших версиях ОС):

[source,bash]
/etc/init.d/elasticsearch start

== Тестирование установленного Elasticsearch

Проверить запущенный сервер можно следующей командой:

[source,bash]
curl -X GET "localhost:9200/"

В случае успешного запуска поискового сервера вы увидите нечто вроде:

[source,json]
----
{
  "name" : "0eeZIeo",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "pfnJ2SzKRTOJ3wMgDhyTQQ",
  "version" : {
    "number" : "5.6.13",
    "build_hash" : "4d5320b",
    "build_date" : "2018-10-30T19:05:08.237Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
----

{{% notice warning %}}
Elasticsearch не имеет встроенного механизма аутентификации.
Позаботьтесь заранее о безопасном доступе к установленному серверу, в противном случае ваши данные могут быть доступны всем желающим!
{{% /notice %}}

