---
Title: Logs and debugging
weight: 80
---

== 1. Logs

The commands used during the upgrade provide some information of the steps and their execution result.
However, sometimes they do not provide a lot of information on error reporting.

There are some logs that may provide more information:

- The *logs/upgrade.log* contains logs that are generated by the upgrade log on SuiteCRM 8 side.

- The *public/legacy/upgradeWizard.log* contains upgrade specific logs that are generated by the legacy part of the app. This file is generated during the `legacy-post-upgrade` step.

- The *logs/<app-env-mode>/<app-env-mode>.log* is the main app log.
Its file path and name changes according to the value set on your `APP_ENV`.  E.g. if it is set to `prod` the path will be `logs/prod/prod.log`. Most likely, this log will not have much upgrade information.

- The *public/legacy/suitecrm.log* is the main log location for the legacy part of the app. It may contain upgrade related logs, as well as other logs.

== 2. APP_ENV mode

When running the app in a production environment the `APP_ENV` in `.env` or in `.env.local` should be set to `prod`. However this mode has a high log level, meaning that not all the debug information will be logged.

One way to get more logs is to change `APP_ENV` to `qa` (this mode should only be used temporarily).

After the `APP_ENV` you may have to clear the symfony cache - from your instance root folder run:

[source,bash]
----
bin/console cache:clear
----
