---
Title: Файлы журнала и отладка системы
weight: 82
---

:author: likhobory
:email: likhobory@mail.ru


:toc:
:toc-title: Оглавление
:toclevels: 1

//
:sectnums:
:sectnumlevels: 1
//

== Файлы журнала

Команды, используемые во время обновления, предоставляют определённую информацию о выполняемых шагах и результатах их выполнения. Однако этой информации может быть  недостаточно при возникновении ошибок.

Есть несколько файлов журнала, которые могут предоставить дополнительную информацию:

. *logs/upgrade.log*
+
Файл журнала, создаваемый при обновлении SuiteCRM 8.
+
. *public/legacy/upgradeWizard.log*
+
Специальный журнал обновления, создаётся устаревшей частью приложения. файл создается на этапе `legacy-post-upgrade`.
+
. *logs/<app-env-mode>/<app-env-mode>.log*
+
Основной журнал системы. Путь к файлу и имя меняются в соответствии со значением, установленным в переменной *APP_ENV*. Например, если значение установлено в `prod`, путь к файлу журнала будет `logs/prod/prod.log`
+
В этом журнале скорее всего не будет содержаться много информации об обновлении.
+
. *public/legacy/suitecrm.log*
+
Это основной журнал устаревшей части приложения. Он может содержать записи, связанные с обновлением, а также другую полезную информацию.

== Переменная APP_ENV 

При запуске приложения в рабочем режиме переменная *APP_ENV* в файлах *.env* или *.env.local* должна быть установлена в значение `prod`. Однако в этом режиме не вся отладочная информация будет регистрироваться.

Один из способов получить более детальную информацию — изменить значение переменной APP_ENV на `qa` (этот режим не следует использовать постоянно).

После этого вам, возможно, придется очистить кеш symfony, для чего в корневой папке приложения выполните следующую команду:

[source,console]
----
bin/console cache:clear
----
