---
Title: Режимы слияния метаданных
weight: 84
---

:author: likhobory
:email: likhobory@mail.ru


:toc:
:toc-title: Оглавление
:toclevels: 1

//
:sectnums:
:sectnumlevels: 1
//

В этой команде вы можете указать режим слияния, который вы хотите использовать при объединении метаданных,
 указав необходимый режим после ключа `-m` в команде `suitecrm:app:upgrade-finalize`.

По умолчанию используется режим `keep`.

== Режим *_KEEP_*

* Этот режим сохранит все существующие ранее метаданные, слияние выполняться не будет.
* Этот режим используется по умолчанию.

В консоли выполните: 

[source,console]
-----
./bin/console suitecrm:app:upgrade-finalize -m keep
-----

==  Режим *_MERGE_*

* Этот режим попытается объединить все существующие ранее метаданные с новыми метаданными. Объединение будет выполнено для каждого модуля.
* Объединенные метаданные помещаются в папку *custom* соответствующего модуля:  `public/legacy/custom/<Module>/metadata`
* В эту же папку добавляется файл резервной копии предыдущей версии метаданных
+
В консоли выполните: 

[source,console]
-----
./bin/console suitecrm:app:upgrade-finalize -m merge
-----

== Режим *_OVERRIDE_*

* Этот режим заменит все текущие настройки новой версией  метаданных.

{{% notice warning %}}
В результате будут удалены все текущие файлы настроек из папки `public/legacy/custom/<Module>/metadata`!
{{% /notice %}}

В консоли выполните: 

[source,console]
-----
./bin/console suitecrm:app:upgrade-finalize -m override
-----