---
Title: Calendar
Weight: 110
---

= Calendar

The Calendar module in SuiteCRM allows you to manage your time by
scheduling Meetings, Calls and Tasks. Users may share their Calendar so
they can allow others to view their upcoming activities. These
activities will be displayed in the Calendar module given that the User
concerned is a participant or the task has been assigned to them.

== Calendar Actions

You can access the Calendar actions from the Calendar module menu drop
down or via the Sidebar. The Calendar actions are as follows:

* *Schedule Meetings* – A new form is opened in the Edit View of the
Meetings module to allow you to create a new Meeting record. This record
will display on the Calendar.
* *Schedule Calls* – A new form is opened in the Edit View of the Call
module to allow you to create a new Call record. This record will
display on the Calendar.
* *Create Task* – A new form is opened in the Edit View of the Tasks
module to allow you to create a new Task record. This record will
display on the Calendar.
* *Today* – Redirects you to the Day format of the Calendar for the
current day.