---
Title: Projects
Weight: 210
---

== Projects

In SuiteCRM the Projects module allows the User to arrange their
organisation's projects by tracking a number of Tasks and allocating
resources. Once set up, a project can be visualised in the form of a
Gantt chart or using the project grid.

=== Projects Actions

You can access the Projects actions from the Projects module menu drop
down or via the Sidebar once you have clicked to view the module. The
Projects actions are as follows:

* *Create Project* – A new form is opened in Edit View to allow you to
create a new Project record.
* *View Project* – Redirects you to the List View for the Projects module.
This allows you to search and list Project records.
* *View Project Tasks* – Allows you to list Project Tasks, which are
related to a parent Project.
* *Import Project* – Redirects you to the Import Wizard for the Projects
module. For more information, see link:http://docs.suitecrm.com/user/user-interface/#_importing_records[Importing
Records].

To view the full list of fields available when creating a Project, See
link:http://docs.suitecrm.com/user/appendix-a/#_projects_field_list[Projects Field List].

=== Creating Projects

In the Projects module, you can create, manage, and duplicate Projects
and Project Tasks.

You can define multiple Project Tasks for each Project. When you create
a Project Task, you must associate it with a Project. You can associate
a Project with multiple activities, Accounts, Opportunities, and Cases.
You can also create Projects and Project Tasks from an Email’s detail
page.

.  In the Actions bar, click Create Project.
.  On the Projects page, enter information for the following fields:
..  Name. Enter a name for the Project.
..  Status. From the drop-down list, select the Project status such as
Draft, In Review, or Published.
..  Start Date. Click the Calendar icon and select the Project start
date.
..  End Date. Click the Calendar icon and select the Project end date.
..  Assigned to. Enter the name of you who has ownership of the Project.
By default, it is assigned to you.
..  Priority. From the drop-down list, select the importance of the
Project such as Low, Medium, or High.
..  Description. Enter a brief description of the Project.
.  Click Save to create the Project; click Cancel to exit the page
without creating the Project.

When you save the Project, the Project’s detail page displays on the
page.

From this page, you can relate the Project to records such as Contacts
and Opportunities.

=== Creating Project Tasks

.  In the Project Tasks sub-panel, click Create.
.  On the Project Tasks page, enter information for the following
fields:
..  Name. Enter a name for the task.
..  Task ID. Enter a numerical value as the task identification number.
..  Start Date. Click the Calendar icon and select the date when the
task is due to begin.
..  Finish Date. Click the Calendar icon and select a date when the task
is due to be completed; enter the start time in the adjoining field.
..  Percentage Complete. Enter a numerical value to indicate what
percentage of the task has been completed.
..  Priority. From the drop-down list, select a priority level that
reflects the importance of completing this task.
..  Milestone. Check this box if the completion on this task is
considered a milestone for project completion.
..  Project Name. Click Select and choose the project associated with
the task.
..  Description. Enter a brief description of the task.
.  Click Save to create the task; click Cancel to return to the project
detail page without creating the task.

=== Managing Projects and Project Tasks

* To sort the List View on the Projects and Project Tasks list view,
click any column title which is sortable. This will sort the column
either ascending or descending.
* To search for a Project or Project task, see the link:http://docs.suitecrm.com/user/user-interface/#_search[Search]
section of this user guide.
* To update some or all the Projects or Project Tasks on the List View,
use the Mass Update panel as described in the
link:http://docs.suitecrm.com/user/user-interface/#_mass_updating_records[Mass Updating Records] section of this user
guide.
* To duplicate a Project, you can click the Duplicate button on the
Detail View and then save the duplicate record.
* To delete one or multiple Projects, you can select multiple records
from the List View and click delete. You can also delete a Project from
the Detail View by clicking the Delete button. For a more detailed guide
on deleting records, see the link:http://docs.suitecrm.com/user/user-interface/#_deleting_records[Deleting Records]
section of this user guide.
* To view the details of a Project or Project Task, click the Project or
Project Task Name in the List View. This will open the record in Detail
View.
* To edit the Project or Project Task details, click Edit icon within
the List View or click the edit button on the Detail View, make the
necessary changes, and click Save.
* For a detailed guide on importing and exporting Projects and Project
Tasks, see the link:http://docs.suitecrm.com/user/user-interface/#_importing_records[Importing Records] and
link:http://docs.suitecrm.com/user/user-interface/#_exporting_records[Exporting Records] sections of this user guide.
* To track all changes to audited fields, in the Project or Project Task
record, you can click the View Change Log button on the Project's or
Project Task's Detail View or Edit View.